// English texts, by id. Everything that is not text (ids, colours, relations, step timing) lives in data.pt.js.
export const T = {
  groups: {
    est: 'Stimulus',
    sens: 'Sensory pathway',
    med: 'Spinal cord',
    enc: 'Brain',
    mot: 'Motor pathway',
    jnm: 'Neuromuscular junction',
  },

  views: {
    body: 'Body',
    skin: 'Skin',
    cord: 'Spinal cord',
    nmj: 'Muscle',
  },

  path: {},

  steps: {
    pisada: {
      title: 'Stepping on the thumbtack',
      text: 'The point of the thumbtack breaks the skin on the sole of the foot. So far there is no nerve signal at all: it is only a mechanical stimulus.',
    },
    pele: {
      title: 'In the skin: stretch becomes an electrical signal',
      text: 'The point stretches the membrane of the sensory nerve ending. Stretch-sensitive Na⁺ channels open, Na⁺ enters and the ending depolarizes: this is the generator potential. When it reaches threshold, an action potential is born.',
    },
    nervo: {
      title: 'Along the nerve to the spinal cord',
      text: 'The action potentials travel up the sensory axon, inside the nerve of the leg, and are regenerated at each segment of the axon. The strength of the stimulus is encoded in the firing frequency.',
    },
    medula: {
      title: 'In the spinal cord: the signal splits',
      text: 'The axon enters through the dorsal root. At the terminals, Ca²⁺ enters and the vesicles release the transmitter, probably glutamate. The EPSPs add up in two neurons of the spinal cord, and from there the signal follows two paths.',
    },
    encefalo: {
      title: 'Path 1: up to the brain',
      text: 'An axon goes up the spinal cord to the brain, where the pain is registered. This happens at the same time as the next step.',
    },
    motor: {
      title: 'Path 2: the motor neuron fires',
      text: 'The other path does not leave the spinal cord: the interneuron excites the motor neuron, which sums the EPSPs and fires. The command leaves through the ventral root, without passing through the brain.',
    },
    juncao: {
      title: 'At the neuromuscular junction',
      text: 'The action potential travels down the motor axon to the muscle. The terminal releases acetylcholine, which opens the nicotinic ACh receptors of the motor end-plate. Na⁺ enters and the muscle fiber fires. This synapse never fails.',
    },
    levanta: {
      title: 'The foot lifts',
      text: 'The muscle fibers contract, the leg bends and the foot moves away from the thumbtack. From contact to movement, the signal passed through three neurons of the model (sensory, interneuron and motor) and did not need the brain.',
    },
  },

  items: {
    tachinha: {
      name: 'Thumbtack',
      morf: 'Thin metal point.',
      func: 'It is the stimulus. When you step on it, the point breaks the skin and stretches the membrane of the sensory nerve endings.',
      more: ['The book uses this scene in chapters 3, 4 and 5 to follow a signal from start to finish.'],
      where: 'On the floor, under the foot. In the Skin view, entering through the sole.',
    },
    pele: {
      name: 'Skin',
      morf: 'Tissue that covers the body. Inside it are the endings of the sensory neurons.',
      func: 'It is where the mechanical stimulus becomes an electrical signal.',
      more: [{ x: 'The drawing shows the skin as a single block, with the surface in a darker shade. The layers of the skin are not covered in chapters 1 to 6.' }],
      where: 'In the Skin view: the block cut in half, with the sole of the foot facing down.',
    },

    terminacao: {
      name: 'Sensory nerve ending',
      morf: 'Tip of the axon of the sensory neuron, inside the skin. The membrane has Na⁺ channels that open when it is stretched.',
      func: 'Turns stretch into an electrical signal. Na⁺ enters and depolarizes the ending: this is the generator potential. If it reaches threshold, an action potential is born.',
      clueTitle: 'Why it matters',
      clue: 'In the sensory neuron, the spike-initiation zone is here, near the ending. In the typical neuron of the brain and spinal cord, it is at the axon hillock.',
      more: [
        'It is all or none: below threshold, nothing happens; above it, the full action potential comes out.',
        'A stronger stimulus does not produce a bigger action potential: it produces more spikes per second. That is how intensity is encoded.',
      ],
      where: 'In the Skin view: the blue branches and the knob just above the point of the thumbtack.',
    },
    'canal-est': {
      name: 'Stretch-sensitive Na⁺ channel',
      morf: 'Protein in the membrane of the sensory nerve ending, with a pore that opens when the membrane is stretched.',
      func: 'Lets Na⁺ in. Because there is much more Na⁺ outside and the inside is negative, it enters forcefully and depolarizes the ending.',
      clueTitle: 'Three ways to open a channel',
      clue: 'This one opens with stretch. The channels of the action potential open with voltage. Those at synapses open with neurotransmitter.',
      where: 'In the Skin view: the green pairs on the surface of the knob of the ending. They move apart when the thumbtack stretches the membrane.',
    },
    sodio: {
      name: 'Sodium (Na⁺)',
      rows: [['Outside', '150 mM'], ['Inside', '15 mM'], ['Equilibrium', '+62 mV']],
      morf: 'Cation ten times more concentrated outside the neuron.',
      func: 'When a Na⁺ channel opens, it enters: diffusion and the negative interior push in the same direction. The entry of positive charge depolarizes the membrane.',
      more: ['It is the same ion at the three points of the story: it enters the ending in the skin, it enters at each segment of the axon during the action potential, and it enters the muscle fiber through the nicotinic ACh receptor.'],
      where: 'In the Skin and Muscle views: the orange spheres.',
    },
    sensorial: {
      name: 'Sensory neuron',
      aka: 'Primary sensory neuron',
      morf: 'Neuron with its ending in the skin and its axon inside the nerve, as far as the spinal cord.',
      func: 'Carries information from the skin to the spinal cord, as action potentials.',
      clueTitle: 'Why it matters',
      clue: 'The action potential is regenerated at each segment of the axon. That is why it reaches the spinal cord the same size as when it left the foot.',
      more: [
        'The sensory nerve fires at high frequency.',
        'The information is carried in the frequency and pattern of the firing, as in Morse code.',
        'With the order-of-magnitude figures of chapter 4, at 10 m/s and lasting 2 ms, each action potential occupies about 2 cm of axon.',
        'Thin axons, like the ones that carry pain, are the most sensitive to local anesthesia.',
        { x: 'The cell body of this neuron is in the dorsal root ganglion, beside the spinal cord.' },
      ],
      where: 'The blue thread: it leaves the sole of the foot, goes up the leg inside the nerve and enters the spinal cord through the dorsal root.',
    },
    nervo: {
      name: 'Nerve',
      morf: 'Bundle of axons outside the central nervous system.',
      func: 'Connects the spinal cord to the leg. It mixes sensory fibers, which go up, and motor fibers, which go down.',
      clueTitle: 'Why it matters',
      clue: 'Each fiber conducts in one direction only. The same nerve carries the news of the thumbtack up and the command to contract down, in different fibers.',
      more: ['The nerves make up the peripheral nervous system.', 'In them, the myelin sheath is made by the Schwann cell.'],
      where: 'The light-colored tube that surrounds the blue thread and the red thread, from the spinal cord to the leg.',
    },
    'raiz-dorsal': {
      name: 'Dorsal root',
      morf: 'Near the spinal cord, the fibers of each nerve divide into two roots. The dorsal root is the one at the back.',
      func: 'Sensory information enters the spinal cord through it.',
      clueTitle: 'In history',
      clue: 'Around 1810, Bell and Magendie cut spinal roots: cutting the ventral root causes paralysis, and the dorsal root carries sensory information. That is how it became known that a nerve mixes the two types of fiber.',
      where: 'In the Spinal cord view: the branch at the back, with a swelling in the middle.',
    },
    ganglio: {
      name: 'Dorsal root ganglion',
      morf: 'Swelling on the dorsal root, beside the spinal cord.',
      func: 'Houses the cell bodies of the sensory neurons.',
      more: [{ x: 'This structure is not in chapters 1 to 6. It was included in the model because the sensory neuron needs a cell body, and that is where it is.' }],
      where: 'In the Spinal cord view: the translucent bulb on the dorsal root, with the blue cell body inside.',
    },

    medula: {
      name: 'Spinal cord',
      morf: 'Part of the central nervous system, together with the brain.',
      func: 'It is where the thumbtack signal passes from the sensory neuron to other neurons and splits: one path goes up to the brain, the other goes to the motor neurons.',
      clueTitle: 'Why it matters',
      clue: 'The command to lift the foot leaves from here. It does not wait for the brain.',
      more: [
        'Glycine is the inhibitory transmitter of the spinal cord and brain stem. Without this inhibition, reflexes become exaggerated: this is the effect of strychnine.',
        { x: 'In cross section, the gray matter is in the middle, shaped like a butterfly, and the white matter is around it.' },
      ],
      where: 'In the Body view: the light-colored cord that runs down from the brain along the back. In the Spinal cord view: a slice in cross section.',
    },
    cinzenta: {
      name: 'Gray matter',
      morf: 'The darker part of nervous tissue.',
      func: 'Receives and sends information through the fibers of the white matter.',
      more: [{ x: 'It is where the cell bodies of the neurons and the synapses are. In the spinal cord, it is shaped like a butterfly: the back part receives the sensory axon, and the motor neurons are in the front part.' }],
      where: 'In the Spinal cord view: the butterfly in the middle of the slice.',
    },
    branca: {
      name: 'White matter',
      morf: 'The lighter part of nervous tissue. It is continuous with the nerves.',
      func: 'Contains the fibers that carry information to and from the gray matter.',
      more: ['In the model, the axon that goes up to the brain runs through it.', { x: 'The light color comes from the myelin that wraps the axons.' }],
      where: 'In the Spinal cord view: the light part around the butterfly.',
    },
    sinapse: {
      name: 'Synapse in the spinal cord',
      morf: 'Contact between the terminal of the sensory axon and the next neuron.',
      func: 'The action potential reaches the terminal, Ca²⁺ enters and the vesicles release the transmitter, probably glutamate. On the other side, the channels let positive charge in: this is an EPSP.',
      clueTitle: 'Why it matters',
      clue: 'A single synapse produces an EPSP of a few tenths of a mV, which is not enough. Because the sensory nerve fires at high frequency and many synapses are activated together, the EPSPs add up and bring the spike-initiation zone to threshold.',
      more: [
        'Temporal summation: EPSPs from the same synapse in rapid succession. Spatial summation: EPSPs from several synapses at the same time.',
        'Glutamate is the main excitatory transmitter of the central nervous system.',
      ],
      where: 'In the Spinal cord view: the lilac knobs where an axon touches the next neuron.',
    },
    interneuronio: {
      name: 'Interneuron',
      morf: 'Neuron that connects only with other neurons. Most neurons are of this type.',
      func: 'In the model, it receives the signal from the sensory neuron and passes it on to the motor neuron.',
      clueTitle: 'To check against the book',
      clue: 'The study guides of this project record only that the signal splits in the spinal cord between the path to the brain and the path to the motor neurons. The interneuron in the middle of the path was drawn from the reflex figure in chapter 3, without checking against the PDF.',
      more: [
        'Not every interneuron excites. A GABAergic interneuron, for example, inhibits its targets.',
        'What happens after each synapse depends on which cell comes next. This explains how a simple stimulus produces a complex behavior, such as shouting and pulling the foot back.',
      ],
      where: 'In the Spinal cord view: the blue-green neuron, between the sensory axon and the motor neuron.',
    },
    ascendente: {
      name: 'Pathway to the brain',
      morf: 'Spinal cord neuron whose axon goes up through the white matter to the brain.',
      func: 'Carries the information about the thumbtack to the brain, where the pain is registered.',
      clueTitle: 'Why it matters',
      clue: 'This path and the path of the motor neuron set off at the same time. Feeling the pain and lifting the foot are two results of the same signal.',
      more: [{ x: 'Anatomically, this axon crosses to the other side of the spinal cord before going up, and there are other stops inside the brain. That is a subject of the somatic sensory system, outside chapters 1 to 6.' }],
      where: 'The purple thread. In the Spinal cord view, it crosses the slice and goes up. In the Body view, it runs beside the spinal cord up to the head.',
    },

    encefalo: {
      name: 'Brain',
      morf: 'Cerebrum, cerebellum and brain stem. With the spinal cord, it forms the central nervous system.',
      func: 'It is where the sensation of pain is registered.',
      clueTitle: 'What it does not do here',
      clue: 'It is not the brain that orders the foot to lift. That command leaves the spinal cord, in parallel with the signal that goes up.',
      more: ['The cerebrum is only one part of the brain.'],
      where: 'In the Body view: inside the head.',
    },

    motor: {
      name: 'Motor neuron',
      morf: 'Neuron with its cell body in the spinal cord and its axon inside the nerve, as far as the muscle.',
      func: 'Sums the EPSPs it receives. If the total reaches threshold at the spike-initiation zone, it fires and carries the command to contract.',
      clueTitle: 'Why it matters',
      clue: 'It is the output of the nervous system. Everything the spinal cord and the brain decide only becomes movement by passing through it.',
      more: [
        'All the motor neurons of the spinal cord and brain stem are cholinergic: they release acetylcholine.',
        'The enzyme ChAT, which makes acetylcholine, is the marker for these neurons.',
        'Its spike-initiation zone is the axon hillock.',
        { x: 'In the drawing, the cell body is in the front (ventral) part of the gray matter.' },
      ],
      where: 'The red thread: it leaves the spinal cord through the ventral root and goes down the nerve to the muscle.',
    },
    'raiz-ventral': {
      name: 'Ventral root',
      morf: 'The front root, of the two into which each nerve divides near the spinal cord.',
      func: 'The axons of the motor neurons leave through it.',
      clueTitle: 'In history',
      clue: 'Bell cut only the ventral roots and saw paralysis: they are motor.',
      where: 'In the Spinal cord view: the front branch, which joins the dorsal root to form the nerve.',
    },

    jnm: {
      name: 'Neuromuscular junction',
      morf: 'Synapse between the axon of the motor neuron and a skeletal muscle fiber. It is one of the largest in the body, and the terminal has many active zones.',
      func: 'Passes the command from the nerve to the muscle. An action potential in the motor axon always produces an action potential in the muscle fiber.',
      clueTitle: 'Why it never fails',
      clue: 'One action potential releases about 200 vesicles and produces an EPSP of 40 mV or more. At a typical synapse of the central nervous system, often only a single vesicle is released.',
      more: [
        'Botulinum toxin destroys SNARE proteins of the terminal and blocks the release of acetylcholine.',
        'Because it is accessible, it is where much of what is known about chemical synapses was discovered.',
      ],
      where: 'In the Muscle view: the pinkish terminal, cut open, resting on the muscle fiber.',
    },
    ach: {
      name: 'Acetylcholine',
      aka: 'ACh',
      morf: 'Neurotransmitter stored in the vesicles of the motor terminal.',
      func: 'Released into the cleft, it binds to the nicotinic ACh receptors of the motor end-plate.',
      clueTitle: 'Why it matters',
      clue: 'It is the receptor, not the transmitter, that decides the effect: the same acetylcholine contracts skeletal muscle and slows the heart.',
      more: [
        'It is made in the cytosol of the terminal by the enzyme ChAT, from choline and acetyl CoA.',
        'Inside a vesicle, it can reach 1,000 mM.',
        'It was the first neurotransmitter identified: Otto Loewi’s Vagusstoff, in 1921.',
      ],
      where: 'In the Muscle view: the yellow spheres inside the terminal are the vesicles; the grains in the cleft are the released acetylcholine.',
    },
    placa: {
      name: 'Motor end-plate',
      aka: 'End-plate',
      morf: 'Patch of the muscle fiber membrane under the terminal. It has folds full of receptors, aligned with the active zones.',
      func: 'It is the postsynaptic side of the junction: it receives the acetylcholine and depolarizes the fiber.',
      where: 'In the Muscle view: the folds on the surface of the fiber, just below the terminal.',
    },
    receptor: {
      name: 'Nicotinic ACh receptor',
      aka: 'Nicotinic cholinergic receptor',
      morf: 'Ion channel of the motor end-plate: five subunits around a pore, like the staves of a barrel.',
      func: 'Opens when two molecules of acetylcholine bind. It lets Na⁺ and K⁺ through; because more Na⁺ enters than K⁺ leaves, the muscle fiber depolarizes.',
      clueTitle: 'Why it excites',
      clue: 'With Na⁺ and K⁺ passing equally, the channel pulls the potential close to 0 mV, above threshold.',
      more: [
        'In muscle, the composition is α2βγδ, with one acetylcholine binding site on each α subunit.',
        'Nicotine activates it, hence the name. Curare and α-bungarotoxin block it and cause paralysis.',
        'If acetylcholine stays high for several seconds, the channel closes even with it present: this is desensitization.',
      ],
      where: 'In the Muscle view: the blue channels at the top of the folds of the motor end-plate.',
    },
    ache: {
      name: 'Acetylcholinesterase',
      aka: 'AChE',
      morf: 'Enzyme deposited in the cleft of the neuromuscular junction by the muscle cells.',
      func: 'Breaks acetylcholine down into choline and acetic acid, and transmission ends. Much of the choline is taken back up by the terminal and reused.',
      clueTitle: 'Why it matters',
      clue: 'Without it, acetylcholine accumulates, the receptors desensitize and transmission fails. That is how nerve gases and organophosphate insecticides act.',
      where: 'In the Muscle view: the green grains in the cleft, between the terminal and the motor end-plate.',
    },
    musculo: {
      name: 'Muscle fiber',
      morf: 'Long cell of skeletal muscle.',
      func: 'Fires an action potential of its own and contracts. With many fibers contracting together, the muscle bends the leg and the foot moves away from the thumbtack.',
      more: [
        'The smooth ER of the muscle fiber is called the sarcoplasmic reticulum.',
        'Actin takes part in contraction (ch. 13).',
        { x: 'The model shows a muscle at the back of the thigh, which bends the knee. The book does not say which muscle lifts the foot.' },
        { x: 'The bands drawn on the fiber are the striations of skeletal muscle.' },
      ],
      where: 'In the Body view: the muscle at the back of the thigh. In the Muscle view: the striated fiber under the terminal.',
    },
  },
};
