// Conteúdo das fichas. Números e termos seguem Bear, Connors & Paradiso, Neurociências, 4ª ed., caps. 2 a 6.
// Em "more", um item { x: '...' } é um detalhe que não está no livro e aparece marcado como "extra".

export const GROUPS = [
  { id: 'soma', name: 'Corpo celular' },
  { id: 'liq', name: 'Líquidos' },
  { id: 'estr', name: 'Membrana e citoesqueleto' },
  { id: 'in', name: 'Entrada do sinal' },
  { id: 'out', name: 'Saída do sinal' },
  { id: 'syn', name: 'Sinapse' },
  { id: 'ap', name: 'Potencial de ação' },
  { id: 'glia', name: 'Glia e tecido' },
];

export const ITEMS = [
  {
    id: 'soma', g: 'soma', name: 'Soma', aka: 'Corpo celular, pericário', color: '#A29BEA', size: '~20 µm',
    morf: 'Parte central do neurônio, de onde saem os neuritos. Por dentro tem o citosol, uma solução salina rica em K⁺, e as organelas.',
    func: 'Abriga o núcleo e as organelas. É onde os genes viram proteínas: tudo o que o neurônio usa sai daqui.',
    clue: 'O citosol rico em K⁺ é a base do potencial de repouso (cap. 3).',
    more: [
      'Tudo o que fica dentro da membrana, menos o núcleo, forma o citoplasma.',
      'Os neurotransmissores peptídicos são feitos aqui: o precursor é montado no RE rugoso e cortado no aparelho de Golgi (cap. 5).',
      'Também recebe sinapses (axossomáticas). As inibitórias costumam se agrupar no soma e perto do cone de implantação.',
    ],
    where: 'Aberto em corte no centro da cena, com as organelas à mostra.',
    rel: ['citosol', 'nucleo', 're-rugoso', 'cone'],
  },
  {
    id: 'nucleo', g: 'soma', name: 'Núcleo', color: '#6A62CF', size: '5–10 µm',
    morf: 'Esfera no meio do soma, com um envelope duplo cheio de poros.',
    func: 'Guarda o DNA. Ali ocorre a transcrição: o gene é copiado em RNAm, que sai pelos poros até os ribossomos.',
    clue: 'O DNA é o mesmo em todas as células do corpo. O que faz um neurônio ser neurônio são os genes que ele usa.',
    more: [
      'Do gene à proteína: transcrição (a RNA-polimerase copia o gene), processamento (saem os íntrons, emendam-se os éxons) e tradução nos ribossomos.',
      'No splicing alternativo, um mesmo gene gera proteínas diferentes.',
      'O genoma humano tem cerca de 25 mil genes.',
    ],
    where: 'Esfera grande dentro do soma. Os pontos escuros são os poros.',
    rel: ['re-rugoso', 'ribossomos'],
  },
  {
    id: 're-rugoso', g: 'soma', name: 'RE rugoso', aka: 'Corpúsculos de Nissl', color: '#C48BE3',
    morf: 'Pilhas de membrana cravejadas de ribossomos, em volta do núcleo.',
    func: 'Faz as proteínas destinadas a membranas (canais, bombas, receptores). Elas são inseridas na membrana enquanto são sintetizadas.',
    clue: 'É abundante no neurônio porque ele depende de muitas proteínas de membrana. Foi o que Nissl viu ao corar o tecido.',
    more: [
      'Neurônios têm mais RE rugoso que a glia e que a maioria das células.',
      'Monta o precursor dos neurotransmissores peptídicos (cap. 5).',
      'O axônio não tem RE rugoso: por isso depende do soma.',
    ],
    where: 'Lâminas curvas ao lado do núcleo, pontilhadas de ribossomos.',
    rel: ['ribossomos', 'golgi', 'membrana'],
  },
  {
    id: 'ribossomos', g: 'soma', name: 'Ribossomos livres', aka: 'Em grupo: polirribossomo', color: '#E9BE4E',
    morf: 'Grãos soltos no citosol. Vários ribossomos lendo o mesmo RNAm formam um polirribossomo.',
    func: 'Fazem as proteínas que ficam no citosol.',
    clue: 'Também aparecem nos dendritos, embaixo dos espinhos.',
    more: [
      'No polirribossomo, cada ribossomo produz uma cópia da mesma proteína.',
      'Na base dos espinhos, a atividade da sinapse pode mandar fabricar proteína ali mesmo, algo importante para guardar informação (cap. 25).',
    ],
    where: 'Grãos dourados soltos no soma. Os enfileirados em arco são polirribossomos.',
    rel: ['re-rugoso', 'espinhos'],
  },
  {
    id: 're-liso', g: 'soma', name: 'RE liso', color: '#7CC4D6',
    morf: 'Membrana sem ribossomos.',
    func: 'Ajuda a dobrar proteínas e regula concentrações internas, como a de Ca²⁺.',
    more: [
      'No músculo, chama-se retículo sarcoplasmático.',
      'Tem canais de Ca²⁺ que o segundo mensageiro IP3 abre, soltando cálcio no citosol (cap. 6).',
    ],
    where: 'Rede de tubos lisos, perto da borda do soma.',
    rel: ['re-rugoso'],
  },
  {
    id: 'golgi', g: 'soma', name: 'Aparelho de Golgi', color: '#F3A56F',
    morf: 'Pilha de discos de membrana.',
    func: 'Processa as proteínas depois da tradução e as endereça para cada parte do neurônio, como axônio ou dendritos.',
    clue: 'É a expedição da fábrica.',
    more: ['Corta o precursor dos neurotransmissores peptídicos. Dele sai o grânulo secretor já cheio, que desce pelo axônio (cap. 5).'],
    where: 'Pilha de discos, do lado do soma oposto ao núcleo.',
    rel: ['re-rugoso', 'axonio', 'granulos'],
  },
  {
    id: 'mitocondria', g: 'soma', name: 'Mitocôndria', color: '#EC766F', size: '~1 µm',
    morf: 'Organela alongada, com a membrana interna dobrada.',
    func: 'Respiração celular: produz ATP.',
    clue: 'O ATP paga as bombas iônicas e o transporte no axônio. O terminal axonal tem muitas mitocôndrias: sinal de gasto alto de energia.',
    more: [
      'Entram ácido pirúvico e oxigênio. O ciclo de Krebs e a cadeia de transporte de elétrons transformam ADP em ATP.',
      'A bomba de sódio e potássio consome até 70% do ATP do encéfalo (cap. 3).',
      'Na membrana externa fica a MAO, enzima que destrói catecolaminas e serotonina recaptadas (cap. 6).',
    ],
    where: 'Cápsulas no soma (uma está aberta, mostrando as dobras) e dentro do terminal, na vista Sinapse.',
    rel: ['terminal', 'bomba', 'microtubulo'],
  },

  {
    id: 'citosol', g: 'liq', name: 'Citosol', short: 'Citosol', color: '#B3A4F0',
    rows: [['K⁺', '100 mM'], ['Na⁺', '15 mM'], ['Ca²⁺', '0,0002 mM'], ['Cl⁻', '13 mM']],
    morf: 'Solução salina que preenche o neurônio por dentro, do soma aos neuritos. É rica em K⁺ e pobre em Na⁺.',
    func: 'É onde ficam as organelas e por onde a corrente elétrica corre dentro do neurônio, carregada por íons.',
    clueTitle: 'Por que importa',
    clue: 'É o lado de dentro da bateria. As bombas mantêm o K⁺ alto aqui e o Na⁺ alto lá fora; essa diferença é o que os canais usam para gerar o potencial de repouso e o potencial de ação.',
    more: [
      'Tudo o que fica dentro da membrana, menos o núcleo, forma o citoplasma: citosol mais organelas.',
      'Conduz muito pior que um fio de cobre: quem carrega a carga são íons, não elétrons livres.',
      'É eletricamente neutro. A carga negativa do repouso fica colada à face interna da membrana.',
      'O Ca²⁺ é mantido baixíssimo pela bomba de cálcio, por proteínas que se ligam a ele e por organelas que o sequestram.',
      'No terminal, os transmissores pequenos são fabricados no citosol e depois concentrados nas vesículas.',
      'Segundos mensageiros, como o AMPc, se difundem por ele (cap. 6).',
    ],
    where: 'No soma aberto, é todo o espaço entre as organelas. Com Líquidos ligado, aparece como o volume lilás dentro do soma, do terminal e do axônio.',
    rel: ['soma', 'extracelular', 'membrana', 'ion-k', 'bomba'],
  },
  {
    id: 'extracelular', g: 'liq', name: 'Líquido extracelular', short: 'Extracelular', color: '#7FD0DA',
    rows: [['K⁺', '5 mM'], ['Na⁺', '150 mM'], ['Ca²⁺', '2 mM'], ['Cl⁻', '150 mM']],
    morf: 'Solução salina que banha neurônios e glia por fora. É rica em Na⁺ e Cl⁻ e pobre em K⁺.',
    func: 'É o lado de fora da bateria. É também por ele que o neurotransmissor se difunde na fenda sináptica.',
    clueTitle: 'Por que importa',
    clue: 'O potencial de repouso é muito sensível ao K⁺ daqui: subir de 5 para 50 mM leva o Vm de −65 para cerca de −17 mV. Por isso os astrócitos e a barreira hematencefálica mantêm esse K⁺ baixo.',
    more: [
      'O espaço é mínimo: os astrócitos preenchem o espaço entre os neurônios, e sobram frestas de cerca de 20 nm. A cena afasta as células para dar para ver.',
      'Como também conduz eletricidade, a corrente que viaja pelo axônio vaza para ele: é a mangueira furada do capítulo 3.',
      'A fenda sináptica faz parte dele, com 20 a 50 nm.',
      'Os astrócitos captam o K⁺ onde houve muita atividade e o espalham pela rede de prolongamentos (tamponamento espacial).',
    ],
    where: 'Todo o espaço fora das células. Com Líquidos ligado, o fundo fica azulado e os pontos soltos representam íons: alaranjados para Na⁺, roxos para K⁺.',
    rel: ['citosol', 'astrocito', 'fenda', 'ion-na', 'sangue'],
  },
  {
    id: 'liquor', g: 'liq', name: 'Líquido dos ventrículos', short: 'Ventrículos', color: '#7DAFEF',
    morf: 'Líquido que enche os ventrículos, as cavidades do encéfalo.',
    func: 'Preenche os ventrículos e fica em contato com as células ependimárias que os revestem.',
    clueTitle: 'Na história',
    clue: 'Galeno achou os ventrículos cheios de líquido e concluiu, errado, que sensação e movimento eram fluidos indo e vindo pelos nervos. A ideia só caiu quando se mostrou que os nervos conduzem eletricidade.',
    more: [{ x: 'Em anatomia ele se chama líquido cerebrospinal, líquido cefalorraquidiano ou líquor. O nome e a função dele não aparecem nos capítulos 1 a 6.' }],
    where: 'Na vista Tecido, com Líquidos ligado: o volume azul à esquerda da parede de células ependimárias.',
    rel: ['ependimaria', 'extracelular'],
  },
  {
    id: 'sangue', g: 'liq', name: 'Sangue', short: 'Sangue', color: '#EFD27F',
    morf: 'Líquido que corre dentro dos capilares.',
    func: 'Traz oxigênio e nutrientes ao tecido nervoso.',
    clueTitle: 'Por que importa',
    clue: 'Não se mistura livremente com o líquido extracelular: a barreira hematencefálica, nas paredes dos capilares, limita a passagem de K⁺.',
    more: [
      'O triptofano, matéria-prima da serotonina, chega ao encéfalo pelo sangue (cap. 6).',
      'A micróglia pode vir do sangue.',
      'No coração não há essa barreira: por isso cloreto de potássio na veia é letal.',
      { x: 'A parte líquida do sangue se chama plasma. As células vermelhas desenhadas são hemácias.' },
    ],
    where: 'Na vista Tecido, com Líquidos ligado: o líquido amarelado dentro do capilar.',
    rel: ['capilar', 'extracelular', 'astrocito'],
  },

  {
    id: 'membrana', g: 'estr', name: 'Membrana neuronal', color: '#7FCBA4', sizeLabel: 'Espessura', size: '5 nm',
    morf: 'Bicamada de fosfolipídios cravejada de proteínas: umas bombeiam substâncias, outras formam poros. A composição muda entre soma, dendritos e axônio.',
    func: 'Barreira para íons. As proteínas dela criam os sinais elétricos do neurônio.',
    clue: 'A diferença entre axônio e dendrito é, no nível molecular, uma diferença de proteínas de membrana.',
    more: [
      'Cada fosfolipídio tem uma cabeça polar, que gosta de água, e uma cauda que foge dela. Em duas camadas, as caudas se escondem no meio.',
      'Canais iônicos: 4 a 6 subunidades em volta de um poro, com seletividade e, em muitos, portão.',
      'Bombas iônicas: enzimas que usam ATP para mover íons contra o gradiente.',
      'A carga separada fica colada às duas faces da membrana (capacitância). O resto das soluções é neutro.',
      'Somando todos os neurônios, dá cerca de 21 mil m² de membrana.',
    ],
    where: 'Na vista Axônio: a parede em duas camadas, aberta em janela. Na vista Impulso: a bicamada com os canais.',
    rel: ['canal-na', 'canal-k', 'bomba', 're-rugoso', 'citosol', 'extracelular'],
  },
  {
    id: 'microtubulo', g: 'estr', name: 'Microtúbulo', color: '#58B9C4', size: '20 nm',
    morf: 'Tubo oco de tubulina, que corre ao longo dos neuritos.',
    func: 'Trilho do transporte axoplasmático: vesículas caminham sobre ele gastando ATP. A cinesina leva do soma ao terminal; a dineína traz de volta.',
    clue: 'O terminal axonal não tem microtúbulos.',
    more: [
      'Proteínas associadas (MAPs), como a tau, organizam os microtúbulos. No Alzheimer, a tau se solta e se acumula em emaranhados neurofibrilares.',
      'Transporte rápido: até 1.000 mm por dia. Transporte lento: 1 a 10 mm por dia.',
      'Os vírus do herpes e da raiva entram no sistema nervoso pelo transporte retrógrado.',
    ],
    where: 'Na vista Axônio: os tubos ocos mais grossos.',
    rel: ['neurofilamento', 'microfilamento', 'axonio'],
  },
  {
    id: 'neurofilamento', g: 'estr', name: 'Neurofilamento', color: '#D6B95B', size: '10 nm',
    morf: 'Subunidades trançadas como corda.',
    func: 'Resistência mecânica. É o mais resistente dos três e faz o papel de osso.',
    more: ['É um filamento intermediário, parente da queratina do pelo.'],
    where: 'Na vista Axônio: as cordas trançadas, de espessura média.',
    rel: ['microtubulo', 'microfilamento'],
  },
  {
    id: 'microfilamento', g: 'estr', name: 'Microfilamento', color: '#EE8DB0', size: '5 nm',
    morf: 'Duas fitas trançadas de actina, presas à membrana.',
    func: 'Muda a forma da célula.',
    more: ['O citoesqueleto é montado e desmontado o tempo todo.', 'No músculo, a actina participa da contração (cap. 13).'],
    where: 'Na vista Axônio: os fios mais finos, colados por dentro da membrana.',
    rel: ['microtubulo', 'neurofilamento', 'membrana'],
  },

  {
    id: 'neuritos', g: 'in', name: 'Neuritos', color: '#9AB0C4', also: ['dendritos', 'espinhos', 'axonio', 'colaterais', 'cone'],
    morf: 'Prolongamentos finos que saem do soma. São de dois tipos: axônio e dendritos.',
    func: 'Nome geral. Os dendritos são a entrada do sinal; o axônio é a saída.',
    more: ['Pelo número de neuritos, o neurônio é unipolar, bipolar ou multipolar. A maioria no encéfalo é multipolar.'],
    where: 'Tudo o que sai do soma. Ao escolher este item, dendritos e axônio ficam em destaque juntos.',
    rel: ['dendritos', 'axonio'],
  },
  {
    id: 'dendritos', g: 'in', name: 'Dendritos', aka: 'Árvore dendrítica', color: '#74AEEE', sizeLabel: 'Comprimento', size: 'Raramente passam de 2 mm',
    morf: 'Vários por neurônio, curtos, ramificados, e afinam na ponta.',
    func: 'Antenas: recebem milhares de sinapses. A membrana embaixo delas tem receptores que detectam os neurotransmissores.',
    clue: 'Árvore elaborada indica célula especializada em receber muitos sinais.',
    more: [
      'Aqui o sinal não se regenera: cada PEPS é pequeno e decai com a distância. A uma constante de comprimento (λ) da sinapse, sobram 37%.',
      'O neurônio soma os PEPS no espaço (várias sinapses ao mesmo tempo) e no tempo (a mesma sinapse em sequência rápida).',
      'A maioria dos dendritos tem canais de Na⁺, Ca²⁺ e K⁺ dependentes de voltagem, que amplificam PEPS pequenos e distantes.',
    ],
    where: 'Os ramos que saem do soma em várias direções.',
    rel: ['espinhos', 'sinapse', 'receptores'],
  },
  {
    id: 'espinhos', g: 'in', name: 'Espinhos dendríticos', color: '#A3CFF6',
    morf: 'Pequenas bolsas penduradas no dendrito.',
    func: 'Recebem sinapses e isolam as reações químicas disparadas por cada uma. Mudam de forma conforme a atividade.',
    more: [
      'A sinapse feita em um espinho se chama axoespinhosa.',
      'Na base há polirribossomos: a sinapse pode mandar fabricar proteína no local.',
      'Em crianças com deficiência intelectual, os espinhos são menos numerosos, longos e finos, parecidos com os de fetos.',
    ],
    where: 'As bolinhas ao longo dos dendritos. Na vista Sinapse, a bolsa logo abaixo da fenda.',
    rel: ['dendritos', 'sinapse', 'ribossomos'],
  },

  {
    id: 'cone', g: 'out', name: 'Cone de implantação', aka: 'Zona de gatilho', color: '#F2BE63',
    morf: 'Região do soma que afunila até o segmento inicial do axônio.',
    func: 'Zona de gatilho: os canais de Na⁺ dependentes de voltagem são densos aqui, e é onde nasce o potencial de ação.',
    clue: 'Vale para o neurônio típico do encéfalo e da medula. No neurônio sensorial, o gatilho fica perto da terminação sensorial.',
    more: [
      'O neurônio dispara quando a soma dos PEPS, descontada a inibição, atinge o limiar aqui.',
      'Soma e dendritos em geral não disparam potenciais de ação de Na⁺, porque têm poucos desses canais.',
    ],
    where: 'O funil entre o soma e o axônio. Os pontos vermelhos marcam canais de Na⁺.',
    rel: ['canal-na', 'axonio', 'nodulo'],
  },
  {
    id: 'axonio', g: 'out', name: 'Axônio', color: '#ED9F67', size: '<1 mm a >1 m de comprimento; <1 a ~25 µm de diâmetro',
    morf: 'Um por neurônio, com diâmetro uniforme e ramos em ângulo reto. Não tem RE rugoso e quase não tem ribossomos.',
    func: 'Conduz o potencial de ação para longe do soma. Quanto mais grosso, mais rápido.',
    clue: 'Sem ribossomos, não fabrica proteínas: tudo vem do soma. Separado dele, degenera (degeneração walleriana).',
    more: [
      'O potencial de ação se regenera a cada trecho e não encolhe no caminho. Não volta porque o trecho de trás está refratário.',
      'A cerca de 10 m/s e com 2 ms de duração, um potencial de ação ocupa uns 2 cm de axônio por vez.',
      'Enzimas e grânulos de peptídeo descem do soma por transporte axoplasmático.',
      'Na lula, o axônio gigante chega a 1 mm de diâmetro. Foi nele que Hodgkin e Huxley trabalharam.',
    ],
    where: 'O fio longo que sai do cone. Aparece nu no começo, nos nódulos e no fim.',
    rel: ['cone', 'mielina', 'colaterais', 'terminal', 'microtubulo'],
  },
  {
    id: 'colaterais', g: 'out', name: 'Colaterais', color: '#DB8552',
    morf: 'Ramos do axônio, que saem em ângulo reto. As que voltam para a própria célula ou para células vizinhas são colaterais recorrentes.',
    func: 'Levam o mesmo sinal a outros alvos.',
    where: 'O ramo que sai do axônio em um nódulo.',
    rel: ['axonio', 'terminal'],
  },
  {
    id: 'mielina', g: 'out', name: 'Bainha de mielina', color: '#EFE4C8',
    morf: 'Membrana de glia enrolada em espiral em volta do axônio, interrompida a intervalos.',
    func: 'Isola o axônio: menos corrente vaza pela membrana, e a condução acelera.',
    clue: 'Não é parte do neurônio. É membrana de oligodendrócito (no sistema nervoso central) ou de célula de Schwann (no periférico).',
    more: [
      'Na esclerose múltipla, a mielina do sistema nervoso central é atacada, e a condução fica lenta ou falha.',
      'Na síndrome de Guillain-Barré, o ataque é à mielina dos nervos periféricos.',
    ],
    where: 'As capas claras em volta do axônio. Na vista Axônio, o corte mostra a espiral.',
    rel: ['oligodendrocito', 'schwann', 'nodulo'],
  },
  {
    id: 'nodulo', g: 'out', name: 'Nódulo de Ranvier', color: '#F6B77A', sizeLabel: 'Espaçamento', size: '0,2 a 2 mm',
    morf: 'Intervalo sem mielina, onde a membrana do axônio fica exposta e os canais de Na⁺ se concentram.',
    func: 'Regenera o potencial de ação, que salta de nódulo em nódulo (condução saltatória).',
    more: ['Quanto mais grosso o axônio, mais espaçados os nódulos.'],
    where: 'Os intervalos entre duas capas de mielina. Os pontos vermelhos marcam canais de Na⁺.',
    rel: ['mielina', 'canal-na', 'cone'],
  },
  {
    id: 'terminal', g: 'out', name: 'Terminal axonal', aka: 'Botão terminal', color: '#EE8AA4',
    morf: 'Ponta dilatada do axônio. Não tem microtúbulos, é cheia de vesículas sinápticas, tem um revestimento denso de proteínas na face voltada para a sinapse e muitas mitocôndrias.',
    func: 'Converte o sinal elétrico em químico: libera neurotransmissor na fenda.',
    more: [
      'O axônio pode terminar em vários ramos curtos (arborização terminal) ou fazer sinapses de passagem (botões en passant).',
      'Os transmissores pequenos (aminoácidos e aminas) são fabricados aqui mesmo, no citosol, por enzimas que vieram do soma.',
      'Transportadores da membrana recaptam o transmissor da fenda, usando o gradiente de Na⁺.',
      'Autorreceptores sentem o transmissor liberado e freiam a liberação, como uma válvula de segurança.',
    ],
    where: 'Os botões no fim do axônio. Por dentro, na vista Sinapse.',
    rel: ['vesiculas', 'zona-ativa', 'sinapse', 'mitocondria'],
  },

  {
    id: 'sinapse', g: 'syn', name: 'Sinapse', color: '#C97BD8', sizeLabel: 'Fenda', size: '20 a 50 nm',
    morf: 'Tem um lado pré-sináptico (em geral, o terminal), a fenda sináptica e um lado pós-sináptico (dendrito ou soma de outro neurônio), com receptores.',
    func: 'Ponto de contato onde o sinal passa de uma célula a outra: chega elétrico, vira químico e volta a ser elétrico do outro lado.',
    clue: 'Sinapse tipo I de Gray (assimétrica, lado pós mais espesso) costuma ser excitatória. Tipo II (simétrica) costuma ser inibitória.',
    more: [
      'Em seis passos: chega o potencial de ação; abrem-se canais de Ca²⁺; a vesícula se funde e solta o transmissor; ele cruza a fenda; o receptor responde; o transmissor é retirado.',
      'Pelo lugar do contato: axodendrítica, axossomática, axoaxônica ou axoespinhosa.',
      'A maioria das sinapses do sistema nervoso maduro é química. Também existem sinapses elétricas (junções comunicantes, a 3 nm), bidirecionais e quase instantâneas.',
      'Uma sinapse típica do sistema nervoso central gera um PEPS de alguns décimos de mV. Sozinha, não faz o neurônio disparar.',
    ],
    where: 'Onde um botão terminal toca o dendrito do neurônio seguinte. Em detalhe, na vista Sinapse.',
    rel: ['terminal', 'vesiculas', 'fenda', 'receptores', 'astrocito'],
  },
  {
    id: 'vesiculas', also: ['neurotransmissor'], g: 'syn', name: 'Vesículas sinápticas', color: '#F1CF62', size: '~50 nm',
    morf: 'Esferas de membrana dentro do terminal. O neurotransmissor fica guardado no interior delas, o lúmen.',
    func: 'Guardam o neurotransmissor e o liberam na fenda por exocitose: a membrana da vesícula se funde com a do terminal.',
    clue: 'A liberação é rápida porque as vesículas já estão atracadas na zona ativa, bem onde o Ca²⁺ entra.',
    more: [
      'Transportadores na membrana da vesícula concentram o transmissor lá dentro até 100 mil vezes, trocando cada molécula por um H⁺.',
      'O lúmen é ácido: uma bomba de H⁺ movida a ATP mantém isso, e é esse gradiente de H⁺ que o transportador usa.',
      'Cada vesícula carrega alguns milhares de moléculas de transmissor.',
      'Proteínas SNARE amarram a vesícula à membrana do terminal. A sinaptotagmina sente o Ca²⁺ e dispara a fusão.',
      'Depois da exocitose, a membrana é recuperada por endocitose, e a vesícula é recarregada.',
      'Guardam aminoácidos e aminas. Peptídeos ficam nos grânulos secretores.',
    ],
    where: 'Na vista Sinapse: as esferas dentro do terminal. Duas estão abertas, mostrando o neurotransmissor no lúmen.',
    rel: ['neurotransmissor', 'zona-ativa', 'granulos', 'terminal'],
  },
  {
    id: 'neurotransmissor', g: 'syn', name: 'Neurotransmissor', color: '#F2A541',
    morf: 'Molécula guardada no lúmen das vesículas sinápticas. Há três famílias: aminoácidos (glutamato, GABA, glicina), aminas (acetilcolina, dopamina, noradrenalina, serotonina) e peptídeos.',
    func: 'Liberado na fenda, atravessa até a membrana pós-sináptica e se liga aos receptores, como chave na fechadura.',
    clue: 'Quem decide o efeito é o receptor, não o transmissor: a mesma acetilcolina contrai o músculo esquelético e desacelera o coração.',
    more: [
      'Sai da fenda por difusão, por recaptação (transportadores do terminal e da glia) ou por degradação enzimática, como a da acetilcolina pela acetilcolinesterase.',
      'O glutamato é o principal transmissor excitatório do encéfalo; o GABA, o principal inibitório.',
      'Dentro de uma vesícula colinérgica, a acetilcolina pode chegar a 1.000 mM.',
      'Para ser chamada de neurotransmissor, a molécula precisa ser sintetizada e guardada no neurônio pré-sináptico, ser liberada quando ele é estimulado e, aplicada de fora, imitar o efeito da sinapse.',
    ],
    where: 'Na vista Sinapse: os grãos alaranjados dentro das vesículas abertas e espalhados na fenda.',
    rel: ['vesiculas', 'receptores', 'fenda', 'astrocito'],
  },
  {
    id: 'granulos', g: 'syn', name: 'Grânulos secretores', aka: 'Vesículas grandes e eletronicamente densas', color: '#B98A5A', size: '~100 nm',
    morf: 'Vesículas maiores, que aparecem escuras ao microscópio eletrônico.',
    func: 'Guardam os neurotransmissores peptídicos e os liberam por exocitose dependente de Ca²⁺, fora das zonas ativas.',
    clue: 'Como ficam longe das zonas ativas, um potencial de ação isolado não basta: é preciso uma salva em alta frequência, que eleve o Ca²⁺ no terminal inteiro.',
    more: ['Já saem cheios do aparelho de Golgi, no soma, e descem pelo axônio por transporte axoplasmático.', 'A liberação é lenta: 50 ms ou mais.'],
    where: 'Na vista Sinapse: as duas esferas maiores e mais escuras, no alto do terminal.',
    rel: ['golgi', 'vesiculas', 'neurotransmissor'],
  },
  {
    id: 'zona-ativa', g: 'syn', name: 'Zona ativa', color: '#B54C6C',
    morf: 'Acúmulo de proteínas na face do terminal voltada para a fenda, onde as vesículas se agrupam.',
    func: 'É o lugar onde o neurotransmissor é liberado.',
    more: ['Sinapses maiores têm mais zonas ativas. A junção neuromuscular tem muitas.', 'Do outro lado da fenda fica a densidade pós-sináptica, com os receptores.'],
    where: 'Na vista Sinapse: o disco escuro no fundo do terminal, com vesículas atracadas.',
    rel: ['canal-ca', 'vesiculas', 'receptores'],
  },
  {
    id: 'canal-ca', g: 'syn', name: 'Canal de Ca²⁺ dependente de voltagem', color: '#4FB6A6',
    morf: 'Proteína da membrana do terminal, nas zonas ativas. É parente do canal de Na⁺ do potencial de ação, mas deixa passar Ca²⁺.',
    func: 'Abre quando o potencial de ação despolariza o terminal. O Ca²⁺ entra, e essa subida é o sinal para as vesículas liberarem o transmissor.',
    clue: 'A força que empurra o Ca²⁺ para dentro é enorme: em repouso, há só 0,0002 mM no citosol.',
    more: ['Junto da zona ativa, o Ca²⁺ passa de 0,01 mM quando os canais abrem.', 'Em uma sinapse de mamífero, a liberação pode começar cerca de 60 µs depois da entrada do cálcio.'],
    where: 'Na vista Sinapse: as proteínas verde-azuladas na borda de baixo do terminal.',
    rel: ['zona-ativa', 'vesiculas', 'canal-na'],
  },
  {
    id: 'fenda', also: ['neurotransmissor'], g: 'syn', name: 'Fenda sináptica', color: '#C9A6E0', sizeLabel: 'Largura', size: '20 a 50 nm',
    morf: 'Espaço entre as membranas pré e pós-sináptica, preenchido por uma matriz de proteínas fibrosas que mantém as duas unidas.',
    func: 'O neurotransmissor se difunde por ela até os receptores.',
    more: ['É cerca de 10 vezes mais larga que a distância em uma junção comunicante (3 nm).', 'Astrócitos em volta limitam a difusão do transmissor e o retiram da fenda.'],
    where: 'Na vista Sinapse: o espaço entre o terminal e o espinho, com o neurotransmissor.',
    rel: ['neurotransmissor', 'receptores', 'extracelular', 'astrocito'],
  },
  {
    id: 'receptores', g: 'syn', name: 'Receptores', aka: 'Na densidade pós-sináptica', color: '#6C8BF0',
    morf: 'Proteínas da membrana pós-sináptica. São de dois tipos: canais iônicos ativados por transmissor (quatro ou cinco subunidades em volta de um poro) e receptores acoplados a proteínas G.',
    func: 'Detectam o neurotransmissor. O canal abre em microssegundos e gera um PEPS (se entra Na⁺) ou um PIPS (se entra Cl⁻). O receptor acoplado a proteína G age mais devagar, por mais tempo, e modula.',
    clue: 'O canal aberto por glutamato ou acetilcolina puxa o Vm para perto de 0 mV, acima do limiar: excita. O canal de Cl⁻ aberto por GABA ou glicina segura o Vm perto de −65 mV: inibe.',
    more: [
      'Receptores de glutamato: AMPA (PEPS rápido) e NMDA (deixa entrar Ca²⁺ e só conduz com glutamato e despolarização juntos, porque o Mg²⁺ tapa o poro em repouso).',
      'O receptor acoplado a proteína G atravessa a membrana sete vezes. A proteína G abre um canal direto (via de atalho) ou liga uma cascata de segundos mensageiros.',
      'Há bem mais de 100 receptores, e um mesmo transmissor pode ativar vários subtipos.',
    ],
    where: 'Na vista Sinapse: os canais azuis em cima do espinho, voltados para a fenda.',
    rel: ['neurotransmissor', 'espinhos', 'fenda'],
  },

  {
    id: 'canal-na', also: ['ion-na'], g: 'ap', name: 'Canal de Na⁺ dependente de voltagem', color: '#EE8660',
    morf: 'Um único polipeptídeo longo com 4 domínios (I a IV), cada um com 6 alfa-hélices que atravessam a membrana (S1 a S6). Os quatro domínios se juntam em volta do poro.',
    func: 'Abre quando a membrana despolariza até o limiar. O Na⁺ entra e produz a fase ascendente. Fica aberto cerca de 1 ms e se inativa.',
    clue: 'A hélice S4, com aminoácidos positivos, é o sensor de voltagem. Na inativação, uma parte globular da proteína tampa o poro: isso explica a brevidade do potencial de ação e o período refratário absoluto.',
    more: [
      'O filtro de seletividade deixa o canal cerca de 12 vezes mais permeável ao Na⁺ que ao K⁺.',
      'Só pode abrir de novo depois que o Vm volta para perto do repouso (desinativação).',
      'A tetrodotoxina (TTX), do baiacu, tampa o poro pelo lado de fora. A lidocaína entra pelo portão aberto e se liga por dentro.',
      'É denso no cone de implantação e nos nódulos de Ranvier.',
    ],
    where: 'Na vista Impulso: os canais alaranjados. A bolinha presa embaixo é a parte que tampa o poro na inativação.',
    rel: ['canal-k', 'ion-na', 'cone', 'nodulo'],
  },
  {
    id: 'canal-k', also: ['ion-k'], g: 'ap', name: 'Canal de K⁺ dependente de voltagem', color: '#8177E6',
    morf: 'Quatro subunidades separadas em volta do poro (no canal de Na⁺, é um polipeptídeo só, com quatro domínios).',
    func: 'Também abre com a despolarização, mas cerca de 1 ms depois. O K⁺ sai, e o Vm volta a ficar negativo: é a fase descendente.',
    clue: 'Por abrir com atraso, essa condutância foi chamada de retificador com retardo. Enquanto o canal continua aberto, o Vm passa do repouso e se aproxima do EK: é a hiperpolarização pós-potencial.',
    more: ['Em cada subunidade, uma alça do poro forma o filtro de seletividade.', 'Canais de K⁺ lentos, que vão se acumulando abertos durante o estímulo, fazem alguns neurônios dispararem cada vez mais devagar (adaptação).'],
    where: 'Na vista Impulso: os canais roxos.',
    rel: ['canal-na', 'ion-k', 'canal-vaz'],
  },
  {
    id: 'canal-vaz', also: ['ion-k'], g: 'ap', name: 'Canal de K⁺ aberto no repouso', color: '#B5ACF3',
    morf: 'Canal de K⁺ que já fica aberto no repouso, sem depender de voltagem.',
    func: 'Deixa o K⁺ sair a favor do gradiente. Cada K⁺ que sai deixa uma carga negativa para trás, e o interior fica negativo: é o potencial de repouso.',
    clue: 'Em repouso, a membrana é cerca de 40 vezes mais permeável ao K⁺ que ao Na⁺. Um pequeno vazamento de Na⁺ impede o Vm de chegar ao EK (−80 mV) e o deixa em cerca de −65 mV.',
    where: 'Na vista Impulso: o canal lilás, por onde o K⁺ sai devagar o tempo todo.',
    rel: ['ion-k', 'bomba', 'canal-k'],
  },
  {
    id: 'bomba', also: ['ion-na', 'ion-k'], g: 'ap', name: 'Bomba de sódio e potássio', color: '#57B98F',
    morf: 'Enzima da membrana.',
    func: 'Quebra ATP e troca Na⁺ de dentro por K⁺ de fora, contra os dois gradientes.',
    clue: 'Trabalha o tempo todo, como a bomba que tira do barco a água de cada onda. Sem ela não há gradiente; sem gradiente, não há potencial de repouso nem potencial de ação.',
    more: ['Consome até 70% do ATP do encéfalo.', 'Um potencial de ação move tão poucos íons que as concentrações quase não mudam.'],
    where: 'Na vista Impulso: a proteína verde, maior que os canais.',
    rel: ['ion-na', 'ion-k', 'mitocondria'],
  },
  {
    id: 'ion-na', g: 'ap', name: 'Sódio (Na⁺)', color: '#F29A4A', sizeLabel: 'Concentração', size: '150 mM fora, 15 mM dentro',
    morf: 'Cátion dez vezes mais concentrado fora do neurônio.',
    func: 'Quando seus canais abrem, entra com força: a difusão e o interior negativo empurram no mesmo sentido. O Vm corre em direção ao ENa (+62 mV).',
    more: ['Na água, cada íon fica envolto em uma esfera de hidratação.', 'Corrente de um íon = condutância × força motriz (Vm − Eíon).'],
    where: 'Na vista Impulso: as esferas alaranjadas, quase todas do lado de fora.',
    rel: ['canal-na', 'bomba', 'ion-k', 'extracelular'],
  },
  {
    id: 'ion-k', g: 'ap', name: 'Potássio (K⁺)', color: '#8D7CF0', sizeLabel: 'Concentração', size: '5 mM fora, 100 mM dentro',
    morf: 'Cátion vinte vezes mais concentrado dentro do neurônio.',
    func: 'Sai pelos canais de K⁺ e puxa o Vm para o EK (−80 mV). Domina o repouso e faz a repolarização.',
    more: ['O Vm é muito sensível ao K⁺ de fora: subir de 5 para 50 mM leva o repouso de −65 para cerca de −17 mV.', 'Astrócitos e a barreira hematencefálica mantêm baixo o K⁺ de fora.'],
    where: 'Na vista Impulso: as esferas roxas, quase todas do lado de dentro.',
    rel: ['canal-k', 'canal-vaz', 'bomba', 'citosol', 'astrocito'],
  },

  {
    id: 'astrocito', g: 'glia', name: 'Astrócito', color: '#5DC3A8',
    morf: 'A glia mais numerosa. Tem muitos prolongamentos, que preenchem o espaço entre os neurônios e envolvem sinapses.',
    func: 'Regula o meio: controla o K⁺ extracelular, limita a difusão do neurotransmissor e o retira da fenda.',
    more: [
      'Tamponamento espacial de potássio: capta o K⁺ onde houve muita atividade e o espalha pela rede de prolongamentos (cap. 3).',
      'Tem transportadores que recaptam glutamato e GABA, e faz a maior parte desse trabalho (cap. 5).',
      'Tem receptores para neurotransmissores, que disparam eventos elétricos e químicos nele próprio.',
      { x: 'Na vista Tecido, alguns prolongamentos encostam no capilar. Esse contato não é descrito nos capítulos 2 a 6.' },
    ],
    where: 'A célula em estrela perto dos terminais, com um prolongamento na sinapse. Também nas vistas Tecido e Glia.',
    rel: ['sinapse', 'extracelular', 'ion-k', 'capilar', 'oligodendrocito'],
  },
  {
    id: 'oligodendrocito', g: 'glia', name: 'Oligodendrócito', color: '#DDBB62',
    morf: 'Glia do sistema nervoso central. Uma célula estende braços e enrola vários axônios.',
    func: 'Forma a bainha de mielina no sistema nervoso central.',
    where: 'A célula ao lado do axônio, com braços até a mielina deste axônio e a de um vizinho. Também nas vistas Tecido e Glia.',
    rel: ['mielina', 'schwann'],
  },
  {
    id: 'schwann', g: 'glia', name: 'Célula de Schwann', color: '#E0A083',
    morf: 'Glia do sistema nervoso periférico. Cada célula enrola um só axônio.',
    func: 'Forma a bainha de mielina no sistema nervoso periférico.',
    where: 'Na vista Glia: cada capa é uma célula, com seu núcleo, em volta de um só axônio.',
    rel: ['mielina', 'oligodendrocito', 'nodulo'],
  },
  {
    id: 'microglia', g: 'glia', name: 'Micróglia', color: '#A3C866',
    morf: 'Célula pequena.',
    func: 'Fagocita restos de células mortas e parece remodelar sinapses, eliminando algumas.',
    more: ['Pode vir do sangue.', { x: 'Os prolongamentos finos e ramificados do desenho são a forma usual da micróglia; o livro não a descreve nesses capítulos.' }],
    where: 'A célula pequena e ramificada perto do soma. Também nas vistas Tecido e Glia.',
    rel: ['astrocito'],
  },
  {
    id: 'ependimaria', g: 'glia', name: 'Células ependimárias', color: '#9FB3CC',
    morf: 'Células que formam a camada de revestimento dos ventrículos.',
    func: 'Revestem os ventrículos e guiam a migração de células durante o desenvolvimento.',
    more: ['Os ventrículos são cavidades do encéfalo cheias de líquido (cap. 1).'],
    where: 'Na vista Tecido: a parede de células à esquerda. Na vista Glia: a fileira de células lado a lado.',
    rel: ['liquor', 'astrocito'],
  },
  {
    id: 'capilar', g: 'glia', name: 'Capilar', aka: 'Vaso sanguíneo', color: '#E79A9A',
    morf: 'Vaso fino que atravessa o tecido nervoso.',
    func: 'Leva oxigênio e nutrientes ao tecido.',
    clue: 'Nas paredes dos capilares do encéfalo fica a barreira hematencefálica, que limita a passagem de K⁺ do sangue para o tecido.',
    more: [{ x: 'As células vermelhas desenhadas dentro do vaso são hemácias.' }],
    where: 'Na vista Tecido: o tubo rosado que cruza a cena, com prolongamentos de astrócitos encostados.',
    rel: ['sangue', 'astrocito', 'ion-k'],
  },
];

export const BY_ID = Object.fromEntries(ITEMS.map((i) => [i.id, i]));

// Caminho do sinal, na ordem em que ele percorre o neurônio.
export const PATH = [
  ['dendritos', 'recebe o sinal'],
  ['soma', 'integra o que chegou'],
  ['cone', 'dispara o potencial de ação'],
  ['axonio', 'conduz para longe'],
  ['nodulo', 'regenera o sinal a cada salto'],
  ['terminal', 'troca elétrico por químico'],
  ['sinapse', 'atravessa a fenda até o dendrito seguinte'],
];

// Da escala maior para a menor; Glia é a comparação dos cinco tipos.
export const VIEWS = [
  { id: 'tissue', name: 'Tecido' },
  { id: 'world', name: 'Neurônio' },
  { id: 'soma', name: 'Soma' },
  { id: 'axon', name: 'Axônio' },
  { id: 'syn', name: 'Sinapse' },
  { id: 'ap', name: 'Impulso' },
  { id: 'glia', name: 'Glia' },
];
