// English texts, by id. Everything that is not text (ids, colours, relations) lives in data.pt.js.
export const T = {
  groups: {
    soma: 'Cell body',
    liq: 'Fluids',
    estr: 'Membrane and cytoskeleton',
    in: 'Signal input',
    out: 'Signal output',
    syn: 'Synapse',
    ap: 'Action potential',
    glia: 'Glia and tissue',
  },
  views: {
    tissue: 'Tissue',
    world: 'Neuron',
    soma: 'Soma',
    axon: 'Axon',
    syn: 'Synapse',
    ap: 'Impulse',
    glia: 'Glia',
  },
  path: {
    dendritos: 'receives the signal',
    soma: 'integrates what arrived',
    cone: 'fires the action potential',
    axonio: 'conducts it away',
    nodulo: 'regenerates the signal at each jump',
    terminal: 'swaps electrical for chemical',
    sinapse: 'crosses the cleft to the next dendrite',
  },
  steps: {},
  items: {
    soma: {
      name: 'Soma', aka: 'Cell body, perikaryon',
      morf: 'Central part of the neuron, from which the neurites extend. Inside it has the cytosol, a salty solution rich in K⁺, and the organelles.',
      func: 'Houses the nucleus and the organelles. It is where genes become proteins: everything the neuron uses comes from here.',
      clue: 'The K⁺-rich cytosol is the basis of the resting potential (ch. 3).',
      more: [
        'Everything inside the membrane, except the nucleus, makes up the cytoplasm.',
        'Peptide neurotransmitters are made here: the precursor is assembled in the rough ER and cleaved in the Golgi apparatus (ch. 5).',
        'It also receives synapses (axosomatic). Inhibitory ones tend to cluster on the soma and near the axon hillock.',
      ],
      where: 'Cut open at the center of the scene, with the organelles exposed.',
    },
    nucleo: {
      name: 'Nucleus',
      morf: 'Sphere in the middle of the soma, with a double envelope full of pores.',
      func: 'Holds the DNA. Transcription takes place there: the gene is copied into mRNA, which leaves through the pores to the ribosomes.',
      clue: 'The DNA is the same in every cell of the body. What makes a neuron a neuron is the genes it uses.',
      more: [
        'From gene to protein: transcription (RNA polymerase copies the gene), processing (the introns are removed, the exons are spliced together) and translation on the ribosomes.',
        'In alternative splicing, a single gene gives rise to different proteins.',
        'The human genome has about 25,000 genes.',
      ],
      where: 'Large sphere inside the soma. The dark dots are the pores.',
    },
    're-rugoso': {
      name: 'Rough ER', aka: 'Nissl bodies',
      morf: 'Stacks of membrane studded with ribosomes, around the nucleus.',
      func: 'Makes the proteins destined for membranes (channels, pumps, receptors). They are inserted into the membrane as they are synthesized.',
      clue: 'It is abundant in the neuron because the neuron depends on many membrane proteins. It is what Nissl saw when he stained the tissue.',
      more: [
        'Neurons have more rough ER than glia and than most cells.',
        'It assembles the precursor of peptide neurotransmitters (ch. 5).',
        'The axon has no rough ER: that is why it depends on the soma.',
      ],
      where: 'Curved sheets next to the nucleus, dotted with ribosomes.',
    },
    ribossomos: {
      name: 'Free ribosomes', aka: 'In a group: polyribosome',
      morf: 'Loose grains in the cytosol. Several ribosomes reading the same mRNA form a polyribosome.',
      func: 'They make the proteins that stay in the cytosol.',
      clue: 'They also appear in the dendrites, beneath the spines.',
      more: [
        'In a polyribosome, each ribosome produces a copy of the same protein.',
        'At the base of the spines, synaptic activity can order protein to be made right there, something important for storing information (ch. 25).',
      ],
      where: 'Loose golden grains in the soma. The ones lined up in an arc are polyribosomes.',
    },
    're-liso': {
      name: 'Smooth ER',
      morf: 'Membrane without ribosomes.',
      func: 'Helps fold proteins and regulates internal concentrations, such as that of Ca²⁺.',
      more: [
        'In muscle, it is called the sarcoplasmic reticulum.',
        'It has Ca²⁺ channels that the second messenger IP3 opens, releasing calcium into the cytosol (ch. 6).',
      ],
      where: 'Network of smooth tubes, near the edge of the soma.',
    },
    golgi: {
      name: 'Golgi apparatus',
      morf: 'Stack of membrane disks.',
      func: 'Processes proteins after translation and sorts them for delivery to each part of the neuron, such as the axon or the dendrites.',
      clue: 'It is the shipping department of the factory.',
      more: ['It cleaves the precursor of peptide neurotransmitters. The secretory granule leaves it already full and travels down the axon (ch. 5).'],
      where: 'Stack of disks, on the side of the soma opposite the nucleus.',
    },
    mitocondria: {
      name: 'Mitochondrion',
      morf: 'Elongated organelle, with a folded inner membrane.',
      func: 'Cellular respiration: it produces ATP.',
      clue: 'ATP pays for the ion pumps and for transport in the axon. The axon terminal has many mitochondria: a sign of high energy use.',
      more: [
        'Pyruvic acid and oxygen go in. The Krebs cycle and the electron-transport chain turn ADP into ATP.',
        'The sodium-potassium pump consumes up to 70% of the ATP of the brain (ch. 3).',
        'The outer membrane holds MAO, an enzyme that destroys catecholamines and serotonin after reuptake (ch. 6).',
      ],
      where: 'Capsules in the soma (one is cut open, showing the folds) and inside the terminal, in the Synapse view.',
    },

    citosol: {
      name: 'Cytosol',
      rows: [['K⁺', '100 mM'], ['Na⁺', '15 mM'], ['Ca²⁺', '0.0002 mM'], ['Cl⁻', '13 mM']],
      morf: 'Salty solution that fills the inside of the neuron, from the soma to the neurites. It is rich in K⁺ and poor in Na⁺.',
      func: 'It is where the organelles sit and where electrical current flows inside the neuron, carried by ions.',
      clueTitle: 'Why it matters',
      clue: 'It is the inside of the battery. The pumps keep K⁺ high here and Na⁺ high outside; that difference is what the channels use to generate the resting potential and the action potential.',
      more: [
        'Everything inside the membrane, except the nucleus, makes up the cytoplasm: cytosol plus organelles.',
        'It conducts far worse than a copper wire: the charge is carried by ions, not by free electrons.',
        'It is electrically neutral. The negative charge at rest sits right against the inner face of the membrane.',
        'Ca²⁺ is kept extremely low by the calcium pump, by proteins that bind it and by organelles that sequester it.',
        'In the terminal, the small transmitters are made in the cytosol and then concentrated in the vesicles.',
        'Second messengers, such as cAMP, diffuse through it (ch. 6).',
      ],
      where: 'In the cut-open soma, it is all the space between the organelles. With Fluids on, it appears as the lilac volume inside the soma, the terminal and the axon.',
    },
    extracelular: {
      name: 'Extracellular fluid',
      rows: [['K⁺', '5 mM'], ['Na⁺', '150 mM'], ['Ca²⁺', '2 mM'], ['Cl⁻', '150 mM']],
      morf: 'Salty solution that bathes neurons and glia on the outside. It is rich in Na⁺ and Cl⁻ and poor in K⁺.',
      func: 'It is the outside of the battery. It is also what the neurotransmitter diffuses through in the synaptic cleft.',
      clueTitle: 'Why it matters',
      clue: 'The resting potential is very sensitive to the K⁺ here: raising it from 5 to 50 mM takes Vm from −65 to about −17 mV. That is why the astrocytes and the blood-brain barrier keep this K⁺ low.',
      more: [
        'The space is minimal: astrocytes fill the space between neurons, leaving gaps of about 20 nm. The scene spreads the cells apart so they can be seen.',
        'Because it also conducts electricity, the current traveling down the axon leaks into it: it is the leaky hose of chapter 3.',
        'The synaptic cleft is part of it, at 20 to 50 nm.',
        'Astrocytes take up K⁺ where there has been a lot of activity and spread it through their network of processes (spatial buffering).',
      ],
      where: 'All the space outside the cells. With Fluids on, the background turns bluish and the loose dots represent ions: orange for Na⁺, purple for K⁺.',
    },
    liquor: {
      name: 'Ventricular fluid',
      morf: 'Fluid that fills the ventricles, the cavities of the brain.',
      func: 'It fills the ventricles and is in contact with the ependymal cells that line them.',
      clueTitle: 'In history',
      clue: 'Galen found the ventricles full of fluid and concluded, wrongly, that sensation and movement were fluids moving to and fro through the nerves. The idea only fell when nerves were shown to conduct electricity.',
      more: [{ x: 'In anatomy it is called cerebrospinal fluid, or CSF. Its name and its function do not appear in chapters 1 to 6.' }],
      where: 'In the Tissue view, with Fluids on: the blue volume to the left of the wall of ependymal cells.',
    },
    sangue: {
      name: 'Blood',
      morf: 'Fluid that flows inside the capillaries.',
      func: 'Brings oxygen and nutrients to the nervous tissue.',
      clueTitle: 'Why it matters',
      clue: 'It does not mix freely with the extracellular fluid: the blood-brain barrier, in the capillary walls, limits the passage of K⁺.',
      more: [
        'Tryptophan, the raw material for serotonin, reaches the brain through the blood (ch. 6).',
        'Microglia may come from the blood.',
        'The heart has no such barrier: that is why potassium chloride in a vein is lethal.',
        { x: 'The liquid part of the blood is called plasma. The red cells drawn here are red blood cells (erythrocytes).' },
      ],
      where: 'In the Tissue view, with Fluids on: the yellowish fluid inside the capillary.',
    },

    membrana: {
      name: 'Neuronal membrane',
      morf: 'Phospholipid bilayer studded with proteins: some pump substances, others form pores. Its composition differs between soma, dendrites and axon.',
      func: 'Barrier to ions. Its proteins create the electrical signals of the neuron.',
      clue: 'The difference between axon and dendrite is, at the molecular level, a difference in membrane proteins.',
      more: [
        'Each phospholipid has a polar head, which likes water, and a tail that avoids it. In two layers, the tails hide in the middle.',
        'Ion channels: 4 to 6 subunits around a pore, with selectivity and, in many, a gate.',
        'Ion pumps: enzymes that use ATP to move ions against the gradient.',
        'The separated charge sits right against the two faces of the membrane (capacitance). The rest of the solutions is neutral.',
        'Adding up all the neurons gives about 21,000 m² of membrane.',
      ],
      where: 'In the Axon view: the two-layer wall, opened as a window. In the Impulse view: the bilayer with the channels.',
    },
    microtubulo: {
      name: 'Microtubule',
      morf: 'Hollow tube of tubulin, running along the neurites.',
      func: 'Track for axoplasmic transport: vesicles walk along it, spending ATP. Kinesin carries from the soma to the terminal; dynein brings back.',
      clue: 'The axon terminal has no microtubules.',
      more: [
        'Associated proteins (MAPs), such as tau, organize the microtubules. In Alzheimer\'s disease, tau detaches and accumulates in neurofibrillary tangles.',
        'Fast transport: up to 1,000 mm per day. Slow transport: 1 to 10 mm per day.',
        'The herpes and rabies viruses enter the nervous system by retrograde transport.',
      ],
      where: 'In the Axon view: the thickest hollow tubes.',
    },
    neurofilamento: {
      name: 'Neurofilament',
      morf: 'Subunits braided like a rope.',
      func: 'Mechanical strength. It is the strongest of the three and plays the role of bone.',
      more: ['It is an intermediate filament, a relative of the keratin of hair.'],
      where: 'In the Axon view: the braided ropes, of medium thickness.',
    },
    microfilamento: {
      name: 'Microfilament',
      morf: 'Two braided strands of actin, anchored to the membrane.',
      func: 'Changes the shape of the cell.',
      more: ['The cytoskeleton is assembled and disassembled all the time.', 'In muscle, actin takes part in contraction (ch. 13).'],
      where: 'In the Axon view: the thinnest threads, attached to the inside of the membrane.',
    },

    neuritos: {
      name: 'Neurites',
      morf: 'Thin processes that extend from the soma. There are two types: axon and dendrites.',
      func: 'General name. The dendrites are the signal input; the axon is the output.',
      more: ['By its number of neurites, a neuron is unipolar, bipolar or multipolar. Most in the brain are multipolar.'],
      where: 'Everything that extends from the soma. When you choose this item, dendrites and axon are highlighted together.',
    },
    dendritos: {
      name: 'Dendrites', aka: 'Dendritic tree', size: 'Rarely longer than 2 mm',
      morf: 'Several per neuron, short, branched, and tapering toward the tip.',
      func: 'Antennae: they receive thousands of synapses. The membrane beneath them has receptors that detect the neurotransmitters.',
      clue: 'An elaborate tree indicates a cell specialized in receiving many signals.',
      more: [
        'Here the signal is not regenerated: each EPSP is small and decays with distance. At one length constant (λ) from the synapse, 37% remains.',
        'The neuron adds up the EPSPs in space (several synapses at the same time) and in time (the same synapse in rapid succession).',
        'Most dendrites have voltage-gated Na⁺, Ca²⁺ and K⁺ channels, which amplify small, distant EPSPs.',
      ],
      where: 'The branches that extend from the soma in several directions.',
    },
    espinhos: {
      name: 'Dendritic spines',
      morf: 'Small sacs hanging from the dendrite.',
      func: 'They receive synapses and isolate the chemical reactions triggered by each one. They change shape with activity.',
      more: [
        'A synapse made on a spine is called axospinous.',
        'At the base there are polyribosomes: the synapse can order protein to be made on site.',
        'In children with intellectual disability, the spines are fewer, long and thin, resembling those of fetuses.',
      ],
      where: 'The little balls along the dendrites. In the Synapse view, the sac just below the cleft.',
    },

    cone: {
      name: 'Axon hillock', aka: 'Spike-initiation zone',
      morf: 'Region of the soma that tapers into the initial segment of the axon.',
      func: 'Spike-initiation zone: voltage-gated sodium channels are dense here, and this is where the action potential is born.',
      clue: 'This holds for the typical neuron of the brain and spinal cord. In a sensory neuron, the spike-initiation zone is near the sensory nerve ending.',
      more: [
        'The neuron fires when the sum of the EPSPs, minus the inhibition, reaches threshold here.',
        'The soma and dendrites generally do not fire Na⁺ action potentials, because they have few of these channels.',
      ],
      where: 'The funnel between the soma and the axon. The red dots mark Na⁺ channels.',
    },
    axonio: {
      name: 'Axon', size: '<1 mm to >1 m in length; <1 to ~25 µm in diameter',
      morf: 'One per neuron, with a uniform diameter and branches at right angles. It has no rough ER and almost no ribosomes.',
      func: 'Conducts the action potential away from the soma. The thicker it is, the faster.',
      clue: 'Without ribosomes, it makes no proteins: everything comes from the soma. Cut off from it, it degenerates (Wallerian degeneration).',
      more: [
        'The action potential is regenerated at each stretch and does not shrink along the way. It does not turn back because the stretch behind it is refractory.',
        'At about 10 m/s and lasting 2 ms, an action potential occupies some 2 cm of axon at a time.',
        'Enzymes and peptide granules travel down from the soma by axoplasmic transport.',
        'In the squid, the giant axon reaches 1 mm in diameter. It is the one Hodgkin and Huxley worked on.',
      ],
      where: 'The long wire that leaves the hillock. It is bare at the start, at the nodes and at the end.',
    },
    colaterais: {
      name: 'Axon collaterals',
      morf: 'Branches of the axon, which leave at right angles. Those that return to the cell itself or to neighboring cells are recurrent collaterals.',
      func: 'They carry the same signal to other targets.',
      where: 'The branch that leaves the axon at a node.',
    },
    mielina: {
      name: 'Myelin sheath',
      morf: 'Glial membrane wrapped in a spiral around the axon, interrupted at intervals.',
      func: 'Insulates the axon: less current leaks across the membrane, and conduction speeds up.',
      clue: 'It is not part of the neuron. It is membrane from an oligodendrocyte (in the central nervous system) or from a Schwann cell (in the peripheral one).',
      more: [
        'In multiple sclerosis, the myelin of the central nervous system is attacked, and conduction becomes slow or fails.',
        'In Guillain-Barré syndrome, the attack is on the myelin of the peripheral nerves.',
      ],
      where: 'The pale sleeves around the axon. In the Axon view, the cut shows the spiral.',
    },
    nodulo: {
      name: 'Node of Ranvier', size: '0.2 to 2 mm',
      morf: 'Gap without myelin, where the axon membrane is exposed and the Na⁺ channels are concentrated.',
      func: 'Regenerates the action potential, which jumps from node to node (saltatory conduction).',
      more: ['The thicker the axon, the farther apart the nodes.'],
      where: 'The gaps between two myelin sleeves. The red dots mark Na⁺ channels.',
    },
    terminal: {
      name: 'Axon terminal', aka: 'Terminal bouton',
      morf: 'Swollen tip of the axon. It has no microtubules, is full of synaptic vesicles, has a dense coating of proteins on the face turned toward the synapse and has many mitochondria.',
      func: 'Converts the electrical signal into a chemical one: it releases neurotransmitter into the cleft.',
      more: [
        'The axon may end in several short branches (terminal arbor) or make synapses in passing (boutons en passant).',
        'The small transmitters (amino acids and amines) are made right here, in the cytosol, by enzymes that came from the soma.',
        'Membrane transporters take the transmitter back up from the cleft, using the Na⁺ gradient.',
        'Autoreceptors sense the released transmitter and put a brake on release, like a safety valve.',
      ],
      where: 'The boutons at the end of the axon. Seen from the inside in the Synapse view.',
    },

    sinapse: {
      name: 'Synapse', size: '20 to 50 nm',
      morf: 'It has a presynaptic side (usually the terminal), the synaptic cleft and a postsynaptic side (the dendrite or soma of another neuron), with receptors.',
      func: 'Point of contact where the signal passes from one cell to another: it arrives electrical, becomes chemical and turns electrical again on the other side.',
      clue: 'A Gray\'s type I synapse (asymmetrical, thicker postsynaptic side) is usually excitatory. Type II (symmetrical) is usually inhibitory.',
      more: [
        'In six steps: the action potential arrives; Ca²⁺ channels open; the vesicle fuses and releases the transmitter; it crosses the cleft; the receptor responds; the transmitter is removed.',
        'By the site of contact: axodendritic, axosomatic, axoaxonic or axospinous.',
        'Most synapses in the mature nervous system are chemical. There are also electrical synapses (gap junctions, at 3 nm), bidirectional and nearly instantaneous.',
        'A typical synapse in the central nervous system generates an EPSP of a few tenths of a mV. On its own, it does not make the neuron fire.',
      ],
      where: 'Where a terminal bouton touches the dendrite of the next neuron. In detail in the Synapse view.',
    },
    vesiculas: {
      name: 'Synaptic vesicles',
      morf: 'Membrane spheres inside the terminal. The neurotransmitter is stored in their interior, the lumen.',
      func: 'They store the neurotransmitter and release it into the cleft by exocytosis: the vesicle membrane fuses with that of the terminal.',
      clue: 'Release is fast because the vesicles are already docked at the active zone, right where Ca²⁺ enters.',
      more: [
        'Transporters in the vesicle membrane concentrate the transmitter inside up to 100,000-fold, exchanging each molecule for one H⁺.',
        'The lumen is acidic: an ATP-driven H⁺ pump keeps it that way, and this H⁺ gradient is what the transporter uses.',
        'Each vesicle carries a few thousand transmitter molecules.',
        'SNARE proteins tie the vesicle to the terminal membrane. Synaptotagmin senses Ca²⁺ and triggers fusion.',
        'After exocytosis, the membrane is recovered by endocytosis, and the vesicle is refilled.',
        'They store amino acids and amines. Peptides are kept in the secretory granules.',
      ],
      where: 'In the Synapse view: the spheres inside the terminal. Two are cut open, showing the neurotransmitter in the lumen.',
    },
    neurotransmissor: {
      name: 'Neurotransmitter',
      morf: 'Molecule stored in the lumen of the synaptic vesicles. There are three families: amino acids (glutamate, GABA, glycine), amines (acetylcholine, dopamine, norepinephrine, serotonin) and peptides.',
      func: 'Released into the cleft, it crosses to the postsynaptic membrane and binds to the receptors, like a key in a lock.',
      clue: 'The receptor, not the transmitter, decides the effect: the same acetylcholine contracts skeletal muscle and slows the heart.',
      more: [
        'It leaves the cleft by diffusion, by reuptake (transporters in the terminal and in glia) or by enzymatic degradation, as with acetylcholine by acetylcholinesterase.',
        'Glutamate is the main excitatory transmitter in the brain; GABA, the main inhibitory one.',
        'Inside a cholinergic vesicle, acetylcholine can reach 1,000 mM.',
        'To be called a neurotransmitter, a molecule must be synthesized and stored in the presynaptic neuron, be released when that neuron is stimulated and, when applied from outside, mimic the effect of the synapse.',
      ],
      where: 'In the Synapse view: the orange grains inside the cut-open vesicles and scattered in the cleft.',
    },
    granulos: {
      name: 'Secretory granules', aka: 'Large, dense-core vesicles',
      morf: 'Larger vesicles, which appear dark under the electron microscope.',
      func: 'They store the peptide neurotransmitters and release them by Ca²⁺-dependent exocytosis, outside the active zones.',
      clue: 'Because they sit far from the active zones, a single action potential is not enough: it takes a high-frequency train, which raises Ca²⁺ throughout the terminal.',
      more: ['They leave the Golgi apparatus, in the soma, already full and travel down the axon by axoplasmic transport.', 'Release is slow: 50 ms or more.'],
      where: 'In the Synapse view: the two larger, darker spheres, at the top of the terminal.',
    },
    'zona-ativa': {
      name: 'Active zone',
      morf: 'Accumulation of proteins on the face of the terminal turned toward the cleft, where the vesicles cluster.',
      func: 'It is the site where the neurotransmitter is released.',
      more: ['Larger synapses have more active zones. The neuromuscular junction has many.', 'On the other side of the cleft lies the postsynaptic density, with the receptors.'],
      where: 'In the Synapse view: the dark disk at the bottom of the terminal, with docked vesicles.',
    },
    'canal-ca': {
      name: 'Voltage-gated calcium channel',
      morf: 'Protein of the terminal membrane, at the active zones. It is a relative of the Na⁺ channel of the action potential, but lets Ca²⁺ through.',
      func: 'Opens when the action potential depolarizes the terminal. Ca²⁺ enters, and that rise is the signal for the vesicles to release the transmitter.',
      clue: 'The force pushing Ca²⁺ inward is enormous: at rest, there is only 0.0002 mM in the cytosol.',
      more: ['Next to the active zone, Ca²⁺ exceeds 0.01 mM when the channels open.', 'At a mammalian synapse, release can begin about 60 µs after calcium enters.'],
      where: 'In the Synapse view: the blue-green proteins on the lower edge of the terminal.',
    },
    fenda: {
      name: 'Synaptic cleft', size: '20 to 50 nm',
      morf: 'Space between the presynaptic and postsynaptic membranes, filled with a matrix of fibrous proteins that holds the two together.',
      func: 'The neurotransmitter diffuses across it to the receptors.',
      more: ['It is about 10 times wider than the gap at a gap junction (3 nm).', 'Surrounding astrocytes limit the diffusion of the transmitter and remove it from the cleft.'],
      where: 'In the Synapse view: the space between the terminal and the spine, with the neurotransmitter.',
    },
    receptores: {
      name: 'Receptors', aka: 'In the postsynaptic density',
      morf: 'Proteins of the postsynaptic membrane. There are two types: transmitter-gated ion channels (four or five subunits around a pore) and G-protein-coupled receptors.',
      func: 'They detect the neurotransmitter. The channel opens in microseconds and generates an EPSP (if Na⁺ enters) or an IPSP (if Cl⁻ enters). The G-protein-coupled receptor acts more slowly, for longer, and modulates.',
      clue: 'A channel opened by glutamate or acetylcholine pulls Vm close to 0 mV, above threshold: it excites. A Cl⁻ channel opened by GABA or glycine holds Vm near −65 mV: it inhibits.',
      more: [
        'Glutamate receptors: AMPA (fast EPSP) and NMDA (lets Ca²⁺ in and only conducts with glutamate and depolarization together, because Mg²⁺ plugs the pore at rest).',
        'The G-protein-coupled receptor crosses the membrane seven times. The G-protein opens a channel directly (shortcut pathway) or switches on a second messenger cascade.',
        'There are well over 100 receptors, and a single transmitter can activate several subtypes.',
      ],
      where: 'In the Synapse view: the blue channels on top of the spine, facing the cleft.',
    },

    'canal-na': {
      name: 'Voltage-gated sodium channel',
      morf: 'A single long polypeptide with 4 domains (I to IV), each with 6 alpha helices that cross the membrane (S1 to S6). The four domains come together around the pore.',
      func: 'Opens when the membrane depolarizes to threshold. Na⁺ enters and produces the rising phase. It stays open about 1 ms and inactivates.',
      clue: 'The S4 helix, with positive amino acids, is the voltage sensor. In inactivation, a globular part of the protein plugs the pore: this explains the brevity of the action potential and the absolute refractory period.',
      more: [
        'The selectivity filter makes the channel about 12 times more permeable to Na⁺ than to K⁺.',
        'It can only open again after Vm returns close to rest (deinactivation).',
        'Tetrodotoxin (TTX), from the puffer fish, plugs the pore from the outside. Lidocaine enters through the open gate and binds on the inside.',
        'It is dense at the axon hillock and at the nodes of Ranvier.',
      ],
      where: 'In the Impulse view: the orange channels. The little ball attached underneath is the part that plugs the pore in inactivation.',
    },
    'canal-k': {
      name: 'Voltage-gated potassium channel',
      morf: 'Four separate subunits around the pore (in the Na⁺ channel, it is a single polypeptide, with four domains).',
      func: 'It also opens with depolarization, but about 1 ms later. K⁺ leaves, and Vm becomes negative again: this is the falling phase.',
      clue: 'Because it opens with a delay, this conductance was called the delayed rectifier. While the channel stays open, Vm goes past rest and approaches EK: this is the undershoot (after-hyperpolarization).',
      more: ['In each subunit, a pore loop forms the selectivity filter.', 'Slow K⁺ channels, which build up in the open state during the stimulus, make some neurons fire more and more slowly (adaptation).'],
      where: 'In the Impulse view: the purple channels.',
    },
    'canal-vaz': {
      name: 'Potassium channel open at rest',
      morf: 'K⁺ channel that is already open at rest, without depending on voltage.',
      func: 'Lets K⁺ leave down its gradient. Each K⁺ that leaves leaves a negative charge behind, and the interior becomes negative: this is the resting potential.',
      clue: 'At rest, the membrane is about 40 times more permeable to K⁺ than to Na⁺. A small Na⁺ leak keeps Vm from reaching EK (−80 mV) and leaves it at about −65 mV.',
      where: 'In the Impulse view: the lilac channel, through which K⁺ slowly leaves all the time.',
    },
    bomba: {
      name: 'Sodium-potassium pump',
      morf: 'Membrane enzyme.',
      func: 'Breaks down ATP and exchanges Na⁺ from inside for K⁺ from outside, against both gradients.',
      clue: 'It works all the time, like the pump that bails out of the boat the water from each wave. Without it there is no gradient; without a gradient, there is no resting potential and no action potential.',
      more: ['It consumes up to 70% of the ATP of the brain.', 'An action potential moves so few ions that the concentrations barely change.'],
      where: 'In the Impulse view: the green protein, larger than the channels.',
    },
    'ion-na': {
      name: 'Sodium (Na⁺)', size: '150 mM outside, 15 mM inside',
      morf: 'Cation ten times more concentrated outside the neuron.',
      func: 'When its channels open, it rushes in: diffusion and the negative interior push in the same direction. Vm races toward ENa (+62 mV).',
      more: ['In water, each ion is surrounded by a sphere of hydration.', 'Current of an ion = conductance × driving force (Vm − Eion).'],
      where: 'In the Impulse view: the orange spheres, almost all on the outside.',
    },
    'ion-k': {
      name: 'Potassium (K⁺)', size: '5 mM outside, 100 mM inside',
      morf: 'Cation twenty times more concentrated inside the neuron.',
      func: 'It leaves through the K⁺ channels and pulls Vm toward EK (−80 mV). It dominates the resting state and carries out repolarization.',
      more: ['Vm is very sensitive to the K⁺ outside: raising it from 5 to 50 mM takes the resting potential from −65 to about −17 mV.', 'Astrocytes and the blood-brain barrier keep the K⁺ outside low.'],
      where: 'In the Impulse view: the purple spheres, almost all on the inside.',
    },

    astrocito: {
      name: 'Astrocyte',
      morf: 'The most numerous glia. It has many processes, which fill the space between the neurons and envelop synapses.',
      func: 'Regulates the environment: it controls extracellular K⁺, limits the diffusion of the neurotransmitter and removes it from the cleft.',
      more: [
        'Potassium spatial buffering: it takes up K⁺ where there has been a lot of activity and spreads it through its network of processes (ch. 3).',
        'It has transporters that take up glutamate and GABA, and it does most of this work (ch. 5).',
        'It has receptors for neurotransmitters, which trigger electrical and chemical events in the astrocyte itself.',
        { x: 'In the Tissue view, some processes touch the capillary. This contact is not described in chapters 2 to 6.' },
      ],
      where: 'The star-shaped cell near the terminals, with a process at the synapse. Also in the Tissue and Glia views.',
    },
    oligodendrocito: {
      name: 'Oligodendrocyte',
      morf: 'Glia of the central nervous system. One cell extends arms and wraps several axons.',
      func: 'Forms the myelin sheath in the central nervous system.',
      where: 'The cell next to the axon, with arms reaching the myelin of this axon and that of a neighbor. Also in the Tissue and Glia views.',
    },
    schwann: {
      name: 'Schwann cell',
      morf: 'Glia of the peripheral nervous system. Each cell wraps a single axon.',
      func: 'Forms the myelin sheath in the peripheral nervous system.',
      where: 'In the Glia view: each sleeve is one cell, with its nucleus, around a single axon.',
    },
    microglia: {
      name: 'Microglia',
      morf: 'Small cell.',
      func: 'Phagocytoses the debris of dead cells and appears to remodel synapses, eliminating some.',
      more: ['It may come from the blood.', { x: 'The thin, branched processes in the drawing are the usual shape of microglia; the book does not describe it in these chapters.' }],
      where: 'The small, branched cell near the soma. Also in the Tissue and Glia views.',
    },
    ependimaria: {
      name: 'Ependymal cells',
      morf: 'Cells that form the layer lining the ventricles.',
      func: 'They line the ventricles and guide cell migration during development.',
      more: ['The ventricles are fluid-filled cavities of the brain (ch. 1).'],
      where: 'In the Tissue view: the wall of cells on the left. In the Glia view: the row of cells side by side.',
    },
    capilar: {
      name: 'Capillary', aka: 'Blood vessel',
      morf: 'Thin vessel that runs through the nervous tissue.',
      func: 'Carries oxygen and nutrients to the tissue.',
      clue: 'The walls of the brain capillaries hold the blood-brain barrier, which limits the passage of K⁺ from the blood into the tissue.',
      more: [{ x: 'The red cells drawn inside the vessel are red blood cells (erythrocytes).' }],
      where: 'In the Tissue view: the pinkish tube that crosses the scene, with astrocyte processes touching it.',
    },
  },
};
