// Fichas: organização geral, superfície do cérebro e áreas do córtex.
// Fonte: Bear, Connors e Paradiso, Neurociências, 4ª ed., cap. 7 e apêndice. Em "more", { x: '...' } é detalhe de fora
// do capítulo e aparece marcado como "extra". "sub" é a subvista em que a ficha mora ("ver de perto").
const M = 'malha anatômica', E = 'desenho esquemático', R = 'região aproximada sobre a malha', C = 'conceito, sem peça própria';

export default [
  /* ===================== organização geral ===================== */
  {
    id: 'encefalo', g: 'div', name: 'Encéfalo', color: '#E2B5A7', sub: 'lateral',
    rows: [['No modelo', M], ['Peso', 'cerca de 1,4 kg']],
    morf: 'Parte do sistema nervoso central que fica inteira dentro do crânio. Tem três partes comuns a todos os mamíferos: cérebro, cerebelo e tronco encefálico.',
    func: 'Com a medula espinhal, forma o sistema nervoso central. Nas palavras do livro, é o sistema nervoso que vê, ouve, sente, se move, lembra e sonha.',
    clueTitle: 'A ideia do capítulo',
    clue: 'O encéfalo humano é uma variação do plano comum a todos os mamíferos. Ele parece complicado porque algumas partes cresceram demais dentro dos limites do crânio e deformaram o conjunto.',
    more: [
      'Quase todas as estruturas são pares: uma do lado direito, outra do esquerdo. O livro chama isso de simetria bilateral.',
      'Recém-removido do crânio, o encéfalo é úmido e esponjoso.',
      { x: 'Neste modelo, o lado direito é o espelho do esquerdo. Nas malhas originais os dois lados já são quase iguais.' },
    ],
    where: 'É o modelo inteiro do Atlas. Gire para ver de cima, de baixo e de lado.',
    rel: ['cerebro', 'cerebelo', 'tronco-encefalico', 'medula-espinhal'],
  },
  {
    id: 'cerebro', g: 'div', name: 'Cérebro', aka: 'os dois hemisférios cerebrais', color: '#DFAE9F', sub: 'lateral',
    rows: [['No modelo', M], ['Origem', 'telencéfalo']],
    morf: 'A parte maior e mais rostral do encéfalo. Divide-se em dois hemisférios cerebrais, separados pela fissura cerebral longitudinal. A superfície é toda dobrada em giros e sulcos.',
    func: 'Com o diencéfalo, forma o prosencéfalo, o local das percepções, da consciência, da cognição e da ação voluntária. Em geral, o hemisfério direito recebe as sensações e controla os movimentos do lado esquerdo do corpo, e o esquerdo cuida do lado direito.',
    clueTitle: 'Corno de carneiro',
    clue: 'No ser humano, os hemisférios cresceram para trás, para baixo e para a frente, em arco. Visto de lado, o cérebro lembra um corno de carneiro que sai do tronco encefálico. A ponta do corno é o lobo temporal.',
    more: [
      'Por convenção, cada hemisfério é dividido em quatro lobos, com os nomes dos ossos do crânio que ficam por cima: frontal, parietal, temporal e occipital.',
      'Os dois hemisférios se comunicam pelos axônios do corpo caloso.',
    ],
    where: 'No Atlas, tudo o que fica rosado na vista Lateral e na Dorsal. Na vista Cerebelo ele é retirado, como na figura do livro.',
    rel: ['telencefalo', 'cortex-cerebral', 'lobo-frontal', 'lobo-parietal', 'lobo-temporal', 'lobo-occipital', 'corpo-caloso'],
  },
  {
    id: 'tronco-encefalico', g: 'div', name: 'Tronco encefálico', color: '#D9C3A5', sub: 'tronco',
    rows: [['No modelo', M], ['Partes', 'diencéfalo, mesencéfalo, ponte e bulbo']],
    morf: 'O talo do encéfalo: o pedúnculo de onde se destacam os hemisférios cerebrais e o cerebelo. O livro o descreve como formado por diencéfalo (tálamo e hipotálamo), mesencéfalo (teto e tegmento), ponte e bulbo.',
    func: 'Retransmite informação do cérebro para a medula espinhal e o cerebelo, e de volta. Também regula funções vitais, como a respiração, a consciência e a temperatura do corpo.',
    clueTitle: 'Primitivo e indispensável',
    clue: 'É considerado a parte mais primitiva do encéfalo dos mamíferos e também a mais importante para manter a vida. Dá para sobreviver a uma lesão do cérebro ou do cerebelo. Lesões do tronco encefálico costumam ser fatais.',
    more: [
      'O livro avisa que alguns anatomistas chamam de tronco encefálico só o mesencéfalo, a ponte e o bulbo, sem o diencéfalo.',
      'É do tronco encefálico que saem os nervos cranianos.',
    ],
    where: 'No Atlas, vista Tronco: o cérebro e o cerebelo são retirados e o tronco fica exposto por trás. Na vista Medial ele aparece cortado ao meio.',
    rel: ['diencefalo', 'mesencefalo', 'ponte', 'bulbo'],
  },
  {
    id: 'medula-espinhal', g: 'div', name: 'Medula espinhal', color: '#F0CF55', sub: 'coluna',
    rows: [['No modelo', E + ' (o conjunto de malhas só traz o canal central)'], ['Origem', 'tubo neural caudal']],
    morf: 'Fica dentro da coluna vertebral e é a continuação do tronco encefálico. Em corte, tem a substância cinzenta no centro, em forma de borboleta, e a substância branca em volta.',
    func: 'É o maior condutor de informação da pele, das articulações e dos músculos para o encéfalo, e de volta. Os neurônios da substância cinzenta também começam a análise da informação sensorial, coordenam movimentos e montam reflexos simples, como tirar o pé de cima de uma tachinha.',
    clueTitle: 'Se ela é cortada',
    clue: 'Uma transecção da medula causa anestesia da pele e paralisia dos músculos das partes do corpo caudais ao corte. Os músculos ainda funcionam. O que se perde é o controle deles pelo encéfalo.',
    more: [
      'Ela se comunica com o corpo pelos nervos espinhais. Cada nervo se liga à medula por uma raiz dorsal e uma raiz ventral.',
      'No adulto, o livro diz que ela termina no nível da terceira vértebra lombar.',
      { x: 'Outros textos de anatomia situam o fim da medula do adulto entre as vértebras L1 e L2.' },
    ],
    where: 'No módulo Medula. No Atlas aparece só o começo dela, o coto amarelo abaixo do bulbo.',
    rel: ['bulbo', 'canal-central', 'raiz-dorsal', 'raiz-ventral', 'coluna-vertebral'],
  },
  {
    id: 'snc', g: 'div', name: 'Sistema nervoso central', aka: 'SNC', color: '#C9A28F', kind: 'termo', sub: 'lateral',
    rows: [['No modelo', C]],
    morf: 'As partes do sistema nervoso envolvidas por osso: o encéfalo, dentro do crânio, e a medula espinhal, dentro da coluna vertebral.',
    func: 'Todo o resto é sistema nervoso periférico. O gânglio da raiz dorsal, por exemplo, fica fora da medula e pertence ao periférico.',
    more: [
      'A retina e o nervo óptico são partes do encéfalo, e não do sistema nervoso periférico.',
      'Todo o sistema nervoso central se desenvolve das paredes do tubo neural.',
    ],
    where: 'Encéfalo no Atlas e medula no módulo Medula.',
    rel: ['encefalo', 'medula-espinhal', 'snp', 'tubo-neural'],
  },
  {
    id: 'snp', g: 'div', name: 'Sistema nervoso periférico', aka: 'SNP: somático e visceral', color: '#E8C96A', kind: 'termo', sub: 'segmento',
    rows: [['No modelo', C], ['Volta em', 'cap. 15 (sistema nervoso visceral)']],
    morf: 'Tudo o que não está no encéfalo nem na medula espinhal. Tem duas partes: o SNP somático e o SNP visceral.',
    func: 'O somático reúne os nervos espinhais que inervam a pele, as articulações e os músculos de controle voluntário. O visceral inerva órgãos internos, vasos sanguíneos e glândulas.',
    more: [
      'Os axônios motores somáticos saem de neurônios motores da medula ventral. O corpo celular fica no sistema nervoso central; o axônio, quase todo, no periférico.',
      'Os axônios sensoriais somáticos entram pela raiz dorsal. Os corpos celulares deles ficam nos gânglios da raiz dorsal.',
      'Todos os neurônios com corpo celular no sistema nervoso periférico derivam da crista neural.',
    ],
    where: 'No módulo Medula, vista Segmento: raízes, gânglio e nervo espinhal.',
    rel: ['snv', 'nervo-espinhal', 'ganglio-da-raiz-dorsal', 'crista-neural', 'aferente-eferente'],
  },
  {
    id: 'snv', g: 'div', name: 'Sistema nervoso visceral', aka: 'SNV, involuntário, vegetativo ou autônomo', color: '#6FAFC9', kind: 'termo', sub: 'nervos',
    rows: [['No modelo', C + '; o livro o mostra no corpo inteiro'], ['Divisões', 'simpática, parassimpática e entérica'], ['Volta em', 'cap. 15']],
    morf: 'Neurônios que inervam órgãos internos, vasos sanguíneos e glândulas. A divisão simpática é uma cadeia de gânglios ao longo da coluna vertebral, ligados aos nervos espinhais, uns aos outros e a muitos órgãos. A parassimpática vem sobretudo do nervo vago, que sai do bulbo, e dos nervos espinhais sacrais.',
    func: 'Regula os órgãos de forma automática, sem controle direto da consciência. Os axônios sensoriais viscerais informam, por exemplo, a pressão e o oxigênio do sangue arterial. As fibras motoras viscerais comandam o músculo liso do intestino e dos vasos, a frequência do coração e a secreção das glândulas.',
    clueTitle: 'Quem manda nele',
    clue: 'O hipotálamo controla o sistema nervoso visceral. Em uma ameaça, ele orquestra a resposta de luta ou fuga. Depois de uma refeição farta, aumenta a peristalse e manda sangue para o sistema digestório.',
    more: ['Frio no estômago e rubor da face são reações mediadas pelo sistema nervoso visceral.'],
    where: 'Não há um desenho do corpo neste modelo. Veja o nervo vago em Em volta › Nervos e o hipotálamo no Atlas, vista Medial.',
    rel: ['nc-vago', 'hipotalamo', 'snp'],
  },

  /* ===================== superfície do cérebro ===================== */
  {
    id: 'cortex-cerebral', g: 'sup', name: 'Córtex cerebral', aka: 'no ser humano, quase todo ele é neocórtex', color: '#D9A79A', sub: 'lateral',
    rows: [['No modelo', M], ['Área', 'cerca de 1.100 cm² no adulto'], ['Volta em', 'caps. 8 a 14 e 18 a 25']],
    morf: 'Camada fina de neurônios logo abaixo da superfície do cérebro. Os corpos celulares ficam arranjados em camadas paralelas à superfície. A camada mais externa quase não tem corpos celulares: é a camada molecular, ou camada I. Pelo menos uma camada tem células piramidais, que mandam um dendrito apical até a camada I.',
    func: 'Todos os sistemas que tratam das sensações, das percepções, do movimento voluntário, do aprendizado, da linguagem e da cognição convergem para ele. Sem o córtex cerebral, uma pessoa seria cega, surda, muda e incapaz de iniciar um movimento voluntário.',
    clueTitle: 'Por que ele é dobrado',
    clue: 'Para caber no crânio. A área do córtex cresceu muito na evolução humana, e ele precisou dobrar-se e enrugar-se. As saliências são os giros; as reentrâncias, os sulcos ou, quando muito profundas, as fissuras.',
    more: [
      'Há três tipos de córtex. O hipocampo tem três camadas celulares. O córtex olfatório tem duas ou três. O neocórtex tem muitas e só existe nos mamíferos.',
      'Quando se diz só "córtex", quase sempre é o neocórtex.',
      'Entre camundongo, macaco e ser humano, a área do córtex varia na proporção de 1 para 100 para 1.000. A espessura varia no máximo duas vezes. Mudou a quantidade de córtex, não a estrutura básica.',
      'A menor unidade funcional proposta é a coluna neocortical: um cilindro de 2 mm de altura e 0,5 mm de diâmetro, com cerca de 10 mil neurônios e 100 milhões de sinapses.',
      'O diagrama de como os neurônios se ligam entre si é o conectoma.',
      'O neocórtex tem áreas sensoriais primárias, que recebem primeiro as vias sensoriais; áreas sensoriais secundárias, muito ligadas às primárias; áreas motoras; e áreas de associação, a aquisição evolutiva mais recente.',
    ],
    where: 'No Atlas, é a casca de todo o cérebro. Nos Cortes, é a faixa mais escura junto à superfície, por fora da substância branca.',
    rel: ['cerebro', 'substancia-branca', 'hipocampo', 'mapa-de-brodmann', 'talamo'],
  },
  {
    id: 'lobo-frontal', g: 'sup', name: 'Lobo frontal', color: '#6F9FE3', sub: 'lateral',
    rows: [['No modelo', M], ['Limite', 'sulco central, atrás'], ['Volta em', 'caps. 14, 18, 21 e 24']],
    morf: 'A parte anterior do cérebro, sob o osso frontal. O sulco central marca a borda posterior dele. O giro pré-central é a última dobra antes desse sulco.',
    func: 'Tem as principais áreas de controle motor, logo à frente do sulco central. O resto é em grande parte córtex pré-frontal, uma das áreas associativas mais importantes.',
    clueTitle: 'Por que importa',
    clue: 'O livro liga o surgimento da "mente", a capacidade de interpretar comportamentos em termos de desejos, intenções e crenças, à expansão do córtex frontal. Lesões do córtex frontal podem mudar profundamente a personalidade.',
    more: ['No corte coronal 1, a ínsula separa o lobo frontal do lobo temporal.'],
    where: 'Atlas, vista Lateral: a metade da frente do hemisfério. Fica azul quando escolhido e no modo de cores Lobos.',
    rel: ['giro-pre-central', 'sulco-central', 'cortex-pre-frontal', 'cortex-motor-primario', 'cranio'],
  },
  {
    id: 'lobo-parietal', g: 'sup', name: 'Lobo parietal', color: '#7CC47A', sub: 'lateral',
    rows: [['No modelo', M], ['Limite', 'sulco central, à frente'], ['Volta em', 'caps. 12, 21 e 24']],
    morf: 'Fica atrás do sulco central, sob o osso parietal. O giro pós-central é a primeira dobra dele.',
    func: 'Tem as áreas somatossensoriais, que tratam do tato. Mais atrás fica o córtex parietal posterior, uma área associativa.',
    more: [
      'A superfície inferior do lobo parietal, o opérculo, guarda com a ínsula o córtex gustatório.',
      'No corte coronal 2, mais posterior, a fissura lateral separa o lobo parietal do temporal.',
    ],
    where: 'Atlas, vista Lateral: o alto do hemisfério, atrás do sulco central. Fica verde quando escolhido e no modo Lobos.',
    rel: ['giro-pos-central', 'sulco-central', 'cortex-somatossensorial', 'cortex-parietal-posterior', 'cranio'],
  },
  {
    id: 'lobo-temporal', g: 'sup', name: 'Lobo temporal', color: '#EDB98A', sub: 'lateral',
    rows: [['No modelo', M], ['Limite', 'fissura lateral, acima'], ['Volta em', 'caps. 11, 24 e 25']],
    morf: 'A ponta do "corno de carneiro" do cérebro, logo abaixo do osso temporal, na têmpora. Fica ventral à fissura lateral.',
    func: 'Tem as áreas auditivas. A parte de baixo é o córtex temporal inferior, uma área associativa. Por dentro dele ficam o hipocampo e a amígdala.',
    more: ['O crescimento dos lobos temporais é o que mais distorce o sistema ventricular humano em relação ao plano básico dos mamíferos.'],
    where: 'Atlas, vista Lateral: a parte de baixo do hemisfério, sob a fissura lateral. Fica cor de pêssego quando escolhido e no modo Lobos.',
    rel: ['giro-temporal-superior', 'fissura-lateral', 'cortex-auditivo', 'cortex-temporal-inferior', 'hipocampo', 'amigdala'],
  },
  {
    id: 'lobo-occipital', g: 'sup', name: 'Lobo occipital', color: '#E3736F', sub: 'lateral',
    rows: [['No modelo', M], ['Volta em', 'cap. 10']],
    morf: 'A região mais posterior do cérebro, sob o osso occipital. É limitado pelos lobos parietal e temporal.',
    func: 'Tem as áreas visuais. A área 17, no extremo posterior, é o córtex visual primário.',
    more: ['Sem a área 17, o ser humano fica cego.', 'A artéria cerebral posterior irriga a parede medial do lobo occipital.'],
    where: 'Atlas, vista Lateral: o fundo do hemisfério, acima do cerebelo. Fica vermelho quando escolhido e no modo Lobos.',
    rel: ['cortex-visual', 'fissura-calcarina', 'lobo-parietal', 'lobo-temporal'],
  },
  {
    id: 'insula', g: 'sup', name: 'Ínsula', color: '#A8CF8F', sub: 'lateral',
    rows: [['No modelo', M], ['Volta em', 'cap. 8']],
    morf: 'Porção de córtex cerebral escondida no fundo da fissura lateral. O nome vem do latim para "ilha". Só aparece quando se afastam as margens da fissura.',
    func: 'Limita e separa os lobos temporal e frontal. Com o opérculo do lobo parietal, guarda o córtex gustatório.',
    where: 'Escolha a ínsula na lista: os giros que a cobrem viram contorno e ela aparece em verde-claro, na vista Lateral. Nos Cortes 1 e 2 ela está na base da fissura lateral.',
    rel: ['fissura-lateral', 'cortex-gustatorio', 'lobo-frontal', 'lobo-temporal'],
  },
  {
    id: 'giro-pre-central', g: 'sup', name: 'Giro pré-central', color: '#9B7FD1', sub: 'lateral',
    rows: [['No modelo', M], ['Lobo', 'frontal'], ['Volta em', 'cap. 14']],
    morf: 'A dobra do córtex imediatamente anterior ao sulco central.',
    func: 'Os neurônios dele controlam os movimentos voluntários. É onde fica o córtex motor primário, a área 4.',
    more: ['Os núcleos ventral lateral e ventral anterior do tálamo projetam para o córtex motor do giro pré-central.'],
    where: 'Atlas, vista Lateral: a faixa que desce do alto do hemisfério até a fissura lateral, logo à frente do sulco central. Fica roxa quando escolhida.',
    rel: ['sulco-central', 'giro-pos-central', 'cortex-motor-primario', 'nucleo-ventral-lateral', 'lobo-frontal'],
  },
  {
    id: 'giro-pos-central', g: 'sup', name: 'Giro pós-central', color: '#E8D35B', sub: 'lateral',
    rows: [['No modelo', M], ['Lobo', 'parietal'], ['Volta em', 'cap. 12']],
    morf: 'A dobra do córtex imediatamente posterior ao sulco central.',
    func: 'Os neurônios dele tratam da sensação somática, o tato. É onde fica o córtex somatossensorial, áreas 3, 1 e 2.',
    more: ['Recebe a projeção do núcleo ventral posterior do tálamo.'],
    where: 'Atlas, vista Lateral: a faixa paralela ao giro pré-central, logo atrás do sulco central. Fica amarela quando escolhida.',
    rel: ['sulco-central', 'giro-pre-central', 'cortex-somatossensorial', 'nucleo-ventral-posterior', 'lobo-parietal'],
  },
  {
    id: 'giro-temporal-superior', g: 'sup', name: 'Giro temporal superior', color: '#EE8FB0', sub: 'lateral',
    rows: [['No modelo', M], ['Lobo', 'temporal'], ['Volta em', 'cap. 11']],
    morf: 'A dobra mais alta do lobo temporal, logo abaixo da fissura lateral.',
    func: 'Os neurônios dele estão envolvidos na audição.',
    where: 'Atlas, vista Lateral: a faixa comprida que margeia por baixo a fissura lateral. Fica rosa quando escolhida.',
    rel: ['fissura-lateral', 'cortex-auditivo', 'lobo-temporal', 'nucleo-geniculado-medial'],
  },
  {
    id: 'giro-do-cingulo', g: 'sup', name: 'Giro do cíngulo', color: '#7FA8E6', sub: 'medial',
    rows: [['No modelo', M]],
    morf: 'Giro da face medial do hemisfério. Acompanha em arco o corpo caloso, logo acima dele.',
    func: 'O capítulo 7 só o aponta na superfície medial; não descreve a função.',
    more: [{ x: 'Faz parte do lobo límbico e do circuito de Papez, ligados à emoção, que o livro apresenta no capítulo 18.' }],
    where: 'Atlas, vista Medial: a faixa em arco logo acima do corpo caloso. Fica azul-clara quando escolhida.',
    rel: ['corpo-caloso', 'fornice'],
  },
  {
    id: 'sulco-central', g: 'sup', name: 'Sulco central', color: '#5B5F97', sub: 'lateral',
    rows: [['No modelo', 'linha traçada sobre a malha']],
    morf: 'Sulco profundo que desce pela face lateral do hemisfério. Separa o lobo frontal do lobo parietal.',
    func: 'É o marco de referência mais usado no córtex. Na frente dele fica o giro pré-central, motor. Atrás, o giro pós-central, do tato.',
    where: 'Atlas, vistas Lateral e Dorsal: o vão entre o giro pré-central e o pós-central. Ao escolher, uma linha escura percorre o sulco.',
    rel: ['giro-pre-central', 'giro-pos-central', 'lobo-frontal', 'lobo-parietal'],
  },
  {
    id: 'fissura-lateral', g: 'sup', name: 'Fissura lateral', aka: 'de Sylvius', color: '#4E7C8A', sub: 'lateral',
    rows: [['No modelo', 'linha traçada sobre a malha']],
    morf: 'Reentrância profunda na face lateral do hemisfério. O lobo temporal fica ventral a ela.',
    func: 'Separa o lobo temporal dos lobos frontal e parietal. No fundo dela fica a ínsula.',
    more: ['Na frente, ela separa o lobo frontal do temporal (corte 1). Mais atrás, separa o parietal do temporal (corte 2).'],
    where: 'Atlas, vista Lateral: o vão acima do giro temporal superior. Ao escolher, uma linha escura percorre a fissura.',
    rel: ['insula', 'lobo-temporal', 'giro-temporal-superior'],
  },
  {
    id: 'fissura-longitudinal', g: 'sup', name: 'Fissura cerebral longitudinal', aka: 'fissura sagital', color: '#6B6F7A', sub: 'dorsal',
    rows: [['No modelo', 'linha traçada sobre a malha']],
    morf: 'A fenda profunda, no plano mediano, que separa os dois hemisférios cerebrais.',
    func: 'É a linha média do cérebro vista de cima. No fundo dela, o corpo caloso liga os dois hemisférios.',
    where: 'Atlas, vista Dorsal: o vão entre os dois hemisférios. Ao escolher, uma linha escura percorre a fissura.',
    rel: ['cerebro', 'corpo-caloso', 'linha-media'],
  },
  {
    id: 'fissura-calcarina', g: 'sup', name: 'Fissura calcarina', color: '#8A5A6B', sub: 'medial',
    rows: [['No modelo', 'linha traçada sobre a malha, posição aproximada']],
    morf: 'Sulco profundo da face medial do lobo occipital.',
    func: 'O capítulo 7 só a aponta na superfície medial; não descreve a função.',
    more: [{ x: 'O córtex visual primário (área 17) fica nas bordas dela. O livro trata disso no capítulo 10.' }],
    where: 'Atlas, vista Medial: no lobo occipital, atrás do corpo caloso. Ao escolher, uma linha escura marca o sulco.',
    rel: ['lobo-occipital', 'cortex-visual'],
  },
  {
    id: 'bulbo-olfatorio', g: 'sup', name: 'Bulbo olfatório', color: '#E8C547', sub: 'ventral',
    rows: [['No modelo', E], ['Origem', 'telencéfalo'], ['Volta em', 'cap. 8']],
    morf: 'Pequena estrutura par na superfície ventral do lobo frontal. Nasce de um par de vesículas que brota da face ventral dos hemisférios. No ser humano é minúsculo, se comparado ao do rato.',
    func: 'Os neurônios dele recebem informação das células que percebem odores na cavidade nasal e a enviam a uma parte do córtex cerebral.',
    more: ['O primeiro nervo craniano, o olfatório, é na verdade parte do sistema nervoso central.', 'O córtex olfatório, de duas ou três camadas, é contínuo com o bulbo olfatório.'],
    where: 'Atlas, vista Ventral: o par de hastes claras sob o lobo frontal, ao lado da linha média, com a ponta alargada na frente.',
    rel: ['nc-olfatorio', 'cortex-cerebral', 'lobo-frontal'],
  },

  /* ===================== áreas do córtex ===================== */
  {
    id: 'mapa-de-brodmann', g: 'areas', name: 'Mapa de Brodmann', aka: 'mapa citoarquitetônico do neocórtex', color: '#B9A58F', kind: 'termo', sub: 'lateral',
    rows: [['No modelo', C]],
    morf: 'No início do século XX, Korbinian Brodmann dividiu o neocórtex em áreas pela citoarquitetura, isto é, pelo arranjo das células ao microscópio. Cada área com a mesma citoarquitetura recebeu um número.',
    func: 'Brodmann supunha, sem poder demonstrar, que áreas diferentes fazem coisas diferentes. Hoje há evidência de que é assim: a área 17 é córtex visual, a área 4 é córtex motor. O que define a função de cada área são as conexões dela.',
    more: [
      'Acredita-se que o ancestral comum dos mamíferos tivesse cerca de 20 áreas. O que cresceu na evolução foi a região entre as áreas primárias.',
      { x: 'Neste modelo não há uma malha por área. As áreas são aproximadas por giros inteiros ou por faixas deles.' },
    ],
    where: 'Atlas, modo de cores Áreas: motoras em vermelho, sensoriais em verde e associativas em roxo, como na figura do livro.',
    rel: ['cortex-cerebral', 'cortex-motor-primario', 'cortex-visual'],
  },
  {
    id: 'cortex-motor-primario', g: 'areas', name: 'Córtex motor primário', aka: 'área 4, ou M1', color: '#DD5C74', sub: 'lateral',
    rows: [['No modelo', R], ['Onde', 'giro pré-central'], ['Volta em', 'cap. 14']],
    morf: 'A área 4 de Brodmann, anterior ao sulco central, no lobo frontal.',
    func: 'Os neurônios dela mandam axônios direto aos neurônios motores do corno ventral da medula espinhal, que fazem os músculos contrair. Por isso é chamada de córtex motor primário.',
    more: ['Esses axônios formam o tracto corticospinal, que cruza de lado no bulbo.', 'As áreas motoras recebem dos núcleos do tálamo informação retransmitida do telencéfalo basal e do cerebelo.'],
    where: 'Atlas, modo Áreas: o giro pré-central inteiro, em vermelho.',
    rel: ['giro-pre-central', 'area-pre-motora', 'area-motora-suplementar', 'tracto-corticospinal', 'nucleo-ventral-lateral'],
  },
  {
    id: 'area-motora-suplementar', g: 'areas', name: 'Área motora suplementar', aka: 'parte da área 6', color: '#E98A9B', sub: 'lateral',
    rows: [['No modelo', R], ['Onde', 'à frente da área 4, no alto do hemisfério'], ['Volta em', 'cap. 14']],
    morf: 'A parte de cima da área 6, logo à frente do córtex motor primário.',
    func: 'É uma das áreas de controle motor do lobo frontal. O capítulo 7 só a localiza; o controle do movimento é assunto do capítulo 14.',
    where: 'Atlas, modo Áreas: a faixa rosada à frente do giro pré-central, na parte alta.',
    rel: ['area-pre-motora', 'cortex-motor-primario', 'lobo-frontal'],
  },
  {
    id: 'area-pre-motora', g: 'areas', name: 'Área pré-motora', aka: 'parte da área 6', color: '#F2A9A0', sub: 'lateral',
    rows: [['No modelo', R], ['Onde', 'à frente da área 4, na face lateral'], ['Volta em', 'cap. 14']],
    morf: 'A parte lateral da área 6, à frente do córtex motor primário.',
    func: 'É uma das áreas de controle motor do lobo frontal. O capítulo 7 só a localiza; o controle do movimento é assunto do capítulo 14.',
    where: 'Atlas, modo Áreas: a faixa salmão à frente do giro pré-central, na face lateral.',
    rel: ['area-motora-suplementar', 'cortex-motor-primario', 'lobo-frontal'],
  },
  {
    id: 'cortex-somatossensorial', g: 'areas', name: 'Córtex somatossensorial', aka: 'áreas 3, 1 e 2', color: '#7CC45E', sub: 'lateral',
    rows: [['No modelo', R], ['Onde', 'giro pós-central'], ['Volta em', 'cap. 12']],
    morf: 'As áreas 3, 1 e 2 de Brodmann, logo atrás do sulco central, no lobo parietal.',
    func: 'Trata da sensação somática, o tato. É uma área sensorial.',
    more: ['A informação do tato chega pelo núcleo ventral posterior do tálamo.'],
    where: 'Atlas, modo Áreas: o giro pós-central inteiro, em verde.',
    rel: ['giro-pos-central', 'nucleo-ventral-posterior', 'lemnisco-medial', 'cortex-parietal-posterior'],
  },
  {
    id: 'cortex-parietal-posterior', g: 'areas', name: 'Córtex parietal posterior', aka: 'áreas 5 e 7', color: '#9C86CF', sub: 'lateral',
    rows: [['No modelo', R], ['Volta em', 'caps. 12, 21 e 24']],
    morf: 'As áreas 5 e 7 de Brodmann, no lobo parietal, atrás do córtex somatossensorial.',
    func: 'É uma das três áreas associativas que o livro destaca. As áreas associativas não são diretamente motoras nem sensoriais.',
    where: 'Atlas, modo Áreas: o alto do lobo parietal, em roxo.',
    rel: ['lobo-parietal', 'cortex-somatossensorial', 'cortex-pre-frontal', 'cortex-temporal-inferior'],
  },
  {
    id: 'cortex-visual', g: 'areas', name: 'Córtex visual', aka: 'áreas 17, 18 e 19', color: '#9BD07C', sub: 'lateral',
    rows: [['No modelo', R], ['Onde', 'lobo occipital'], ['Volta em', 'cap. 10']],
    morf: 'As áreas 17, 18 e 19 de Brodmann, no lobo occipital. A área 17 fica no extremo posterior.',
    func: 'A área 17 é o córtex visual primário, ou V1: recebe dos olhos por uma via direta, da retina ao tálamo e do tálamo ao córtex. Sem ela, o ser humano fica cego.',
    more: ['O núcleo geniculado lateral do tálamo é quem leva a informação ao córtex visual.', 'Em primatas que dependem da visão, como nós, estima-se que haja de 20 a 40 áreas visuais secundárias.'],
    where: 'Atlas, modo Áreas: o lobo occipital, em verde.',
    rel: ['lobo-occipital', 'nucleo-geniculado-lateral', 'fissura-calcarina'],
  },
  {
    id: 'cortex-auditivo', g: 'areas', name: 'Córtex auditivo', aka: 'áreas 41 e 42', color: '#62B37A', sub: 'lateral',
    rows: [['No modelo', R], ['Onde', 'giro temporal superior'], ['Volta em', 'cap. 11']],
    morf: 'As áreas 41 e 42 de Brodmann, no lobo temporal, junto à fissura lateral.',
    func: 'Trata da audição. Recebe a informação pelo núcleo geniculado medial do tálamo.',
    where: 'Atlas, modo Áreas: a parte de trás do giro temporal superior, em verde-escuro.',
    rel: ['giro-temporal-superior', 'nucleo-geniculado-medial', 'coliculo-inferior'],
  },
  {
    id: 'cortex-gustatorio', g: 'areas', name: 'Córtex gustatório', aka: 'área 43', color: '#A6D85F', sub: 'lateral',
    rows: [['No modelo', 'ponto marcado sobre a ínsula, posição aproximada'], ['Volta em', 'cap. 8']],
    morf: 'A área 43 de Brodmann. Fica na superfície inferior do lobo parietal, o opérculo, e na ínsula, escondida no fundo da fissura lateral.',
    func: 'É o córtex dedicado ao sentido da gustação.',
    where: 'Escolha na lista: os giros que cobrem a ínsula viram contorno e o ponto verde-limão aparece no alto dela.',
    rel: ['insula', 'lobo-parietal', 'nucleo-gustatorio'],
  },
  {
    id: 'cortex-pre-frontal', g: 'areas', name: 'Córtex pré-frontal', color: '#B49ADB', sub: 'lateral',
    rows: [['No modelo', R], ['Volta em', 'caps. 21 e 24']],
    morf: 'A grande região do lobo frontal à frente das áreas motoras.',
    func: 'É uma das três áreas associativas que o livro destaca. O córtex associativo é a aquisição evolutiva mais recente, marcante nos cérebros de primatas.',
    where: 'Atlas, modo Áreas: toda a frente do lobo frontal, em lilás.',
    rel: ['lobo-frontal', 'cortex-parietal-posterior', 'cortex-temporal-inferior', 'nucleo-pulvinar'],
  },
  {
    id: 'cortex-temporal-inferior', g: 'areas', name: 'Córtex temporal inferior', aka: 'áreas 20, 21 e 37', color: '#C6A9E0', sub: 'lateral',
    rows: [['No modelo', R], ['Volta em', 'caps. 24 e 25']],
    morf: 'As áreas 20, 21 e 37 de Brodmann, na parte de baixo do lobo temporal.',
    func: 'É uma das três áreas associativas que o livro destaca.',
    more: ['A artéria cerebral posterior irriga a parte inferior do lobo temporal.'],
    where: 'Atlas, modo Áreas: a parte de baixo do lobo temporal, em lilás-claro.',
    rel: ['lobo-temporal', 'cortex-pre-frontal', 'cortex-parietal-posterior'],
  },
];
