// Fichas: dentro do telencéfalo e o diencéfalo. Fonte: cap. 7 e apêndice (ver 01-geral.pt.js).
const M = 'malha anatômica', E = 'desenho esquemático, posição aproximada';

export default [
  /* ===================== dentro do telencéfalo ===================== */
  {
    id: 'substancia-branca', g: 'tel', name: 'Substância branca cortical', color: '#EADFC6', sub: 'c1',
    rows: [['No modelo', M]],
    morf: 'Os axônios que ficam por baixo do córtex cerebral. Em um encéfalo fresco cortado, os feixes de axônios aparecem em branco.',
    func: 'Contém todos os axônios que se projetam dos neurônios do córtex ou para eles. É contínua com o corpo caloso e com a cápsula interna.',
    clueTitle: 'Cinza por fora, branco por dentro',
    clue: 'No prosencéfalo, a substância cinzenta envolve a branca. Na medula espinhal é o contrário: o cinza fica no centro.',
    where: 'Nos Cortes 1 a 3: a região clara por dentro da faixa do córtex. No Atlas ela fica escondida sob o córtex.',
    rel: ['cortex-cerebral', 'corpo-caloso', 'capsula-interna', 'voc-substancia-branca'],
  },
  {
    id: 'corpo-caloso', g: 'tel', name: 'Corpo caloso', color: '#E7A5CC', sub: 'medial',
    rows: [['No modelo', M], ['Volta em', 'cap. 20']],
    morf: 'Um feixe imenso de axônios que liga os dois hemisférios. No plano mediano aparece cortado, em arco, no centro do cérebro. É contínuo com a substância branca cortical.',
    func: 'É uma comissura: uma ponte de axônios que conecta os neurônios corticais de um hemisfério aos do outro. É por ela que um lado fica sabendo o que o outro está fazendo.',
    clueTitle: 'Por que importa',
    clue: 'A contribuição de cada hemisfério pode ser estudada em pacientes em que o corpo caloso foi cortado.',
    more: ['Visto de cima, ele aparece quando os hemisférios são levemente afastados.', 'O livro usa o corpo caloso como ponto de referência nas secções.'],
    where: 'Atlas, vista Medial: o arco claro no centro do cérebro. Fica rosa quando escolhido.',
    rel: ['substancia-branca', 'fissura-longitudinal', 'fornice', 'voc-comissura'],
  },
  {
    id: 'fornice', g: 'tel', name: 'Fórnice', color: '#B5D95A', sub: 'medial',
    rows: [['No modelo', M], ['Volta em', 'cap. 24']],
    morf: 'Feixe de fibras em arco, logo abaixo do corpo caloso. O nome vem do latim para "arco". Liga o hipocampo de cada lado ao hipotálamo.',
    func: 'Alguns axônios do fórnice participam da regulação do armazenamento da memória. Os corpos mamilares do hipotálamo são um alvo importante dele.',
    more: ['No corte coronal 1 ele aparece cortado, junto ao ventrículo lateral.', 'Os neurônios da área septal mandam axônios para o fórnice.'],
    where: 'Atlas, vista Medial: o arco fino sob o corpo caloso. Em Por dentro dá para seguir o arco inteiro, do hipocampo ao corpo mamilar. Fica verde-limão quando escolhido.',
    rel: ['hipocampo', 'corpo-mamilar', 'hipotalamo', 'area-septal'],
  },
  {
    id: 'septo-pelucido', g: 'tel', name: 'Septo pelúcido', color: '#D9C9B0', sub: 'medial',
    rows: [['No modelo', M], ['No livro', 'aparece desenhado, sem nome']],
    morf: 'Lâmina fina no plano mediano, entre o corpo caloso e o fórnice.',
    func: 'O capítulo 7 não o nomeia nem o descreve.',
    more: [{ x: 'Separa os dois ventrículos laterais. Entrou no modelo para a vista medial não ficar com um buraco onde o livro desenha essa lâmina.' }],
    where: 'Atlas, vista Medial: a lâmina clara entre o corpo caloso e o fórnice.',
    rel: ['corpo-caloso', 'fornice', 'ventriculo-lateral', 'area-septal'],
  },
  {
    id: 'area-septal', g: 'tel', name: 'Área septal', color: '#D7A24A', sub: 'c1',
    rows: [['No modelo', E], ['Volta em', 'cap. 24']],
    morf: 'Grupo de neurônios junto à linha média, abaixo do corpo caloso e perto do fórnice. O nome vem do latim saeptum, "divisória".',
    func: 'Os neurônios dela mandam axônios ao fórnice e estão envolvidos no armazenamento da memória.',
    where: 'Corte 1, camada de células e fibras: a pequena região ocre junto à linha média, sob o corpo caloso.',
    rel: ['fornice', 'hipocampo', 'septo-pelucido'],
  },
  {
    id: 'capsula-interna', g: 'tel', name: 'Cápsula interna', color: '#B8936A', sub: 'c1',
    rows: [['No modelo', M + ' (parte da frente) e desenho esquemático (parte de trás)']],
    morf: 'Grande agrupamento de axônios que passa entre o tálamo e o núcleo caudado, de um lado, e o putame e o globo pálido, do outro. É contínua com a substância branca cortical.',
    func: 'Conecta o córtex com estruturas mais caudais, como o tronco encefálico e, sobretudo, o tálamo. Os neurônios do tálamo mandam axônios ao córtex por ela, e o córtex manda axônios ao tronco encefálico por ela.',
    clueTitle: 'Lado oposto',
    clue: 'Como regra geral, os axônios de cada cápsula interna levam ao córtex informação do lado contralateral do corpo. Um percevejo no pé direito é sentido pelo córtex esquerdo, via tálamo esquerdo e cápsula interna esquerda.',
    more: ['Alguns axônios corticais descem por ela e seguem até a medula espinhal: é o tracto corticospinal.'],
    where: 'Cortes 1 e 2: a faixa castanha entre o tálamo e o putame.',
    rel: ['talamo', 'substancia-branca', 'tracto-corticospinal', 'voc-capsula'],
  },
  {
    id: 'telencefalo-basal', g: 'tel', name: 'Telencéfalo basal', aka: 'prosencéfalo basal', color: '#C9B458', sub: 'c1',
    rows: [['No modelo', 'conjunto das peças profundas do telencéfalo']],
    morf: 'A substância cinzenta profunda do telencéfalo, ventrolateral aos ventrículos laterais. Em corte, é a região heterogênea medial à ínsula e lateral ao tálamo. "Basal" quer dizer profundo.',
    func: 'É o segundo tipo de substância cinzenta do telencéfalo; o primeiro é o córtex. Reúne os núcleos da base, ligados ao movimento, e outras estruturas, como a amígdala.',
    more: ['A artéria cerebral média irriga também as estruturas profundas do prosencéfalo basal.'],
    where: 'Cortes 1 e 2: o conjunto de núcleos coloridos entre a ínsula e o tálamo. Ao escolher, todos acendem juntos.',
    rel: ['nucleos-da-base', 'amigdala', 'cortex-cerebral', 'art-cerebral-media'],
  },
  {
    id: 'nucleos-da-base', g: 'tel', name: 'Núcleos da base', aka: 'caudado, putame e globo pálido', color: '#8FBF9A', sub: 'dentro',
    rows: [['No modelo', M], ['Volta em', 'cap. 14']],
    morf: 'Três agrupamentos de neurônios do telencéfalo basal: o núcleo caudado, o putame e o globo pálido. Ficam profundamente no cérebro.',
    func: 'São uma região importante dos sistemas que controlam o movimento. O córtex também comanda o movimento falando com eles. As funções não são totalmente compreendidas, mas uma lesão ali atrapalha a capacidade de iniciar o movimento voluntário.',
    where: 'Atlas, vista Por dentro: o conjunto azul, verde e roxo ao lado do tálamo. Nos Cortes 1 e 2 aparecem em secção.',
    rel: ['nucleo-caudado', 'putame', 'globo-palido', 'telencefalo-basal', 'substancia-nigra', 'subtalamo'],
  },
  {
    id: 'nucleo-caudado', g: 'tel', name: 'Núcleo caudado', color: '#F08C5A', sub: 'dentro',
    rows: [['No modelo', M], ['Volta em', 'cap. 14']],
    morf: 'Um dos núcleos da base. Fica junto à parede do ventrículo lateral, do lado de dentro da cápsula interna.',
    func: 'Com o putame e o globo pálido, faz parte dos sistemas encefálicos que controlam o movimento.',
    where: 'Corte 1, camada de células e fibras: a região laranja junto ao ventrículo lateral. Em Por dentro, o arco laranja que acompanha o ventrículo.',
    rel: ['nucleos-da-base', 'putame', 'globo-palido', 'ventriculo-lateral', 'capsula-interna'],
  },
  {
    id: 'putame', g: 'tel', name: 'Putame', color: '#9ACD7B', sub: 'dentro',
    rows: [['No modelo', M], ['Volta em', 'cap. 14']],
    morf: 'Um dos núcleos da base. É o mais lateral dos três, do lado de fora da cápsula interna, perto da ínsula.',
    func: 'Com o núcleo caudado e o globo pálido, faz parte dos sistemas encefálicos que controlam o movimento.',
    where: 'Cortes 1 e 2: a região verde, lateral ao globo pálido. Em Por dentro, a peça verde por fora do tálamo.',
    rel: ['nucleos-da-base', 'nucleo-caudado', 'globo-palido', 'insula'],
  },
  {
    id: 'globo-palido', g: 'tel', name: 'Globo pálido', color: '#E2C04F', sub: 'dentro',
    rows: [['No modelo', M], ['Volta em', 'cap. 14']],
    morf: 'Um dos núcleos da base. Fica entre o putame e a cápsula interna.',
    func: 'Com o núcleo caudado e o putame, faz parte dos sistemas encefálicos que controlam o movimento.',
    where: 'Cortes 1 e 2: a região amarelo-ocre, medial ao putame. Em Por dentro, a peça amarelo-ocre encostada nele.',
    rel: ['nucleos-da-base', 'nucleo-caudado', 'putame', 'capsula-interna'],
  },
  {
    id: 'amigdala', g: 'tel', name: 'Amígdala', color: '#E36B6B', sub: 'dentro',
    rows: [['No modelo', M], ['Volta em', 'caps. 18 e 24']],
    morf: 'Estrutura do telencéfalo basal em forma de amêndoa, de onde vem o nome em latim. Fica sob o córtex do lobo temporal, à frente do hipocampo. Não se vê da superfície.',
    func: 'É importante para regular os estados emocionais: está envolvida com o medo e a emoção. Também participa da regulação da memória.',
    more: ['O hipotálamo, embora fique logo abaixo do tálamo, é funcionalmente mais ligado a estruturas telencefálicas como a amígdala.'],
    where: 'Atlas, vista Por dentro: a bolinha vermelha na ponta do lobo temporal, à frente do hipocampo. No Corte 2 ela aparece em secção.',
    rel: ['hipocampo', 'hipotalamo', 'telencefalo-basal', 'lobo-temporal'],
  },
  {
    id: 'hipocampo', g: 'tel', name: 'Hipocampo', color: '#5FB6D4', sub: 'dentro',
    rows: [['No modelo', M], ['Camadas', 'três'], ['Volta em', 'caps. 18, 24 e 25']],
    morf: 'Uma forma relativamente simples de córtex cerebral, dobrada sobre si mesma. Fica no lobo temporal, em volta do ventrículo lateral. O nome vem do grego para "cavalo-marinho". Apesar das dobras, tem só três camadas celulares.',
    func: 'Tem um papel importante no aprendizado e na memória. O livro também o trata como parte do sistema límbico.',
    more: ['O fórnice liga o hipocampo de cada lado ao hipotálamo.', 'Como a amígdala, ele não se vê da superfície: fica sob o córtex.'],
    where: 'Atlas, vista Por dentro: a peça azul alongada no lobo temporal, atrás da amígdala. No Corte 3 ela aparece em secção, junto ao ventrículo lateral.',
    rel: ['fornice', 'amigdala', 'cortex-cerebral', 'ventriculo-lateral', 'lobo-temporal'],
  },

  /* ===================== diencéfalo ===================== */
  {
    id: 'talamo', g: 'die', name: 'Tálamo', color: '#B77FD0', sub: 'medial',
    rows: [['No modelo', M], ['Origem', 'diencéfalo'], ['Referência', 'terceiro ventrículo']],
    morf: 'Massa par de substância cinzenta no centro do encéfalo, de cada lado do terceiro ventrículo. Em corte coronal tem formato de coração. O nome vem do grego para "câmara interior". Divide-se em núcleos.',
    func: 'É o portal para o córtex cerebral. Todas as vias sensoriais da visão, da audição e das sensações somáticas fazem sinapse no tálamo antes de chegar ao córtex. Cada núcleo projeta para uma área diferente do córtex.',
    clueTitle: 'Portal para o neocórtex',
    clue: 'Quando o livro diz portal para o córtex, quer dizer portal para o neocórtex, o córtex de muitas camadas que só os mamíferos têm.',
    more: [
      'Os axônios do tálamo sobem ao córtex pela cápsula interna.',
      'O tálamo também retransmite ao córtex motor informação do telencéfalo basal e do cerebelo.',
      'Do olfato, o livro diz que o bulbo olfatório envia a informação a uma parte do córtex cerebral.',
      { x: 'O olfato é o sentido que chega ao córtex sem passar antes pelo tálamo (capítulo 8).' },
    ],
    where: 'Atlas, vista Medial: a massa roxa no centro, sob o fórnice. Na vista Tronco, o par de ovos roxos no alto. Nos Cortes 2 e 3 aparece em secção.',
    rel: ['diencefalo', 'hipotalamo', 'terceiro-ventriculo', 'capsula-interna', 'nucleo-ventral-posterior', 'nucleo-ventral-lateral', 'nucleo-pulvinar', 'nucleo-geniculado-lateral', 'nucleo-geniculado-medial'],
  },
  {
    id: 'nucleo-ventral-posterior', g: 'die', name: 'Núcleo ventral posterior', aka: 'do tálamo', color: '#6A3FB8', sub: 'c2',
    rows: [['No modelo', E], ['Volta em', 'cap. 12']],
    morf: 'Um dos núcleos do tálamo. No corte 2 aparece na parte de baixo e de fora dele.',
    func: 'É parte do sistema somatossensorial. Projeta para o giro pós-central do córtex.',
    more: ['O lemnisco medial leva a informação somatossensorial do bulbo ao tálamo.', { x: 'No capítulo 12, o destino do lemnisco medial no tálamo é este núcleo.' }],
    where: 'Corte 2, camada de células e fibras: a região roxo-escura dentro do tálamo. Em Vias › Tato, é a parada no tálamo.',
    rel: ['talamo', 'giro-pos-central', 'lemnisco-medial', 'nucleo-ventral-lateral'],
  },
  {
    id: 'nucleo-ventral-lateral', g: 'die', name: 'Núcleo ventral lateral', aka: 'do tálamo', color: '#5C7FE0', sub: 'c2',
    rows: [['No modelo', E], ['Volta em', 'cap. 14']],
    morf: 'Um dos núcleos do tálamo. No corte 2 aparece logo acima do ventral posterior.',
    func: 'É parte do sistema motor. Com o núcleo ventral anterior, que o livro não desenha, projeta para o córtex motor do giro pré-central.',
    where: 'Corte 2, camada de células e fibras: a região azul dentro do tálamo, acima do ventral posterior.',
    rel: ['talamo', 'giro-pre-central', 'cortex-motor-primario', 'nucleo-ventral-posterior'],
  },
  {
    id: 'nucleo-pulvinar', g: 'die', name: 'Núcleo pulvinar', aka: 'do tálamo', color: '#D95BB0', sub: 'c3',
    rows: [['No modelo', E], ['Volta em', 'cap. 21']],
    morf: 'Núcleo da parte posterior do tálamo.',
    func: 'Está conectado com grande parte do córtex de associação e participa do controle da atenção.',
    where: 'Corte 3, camada de células e fibras: a região magenta que ocupa o tálamo nesse nível.',
    rel: ['talamo', 'cortex-pre-frontal', 'cortex-parietal-posterior', 'nucleo-geniculado-lateral'],
  },
  {
    id: 'nucleo-geniculado-lateral', g: 'die', name: 'Núcleo geniculado lateral', aka: 'do tálamo', color: '#F0627E', sub: 'dentro',
    rows: [['No modelo', M], ['Volta em', 'cap. 10']],
    morf: 'Pequeno núcleo do tálamo, na parte de trás e de baixo dele, onde o tracto óptico entra no tálamo.',
    func: 'Retransmite a informação do olho para o córtex visual. É o exemplo que o livro dá de "núcleo".',
    where: 'Atlas, vista Por dentro: o grão rosado no fim do tracto óptico. No Corte 3, a região rosada ao lado do hipocampo.',
    rel: ['tracto-optico', 'cortex-visual', 'talamo', 'nucleo-geniculado-medial', 'voc-nucleo'],
  },
  {
    id: 'nucleo-geniculado-medial', g: 'die', name: 'Núcleo geniculado medial', aka: 'do tálamo', color: '#F29A4A', sub: 'dentro',
    rows: [['No modelo', M], ['Volta em', 'cap. 11']],
    morf: 'Pequeno núcleo do tálamo, ao lado do geniculado lateral e mais perto da linha média.',
    func: 'Transmite a informação auditiva ao córtex auditivo.',
    where: 'Atlas, vista Por dentro: o grão alaranjado ao lado do geniculado lateral. No Corte 3, a região alaranjada junto ao mesencéfalo.',
    rel: ['coliculo-inferior', 'cortex-auditivo', 'talamo', 'nucleo-geniculado-lateral'],
  },
  {
    id: 'hipotalamo', g: 'die', name: 'Hipotálamo', color: '#4FBFB8', sub: 'medial',
    rows: [['No modelo', M], ['Origem', 'diencéfalo'], ['Volta em', 'caps. 15 a 17']],
    morf: 'Fica logo abaixo do tálamo, ventral a ele. Forma o assoalho do terceiro ventrículo.',
    func: 'É um centro de controle vital de muitas funções básicas do corpo. Controla o sistema nervoso visceral e, por conexões com a glândula hipófise, as respostas hormonais. Tem papel-chave na motivação para buscar comida, bebida e acasalamento.',
    clueTitle: 'Primitivo, não sem importância',
    clue: 'O hipotálamo executa muitas funções primitivas e mudou pouco na evolução dos mamíferos. Diante de uma ameaça, é ele que orquestra a resposta de luta ou fuga: coração mais rápido, mais sangue nos músculos, pelos eriçados.',
    more: ['Funcionalmente, é mais ligado a certas estruturas telencefálicas, como a amígdala, do que ao tálamo.', 'Os corpos mamilares são núcleos do hipotálamo.'],
    where: 'Atlas, vista Medial: a região verde-azulada abaixo do tálamo, atrás do quiasma óptico. Nos Cortes 1 e 2, na base, junto ao terceiro ventrículo.',
    rel: ['talamo', 'terceiro-ventriculo', 'hipofise', 'corpo-mamilar', 'amigdala', 'snv', 'diencefalo'],
  },
  {
    id: 'corpo-mamilar', g: 'die', name: 'Corpo mamilar', color: '#C8553D', sub: 'ventral',
    rows: [['No modelo', M], ['Volta em', 'cap. 24']],
    morf: 'Par de saliências arredondadas na superfície ventral do encéfalo, atrás do quiasma óptico. São núcleos do hipotálamo.',
    func: 'Fazem parte da circuitaria da formação da memória. Recebem informação do fórnice, de que são um alvo importante.',
    where: 'Atlas, vista Ventral: as duas bolinhas cor de tijolo na linha média, à frente da ponte. No Corte 2, na base do hipotálamo.',
    rel: ['hipotalamo', 'fornice', 'hipocampo'],
  },
  {
    id: 'subtalamo', g: 'die', name: 'Subtálamo', color: '#3F8FB5', sub: 'c2',
    rows: [['No modelo', E], ['Volta em', 'cap. 14']],
    morf: 'Região logo abaixo do tálamo.',
    func: 'Faz parte do sistema motor.',
    where: 'Corte 2, camada de células e fibras: a pequena região azul sob o tálamo, acima da substância nigra.',
    rel: ['talamo', 'substancia-nigra', 'nucleos-da-base'],
  },
  {
    id: 'hipofise', g: 'die', name: 'Hipófise', aka: 'glândula hipófise', color: '#D9A441', sub: 'medial',
    rows: [['No modelo', M]],
    morf: 'Glândula que fica ventral ao diencéfalo, pendurada abaixo do hipotálamo.',
    func: 'Comunica-se com muitas partes do organismo liberando hormônios na corrente sanguínea. É por ela que o hipotálamo controla parte das respostas do corpo.',
    where: 'Atlas, vista Medial: a bolinha dourada abaixo do hipotálamo.',
    rel: ['hipotalamo', 'diencefalo'],
  },
  {
    id: 'pineal', g: 'die', name: 'Glândula pineal', color: '#7BC66F', sub: 'tronco',
    rows: [['No modelo', M], ['Volta em', 'caps. 17 e 19']],
    morf: 'Pequena glândula ímpar, na linha média, dorsal ao tálamo e logo acima dos colículos superiores.',
    func: 'Secreta melatonina. Está envolvida na regulação do sono e do comportamento sexual.',
    where: 'Atlas, vista Tronco: o grão verde entre os dois tálamos, acima dos colículos. Na vista Medial, atrás do tálamo.',
    rel: ['talamo', 'coliculo-superior'],
  },
  {
    id: 'quiasma-optico', g: 'die', name: 'Quiasma óptico', color: '#F3DC8A', sub: 'ventral',
    rows: [['No modelo', M], ['Volta em', 'cap. 10']],
    morf: 'Cruzamento em forma de X na base do encéfalo, imediatamente à frente do hipotálamo.',
    func: 'É onde muitos dos axônios que vêm dos olhos decussam, isto é, cruzam de um lado para o outro. Antes dele os feixes são os nervos ópticos; depois dele, os tractos ópticos.',
    where: 'Atlas, vista Ventral: o X amarelo-claro na linha média, à frente dos corpos mamilares.',
    rel: ['nervo-optico', 'tracto-optico', 'hipotalamo'],
  },
  {
    id: 'tracto-optico', g: 'die', name: 'Tracto óptico', color: '#EFC75E', sub: 'ventral',
    rows: [['No modelo', M], ['Volta em', 'cap. 10']],
    morf: 'O feixe de axônios que sai do quiasma óptico para trás, contornando o mesencéfalo.',
    func: 'Leva a informação visual do quiasma até o tálamo.',
    where: 'Atlas, vista Ventral: a fita amarela que sai do quiasma para trás e para o lado. Em Por dentro dá para segui-la até o núcleo geniculado lateral.',
    rel: ['quiasma-optico', 'nucleo-geniculado-lateral', 'nervo-optico', 'voc-tracto'],
  },
  {
    id: 'olho', g: 'die', name: 'Olho e retina', color: '#B9C6D3', sub: 'ventral',
    rows: [['No modelo', M], ['Origem', 'vesícula óptica do prosencéfalo'], ['Volta em', 'caps. 9 e 10']],
    morf: 'A retina reveste o fundo do olho. Ela nasce do cálice óptico, uma dobra da vesícula óptica do prosencéfalo.',
    func: 'A retina e o nervo óptico são partes do encéfalo, e não do sistema nervoso periférico.',
    more: [{ x: 'O livro dedica o capítulo 9 ao olho. O globo ocular entrou no modelo para a via da visão ter começo.' }],
    where: 'Atlas, vista Ventral: os dois globos acinzentados à frente, de onde saem os nervos ópticos.',
    rel: ['nervo-optico', 'vesicula-optica', 'snc'],
  },
];
