// Fichas: mesencéfalo, ponte, cerebelo e bulbo. Fonte: cap. 7 e apêndice (ver 01-geral.pt.js).
const M = 'malha anatômica', E = 'desenho esquemático, posição aproximada', R = 'região aproximada sobre a malha';

export default [
  /* ===================== mesencéfalo ===================== */
  {
    id: 'mesencefalo', g: 'mes', name: 'Mesencéfalo', aka: 'encéfalo médio', color: '#E8899A', sub: 'medial',
    rows: [['No modelo', M], ['Partes', 'teto e tegmento'], ['Referência', 'aqueduto do mesencéfalo']],
    morf: 'A parte do tronco encefálico entre o diencéfalo e a ponte. Vem da vesícula do meio do tubo neural e é a que menos se modifica no desenvolvimento. Em volta do aqueduto, o lado dorsal é o teto e o ventral é o tegmento.',
    func: 'Conduz informação da medula espinhal ao prosencéfalo e de volta. Tem também neurônios dos sistemas sensoriais, do controle do movimento e de várias outras funções.',
    clueTitle: 'Lesão de um lado, efeito do outro',
    clue: 'O tracto corticospinal passa pelo mesencéfalo a caminho da medula. Uma lesão desse tracto no mesencéfalo de um lado faz perder o controle voluntário dos movimentos do lado oposto do corpo.',
    more: [
      'Grupos de neurônios espalhados no mesencéfalo mandam axônios para todo o sistema nervoso central e regulam a consciência, o humor, o prazer e a dor.',
      'Mais de 90% dos axônios que descem por ele, cerca de 20 milhões, fazem sinapse na ponte.',
      'Alguns axônios que movem os olhos nascem aqui e formam os nervos cranianos III e IV.',
    ],
    where: 'Atlas, vista Medial: a região rosada entre o tálamo e a ponte. No modo de cores Origem, tudo o que é mesencéfalo fica rosa. Cortes 4 e 5.',
    rel: ['teto', 'tegmento', 'aqueduto', 'tronco-encefalico', 'ponte', 'diencefalo'],
  },
  {
    id: 'teto', g: 'mes', name: 'Teto', aka: 'tectum', color: '#E7C65A', sub: 'tronco',
    rows: [['No modelo', M + ' (os quatro colículos)']],
    morf: 'O topo do mesencéfalo, dorsal ao aqueduto. Vem da superfície dorsal da vesícula mesencefálica. Diferencia-se em dois pares de saliências: os colículos superiores e os inferiores.',
    func: 'Os colículos superiores pertencem ao sistema visual; os inferiores, ao auditivo.',
    where: 'Atlas, vista Tronco: os quatro montículos atrás do tálamo. Ao escolher, os quatro acendem.',
    rel: ['coliculo-superior', 'coliculo-inferior', 'tegmento', 'aqueduto', 'mesencefalo'],
  },
  {
    id: 'tegmento', g: 'mes', name: 'Tegmento', aka: 'tegmento mesencefálico', color: '#F2B8C6', sub: 'medial',
    rows: [['No modelo', M]],
    morf: 'A parte do mesencéfalo ventral ao aqueduto. Vem do assoalho da vesícula mesencefálica.',
    func: 'É uma das porções mais "coloridas" do encéfalo: contém a substância nigra e o núcleo rubro, os dois ligados ao controle do movimento voluntário.',
    more: ['A formação reticular começa aqui e desce pelo centro do tronco encefálico até o bulbo.'],
    where: 'Atlas, vista Medial: a parte do mesencéfalo abaixo do aqueduto. Cortes 4 e 5: tudo o que fica abaixo do aqueduto.',
    rel: ['teto', 'substancia-nigra', 'nucleo-rubro', 'cinzenta-periaquedutal', 'formacao-reticular', 'mesencefalo'],
  },
  {
    id: 'coliculo-superior', g: 'mes', name: 'Colículo superior', aka: 'teto óptico', color: '#F2D548', sub: 'tronco',
    rows: [['No modelo', M], ['Volta em', 'caps. 10 e 14']],
    morf: 'O par de montículos de cima do teto do mesencéfalo. Colliculus vem do latim para "montículo".',
    func: 'Recebe aferência direta do olho; por isso também é chamado de teto óptico. Uma função dele é controlar os movimentos dos olhos, por conexões com os neurônios motores da musculatura ocular.',
    where: 'Atlas, vista Tronco: o par de montículos amarelos logo abaixo da pineal. Corte 4: o topo da secção.',
    rel: ['teto', 'coliculo-inferior', 'nc-oculomotor', 'nc-troclear', 'pineal'],
  },
  {
    id: 'coliculo-inferior', g: 'mes', name: 'Colículo inferior', color: '#C9B037', sub: 'tronco',
    rows: [['No modelo', M], ['Volta em', 'cap. 11']],
    morf: 'O par de montículos de baixo do teto do mesencéfalo, logo atrás dos colículos superiores.',
    func: 'Recebe informação do ouvido. É um núcleo retransmissor importante da informação auditiva a caminho do tálamo.',
    more: ['Os núcleos cocleares do bulbo projetam para ele.'],
    where: 'Atlas, vista Tronco: o par de montículos dourados, mais escuros, abaixo dos colículos superiores. Corte 5: o topo da secção.',
    rel: ['teto', 'coliculo-superior', 'nucleos-cocleares', 'nucleo-geniculado-medial'],
  },
  {
    id: 'cinzenta-periaquedutal', g: 'mes', name: 'Substância cinzenta periaquedutal', color: '#7986CB', sub: 'c4',
    rows: [['No modelo', E], ['Volta em', 'cap. 12']],
    morf: 'Substância cinzenta que envolve o aqueduto do mesencéfalo.',
    func: 'É importante no controle da sensação somática da dor.',
    where: 'Cortes 4 e 5: o anel azul-violeta em volta do aqueduto.',
    rel: ['aqueduto', 'tegmento', 'nucleo-da-rafe'],
  },
  {
    id: 'substancia-nigra', g: 'mes', name: 'Substância nigra', color: '#4E5D78', sub: 'c4',
    rows: [['No modelo', E], ['Volta em', 'cap. 14']],
    morf: 'Grupo de células na base do mesencéfalo, em faixa, dos dois lados. É o exemplo que o livro dá de "substância": um grupo de neurônios com limites menos precisos que os de um núcleo.',
    func: 'Está envolvida no controle do movimento voluntário.',
    clueTitle: 'Por que importa',
    clue: 'A doença de Parkinson resulta da degeneração dessa estrutura.',
    where: 'Cortes 4 e 5: a faixa cinza-azulada escura na parte de baixo da secção. No Corte 2 aparece a ponta dela, na base.',
    rel: ['tegmento', 'nucleo-rubro', 'nucleos-da-base', 'subtalamo', 'voc-substancia'],
  },
  {
    id: 'nucleo-rubro', g: 'mes', name: 'Núcleo rubro', color: '#E5536B', sub: 'c4',
    rows: [['No modelo', E], ['Volta em', 'cap. 14']],
    morf: 'Núcleo arredondado no tegmento do mesencéfalo rostral, um de cada lado.',
    func: 'Tem um papel no controle motor.',
    more: ['Os nomes dos tractos dizem onde eles nascem e terminam: o tracto rubrospinal sai daqui e termina na medula espinhal.'],
    where: 'Corte 4: o círculo vermelho no meio da secção, acima da substância nigra.',
    rel: ['tegmento', 'substancia-nigra', 'tracto-rubrospinal'],
  },

  /* ===================== ponte e cerebelo ===================== */
  {
    id: 'ponte', g: 'rom', name: 'Ponte', color: '#3FB3A0', sub: 'medial',
    rows: [['No modelo', M], ['Origem', 'rombencéfalo rostral'], ['Referência', 'quarto ventrículo']],
    morf: 'A protuberância na superfície ventral do tronco encefálico, entre o mesencéfalo e o bulbo. Forma-se da parede ventral do rombencéfalo rostral, que se dilata.',
    func: 'Funciona como um grande painel de distribuição que conecta o córtex cerebral ao cerebelo. Daí o nome.',
    clueTitle: 'O número',
    clue: 'De todos os axônios que descem pelo mesencéfalo, mais de 90%, cerca de 20 milhões no ser humano, fazem sinapse nos neurônios da ponte. Estes mandam toda essa informação ao cerebelo do lado oposto.',
    more: ['Os axônios que não terminam na ponte seguem para baixo e formam as pirâmides bulbares.', 'A protuberância existe para alojar toda essa circuitaria.'],
    where: 'Atlas, vistas Ventral e Medial: o volume saliente abaixo do mesencéfalo, à frente do cerebelo. Fica verde-azulada quando escolhida. Corte 6.',
    rel: ['nucleos-pontinos', 'cerebelo', 'bulbo', 'quarto-ventriculo', 'formacao-reticular', 'mesencefalo'],
  },
  {
    id: 'nucleos-pontinos', g: 'rom', name: 'Núcleos pontinos', color: '#B48AD6', sub: 'c6',
    rows: [['No modelo', E], ['Volta em', 'cap. 14']],
    morf: 'Os grupos de neurônios da parte ventral da ponte.',
    func: 'Recebem os axônios que descem do córtex cerebral e mandam a informação ao cerebelo do lado oposto. Muitas das aferências do córtex cerebelar vêm deles.',
    where: 'Corte 6: a região violeta na parte de baixo da ponte.',
    rel: ['ponte', 'cerebelo', 'cortex-cerebral'],
  },
  {
    id: 'formacao-reticular', g: 'rom', name: 'Formação reticular', aka: 'pontina e bulbar', color: '#8FAFC7', sub: 'c6',
    rows: [['No modelo', E], ['Volta em', 'caps. 14 e 19']],
    morf: 'Colunas de neurônios ao longo do centro do tronco encefálico, do mesencéfalo ao bulbo, logo abaixo do aqueduto e do quarto ventrículo.',
    func: 'Uma das funções dela é regular o ciclo de sono e vigília. A parte da ponte também regula a postura do corpo.',
    more: ['Os tractos reticulospinais, que descem pela medula, levam o nome dela: um nasce na ponte e outro no bulbo.'],
    where: 'Corte 6: a região azul-acinzentada no centro da ponte, sob o quarto ventrículo. Corte 8: a região de mesma cor no bulbo.',
    rel: ['ponte', 'bulbo', 'tegmento', 'tracto-reticulospinal-pontino', 'tracto-reticulospinal-bulbar'],
  },
  {
    id: 'cerebelo', g: 'rom', name: 'Cerebelo', color: '#4FA864', sub: 'cerebelo',
    rows: [['No modelo', M], ['Origem', 'rombencéfalo rostral (lábios rômbicos)'], ['Volta em', 'cap. 14']],
    morf: 'Fica atrás do cérebro e dorsal à ponte e ao bulbo, com aspecto enrugado. O nome vem do latim para "cérebro pequeno". Tem dois hemisférios e uma região mediana, o verme.',
    func: 'É um centro de controle do movimento. Recebe muitas aferências da medula espinhal, que informam a posição do corpo no espaço, e da ponte, que retransmitem do córtex as metas dos movimentos. Ele compara as duas coisas e calcula a sequência de contrações musculares necessária.',
    clueTitle: 'Pequeno só no tamanho',
    clue: 'Embora bem menor que o cérebro, o cerebelo tem tantos neurônios quanto os dois hemisférios cerebrais juntos.',
    more: [
      'Uma lesão no cerebelo deixa os movimentos descoordenados e imprecisos.',
      'Ao contrário dos hemisférios cerebrais, o lado esquerdo do cerebelo cuida dos movimentos do lado esquerdo do corpo.',
      'As saídas do cerebelo partem dos núcleos cerebelares profundos.',
    ],
    where: 'Atlas, vista Cerebelo: com o cérebro retirado, é ele que domina. Na vista Lateral, a massa sob o lobo occipital. Fica verde quando escolhido.',
    rel: ['verme', 'hemisferio-cerebelar', 'nucleos-cerebelares', 'pedunculo-cerebelar', 'ponte', 'labios-rombicos'],
  },
  {
    id: 'verme', g: 'rom', name: 'Verme', aka: 'do cerebelo', color: '#3E9A58', sub: 'cerebelo',
    rows: [['No modelo', R]],
    morf: 'A região mediana do cerebelo, entre os dois hemisférios.',
    func: 'O capítulo 7 só o nomeia. O papel do cerebelo no movimento é assunto do capítulo 14.',
    where: 'Atlas, vista Cerebelo: a faixa do meio, verde-escura quando escolhida.',
    rel: ['cerebelo', 'hemisferio-cerebelar'],
  },
  {
    id: 'hemisferio-cerebelar', g: 'rom', name: 'Hemisfério cerebelar', color: '#63B877', sub: 'cerebelo',
    rows: [['No modelo', R]],
    morf: 'Cada uma das duas metades laterais do cerebelo, de um lado e de outro do verme.',
    func: 'Cada hemisfério cerebelar cuida dos movimentos do mesmo lado do corpo.',
    where: 'Atlas, vista Cerebelo: as duas massas laterais, verde-claras quando escolhidas.',
    rel: ['cerebelo', 'verme'],
  },
  {
    id: 'nucleos-cerebelares', g: 'rom', name: 'Núcleos cerebelares profundos', color: '#4FBF9F', sub: 'c6',
    rows: [['No modelo', E], ['Volta em', 'cap. 14']],
    morf: 'Grupos de neurônios no interior do cerebelo, perto do quarto ventrículo.',
    func: 'As eferências do cerebelo saem deles. As entradas chegam ao córtex cerebelar, na superfície.',
    where: 'Corte 6: as pequenas regiões verde-água dentro do cerebelo, de cada lado do quarto ventrículo.',
    rel: ['cerebelo', 'nucleos-pontinos', 'quarto-ventriculo'],
  },
  {
    id: 'pedunculo-cerebelar', g: 'rom', name: 'Pedúnculos cerebelares', color: '#E3CF9F', sub: 'tronco',
    rows: [['No modelo', E], ['Volta em', 'cap. 14']],
    morf: 'Feixes grandes de axônios de cada lado do quarto ventrículo. Na figura do livro aparecem cortados, porque o cerebelo foi retirado.',
    func: 'Conectam o cerebelo ao tronco encefálico.',
    where: 'Atlas, vista Tronco: os dois tocos claros ao lado do assoalho do quarto ventrículo.',
    rel: ['cerebelo', 'ponte', 'quarto-ventriculo'],
  },

  /* ===================== bulbo ===================== */
  {
    id: 'bulbo', g: 'rom', name: 'Bulbo', aka: 'bulbo raquidiano, medula oblonga', color: '#B9DE9C', sub: 'medial',
    rows: [['No modelo', M], ['Origem', 'rombencéfalo caudal'], ['Referência', 'quarto ventrículo']],
    morf: 'A parte mais caudal do tronco encefálico, entre a ponte e a medula espinhal. No desenvolvimento, as paredes ventral e lateral se dilatam, e o teto fica coberto só por uma camada fina de células não neuronais.',
    func: 'Por ele passam os grandes feixes que ligam o prosencéfalo à medula. Tem também neurônios com funções sensoriais e motoras: retransmite ao tálamo o tato que vem da medula e o gosto que vem da língua, recebe os nervos auditivos nos núcleos cocleares e comanda a musculatura da língua pelo nervo craniano XII.',
    clueTitle: 'O cruzamento',
    clue: 'É no bulbo que o tracto corticospinal cruza de lado, na decussação piramidal, e é também no bulbo que a via do tato cruza. Por isso cada lado do cérebro lida com o lado oposto do corpo.',
    more: [
      'A destruição dos neurônios que retransmitem o tato causa anestesia.',
      'Uma lesão nos núcleos cocleares causa surdez.',
      'O nervo vago, a principal fonte de inervação parassimpática das vísceras, sai do bulbo.',
    ],
    where: 'Atlas, vistas Ventral e Medial: o trecho afilado abaixo da ponte. Fica verde-claro quando escolhido. Cortes 7 a 9.',
    rel: ['piramide-bulbar', 'decussacao-piramidal', 'nucleos-da-coluna-dorsal', 'nucleos-cocleares', 'oliva-inferior', 'ponte', 'medula-espinhal', 'quarto-ventriculo'],
  },
  {
    id: 'piramide-bulbar', g: 'rom', name: 'Pirâmide bulbar', color: '#C9A7E3', sub: 'ventral',
    rows: [['No modelo', E], ['Volta em', 'cap. 14']],
    morf: 'Feixe calibroso de axônios ao longo da superfície ventral do bulbo, um de cada lado da linha média. Em corte transversal tem forma triangular; daí o nome.',
    func: 'Contém o tracto corticospinal, que desce do córtex para a medula espinhal e comanda o movimento voluntário. Por isso "tracto piramidal" é usado como sinônimo de tracto corticospinal.',
    more: ['São os axônios que passaram pela ponte sem terminar nela.'],
    where: 'Atlas, vista Ventral: as duas colunas lilás na frente do bulbo. Cortes 7 a 9: os triângulos lilás na base.',
    rel: ['decussacao-piramidal', 'tracto-corticospinal', 'bulbo', 'ponte'],
  },
  {
    id: 'decussacao-piramidal', g: 'rom', name: 'Decussação piramidal', color: '#9B6FD0', sub: 'ventral',
    rows: [['No modelo', E]],
    morf: 'O ponto, perto de onde o bulbo se une à medula espinhal, em que cada tracto piramidal cruza a linha média para o outro lado.',
    func: 'Decussação é o cruzamento de axônios de um lado para o outro. Esta explica por que o córtex de um lado controla os movimentos do lado oposto do corpo.',
    where: 'Atlas, vista Ventral: o X roxo no fim das pirâmides, na passagem do bulbo para a medula. Em Vias › Movimento, é onde o sinal troca de lado.',
    rel: ['piramide-bulbar', 'tracto-corticospinal', 'bulbo', 'medula-espinhal', 'ipsi-contra'],
  },
  {
    id: 'oliva-inferior', g: 'rom', name: 'Oliva inferior', color: '#8BC34A', sub: 'c7',
    rows: [['No modelo', E], ['Volta em', 'cap. 14']],
    morf: 'Núcleo de contorno dobrado na parte ventral e lateral do bulbo, um de cada lado.',
    func: 'É importante para o controle motor.',
    where: 'Cortes 7 e 8: a região verde ondulada de cada lado, acima das pirâmides.',
    rel: ['bulbo', 'oliva-superior', 'piramide-bulbar'],
  },
  {
    id: 'oliva-superior', g: 'rom', name: 'Oliva superior', color: '#26A69A', sub: 'c7',
    rows: [['No modelo', E], ['Volta em', 'cap. 11']],
    morf: 'Pequeno núcleo do bulbo rostral, acima da oliva inferior.',
    func: 'É um dos núcleos importantes para o sistema auditivo.',
    where: 'Corte 7: a pequena região verde-azulada acima da oliva inferior.',
    rel: ['nucleos-cocleares', 'coliculo-inferior', 'oliva-inferior'],
  },
  {
    id: 'nucleos-cocleares', g: 'rom', name: 'Núcleos cocleares', aka: 'dorsal e ventral', color: '#7E8BD9', sub: 'c7',
    rows: [['No modelo', E], ['Volta em', 'cap. 11']],
    morf: 'Dois núcleos na borda lateral do bulbo rostral, um dorsal e um ventral.',
    func: 'Os axônios dos nervos auditivos, que trazem informação do ouvido interno, fazem sinapse neles. Dali a informação segue para várias estruturas, entre elas o colículo inferior.',
    more: ['Uma lesão nos núcleos cocleares causa surdez.', 'Recebem informação do nervo craniano VIII.'],
    where: 'Corte 7: as duas regiões azul-violeta na borda lateral, uma acima da outra.',
    rel: ['nc-vestibulococlear', 'coliculo-inferior', 'oliva-superior', 'nucleos-vestibulares'],
  },
  {
    id: 'nucleo-da-rafe', g: 'rom', name: 'Núcleo da rafe', color: '#FFCA28', sub: 'c7',
    rows: [['No modelo', E], ['Volta em', 'caps. 12, 19 e 22']],
    morf: 'Grupo de neurônios em faixa estreita, na linha média do bulbo.',
    func: 'Participa da modulação da dor, do humor e da vigília.',
    more: [{ x: 'Os núcleos da rafe são a fonte da serotonina do encéfalo. É o assunto do item Antidepressivo na Sinapse deste hub.' }],
    where: 'Cortes 7 e 8: a faixa amarela na linha média.',
    rel: ['bulbo', 'cinzenta-periaquedutal', 'formacao-reticular'],
  },
  {
    id: 'nucleos-vestibulares', g: 'rom', name: 'Núcleos vestibulares', color: '#F4A7B9', sub: 'c8',
    rows: [['No modelo', E], ['Volta em', 'cap. 11']],
    morf: 'Grupo de neurônios na parte dorsal do bulbo, sob o assoalho do quarto ventrículo.',
    func: 'Estão envolvidos no sentido do equilíbrio.',
    more: ['Recebem informação do nervo craniano VIII.', 'O tracto vestibulospinal nasce neles e termina na medula espinhal.'],
    where: 'Corte 8: a região rosa no canto dorsal, junto ao quarto ventrículo.',
    rel: ['nc-vestibulococlear', 'tracto-vestibulospinal', 'nucleos-cocleares'],
  },
  {
    id: 'nucleo-gustatorio', g: 'rom', name: 'Núcleo gustatório', aka: 'parte do núcleo do tracto solitário', color: '#4FC3C8', sub: 'c8',
    rows: [['No modelo', E], ['Volta em', 'cap. 8']],
    morf: 'Uma parte do núcleo do tracto solitário, na região dorsal do bulbo.',
    func: 'Transmite as sensações gustatórias: retransmite ao tálamo a informação do gosto que vem da língua.',
    where: 'Corte 8: a pequena região verde-água na parte dorsal, ao lado do núcleo vestibular.',
    rel: ['cortex-gustatorio', 'bulbo', 'talamo'],
  },
  {
    id: 'lemnisco-medial', g: 'rom', name: 'Lemnisco medial', color: '#5CA9E6', sub: 'c8',
    rows: [['No modelo', E], ['Volta em', 'cap. 12']],
    morf: 'Tracto em forma de fita, junto à linha média do bulbo. Lemniscus é "fita" em latim.',
    func: 'Os axônios dele levam a informação somatossensorial ao tálamo. São os axônios que saíram dos núcleos da coluna dorsal e cruzaram para o lado oposto.',
    where: 'Cortes 8 e 9: a faixa azul vertical junto à linha média, acima das pirâmides. Em Vias › Tato, é o trecho que sobe do bulbo ao tálamo.',
    rel: ['nucleos-da-coluna-dorsal', 'talamo', 'nucleo-ventral-posterior', 'coluna-dorsal', 'voc-lemnisco'],
  },
  {
    id: 'nucleos-da-coluna-dorsal', g: 'rom', name: 'Núcleos da coluna dorsal', color: '#EF9A6A', sub: 'c9',
    rows: [['No modelo', E], ['Volta em', 'cap. 12']],
    morf: 'Grupos de neurônios na parte dorsal do bulbo caudal, no nível em que o quarto ventrículo dá lugar ao canal central.',
    func: 'Recebem a informação somatossensorial que sobe pela coluna dorsal da medula, do mesmo lado do corpo. Os axônios que saem deles cruzam para o lado oposto e sobem pelo lemnisco medial até o tálamo.',
    clueTitle: 'Por que o tato cruza',
    clue: 'Esse cruzamento no bulbo é o motivo de o tato do lado esquerdo do corpo ser sentido pelo lado direito do cérebro.',
    where: 'Corte 9: as regiões alaranjadas na parte dorsal. Em Vias › Tato, é a primeira parada.',
    rel: ['coluna-dorsal', 'lemnisco-medial', 'bulbo', 'ipsi-contra'],
  },
];
