// Fichas: ventrículos e LCS, meninges e crânio, nervos cranianos e artérias. Fonte: cap. 7 e apêndice (ver 01-geral.pt.js).
const M = 'malha anatômica', E = 'desenho esquemático, posição aproximada';
const nc = (n, tipos) => [['No modelo', n === 'II' ? M : E], ['Número', n], ['Tipos de axônios', tipos]];

export default [
  /* ===================== ventrículos e LCS ===================== */
  {
    id: 'sistema-ventricular', g: 'vent', name: 'Sistema ventricular', color: '#6C9BEF', sub: 'lcs',
    rows: [['No modelo', M]],
    morf: 'Os espaços e canais cheios de líquido dentro do encéfalo: dois ventrículos laterais, o terceiro ventrículo, o aqueduto do mesencéfalo, o quarto ventrículo e, na medula, o canal central. É o que sobrou do interior do tubo neural.',
    func: 'Por ele circula o líquido cerebrospinal. Serve também de mapa: saber qual parte do sistema ventricular está por perto diz em que parte do encéfalo você está.',
    clueTitle: 'A chave do capítulo',
    clue: 'Ventrículos laterais: telencéfalo em volta. Terceiro ventrículo: tálamo e hipotálamo. Aqueduto: teto acima, tegmento abaixo. Quarto ventrículo: cerebelo acima, ponte e bulbo abaixo. Canal central: medula espinhal.',
    more: ['No ser humano o sistema ventricular está distorcido, sobretudo pelo crescimento dos lobos temporais, mas essas relações se mantêm.'],
    where: 'Em volta › LCS: o encéfalo vira contorno e os ventrículos ficam azuis. No Atlas, vista Por dentro.',
    rel: ['ventriculo-lateral', 'terceiro-ventriculo', 'aqueduto', 'quarto-ventriculo', 'canal-central', 'lcs', 'tubo-neural'],
  },
  {
    id: 'ventriculo-lateral', g: 'vent', name: 'Ventrículo lateral', color: '#7FA6F2', sub: 'lcs',
    rows: [['No modelo', M], ['Em volta dele', 'telencéfalo: córtex e telencéfalo basal']],
    morf: 'Cavidade par, uma em cada hemisfério cerebral. Os dois saem do terceiro ventrículo e se abrem como as galhadas de um veado. No ser humano cada um faz um arco que entra no lobo temporal.',
    func: 'É o marco do telencéfalo: sempre que aparecer um par de ventrículos em uma secção, o tecido em volta é telencéfalo. O plexo corióideo dentro deles produz o líquido cerebrospinal.',
    more: ['Por causa do arco, um corte coronal na junção do tálamo com o mesencéfalo (corte 3) pega o ventrículo lateral duas vezes em cada hemisfério.'],
    where: 'Em volta › LCS e Atlas › Por dentro: a peça azul-clara em arco dentro de cada hemisfério. Cortes 1 a 3: as cavidades pares.',
    rel: ['sistema-ventricular', 'terceiro-ventriculo', 'plexo-corioideo', 'telencefalo', 'nucleo-caudado', 'hipocampo'],
  },
  {
    id: 'terceiro-ventriculo', g: 'vent', name: 'Terceiro ventrículo', color: '#5B8DEF', sub: 'lcs',
    rows: [['No modelo', M], ['Em volta dele', 'diencéfalo: tálamo e hipotálamo']],
    morf: 'Cavidade ímpar, estreita, no plano mediano. Em corte coronal parece uma fenda. O tálamo fica de cada lado dela e o hipotálamo forma o assoalho.',
    func: 'É o marco do diencéfalo. Recebe o líquido dos dois ventrículos laterais e o passa ao aqueduto.',
    where: 'Em volta › LCS: a lâmina azul no centro. Atlas, vista Medial: a área azul entre o tálamo e o hipotálamo. Cortes 1 a 3: a fenda na linha média.',
    rel: ['sistema-ventricular', 'ventriculo-lateral', 'aqueduto', 'talamo', 'hipotalamo'],
  },
  {
    id: 'aqueduto', g: 'vent', name: 'Aqueduto do mesencéfalo', aka: 'aqueduto encefálico', color: '#3D74E0', sub: 'lcs',
    rows: [['No modelo', M], ['Em volta dele', 'mesencéfalo: teto e tegmento']],
    morf: 'Canal estreito no centro do mesencéfalo. Em corte transversal é pequeno e circular. Liga o terceiro ventrículo ao quarto.',
    func: 'É o marco do mesencéfalo: dorsal a ele fica o teto; ventral, o tegmento.',
    where: 'Em volta › LCS: o tubo fino azul-escuro entre o terceiro e o quarto ventrículo. Cortes 4 e 5: o ponto no centro.',
    rel: ['sistema-ventricular', 'terceiro-ventriculo', 'quarto-ventriculo', 'teto', 'tegmento', 'cinzenta-periaquedutal'],
  },
  {
    id: 'quarto-ventriculo', g: 'vent', name: 'Quarto ventrículo', color: '#6C9BEF', sub: 'lcs',
    rows: [['No modelo', M], ['Em volta dele', 'rombencéfalo: cerebelo, ponte e bulbo']],
    morf: 'Cavidade no centro do rombencéfalo, contínua com o aqueduto. O cerebelo fica dorsal a ela; a ponte e o bulbo, ventrais.',
    func: 'É o marco do rombencéfalo. É também por onde o líquido sai do sistema ventricular: pequenas aberturas, perto de onde o cerebelo se liga ao tronco, levam ao espaço subaracnóideo.',
    where: 'Em volta › LCS: a cavidade azul atrás da ponte. Atlas, vista Tronco: o assoalho dela aparece entre os pedúnculos cerebelares. Cortes 6 a 8.',
    rel: ['sistema-ventricular', 'aqueduto', 'canal-central', 'cerebelo', 'ponte', 'bulbo', 'espaco-subaracnoideo'],
  },
  {
    id: 'canal-central', g: 'vent', name: 'Canal central', aka: 'canal central da medula', color: '#3463C9', sub: 'lcs',
    rows: [['No modelo', M]],
    morf: 'Canal muito fino, cheio de líquido cerebrospinal, no centro da medula espinhal. É o que resta da cavidade do tubo neural caudal.',
    func: 'É o marco da medula espinhal: a medula forma as paredes dele. Ele começa a aparecer nos cortes quando o bulbo e o quarto ventrículo acabam.',
    where: 'Em volta › LCS: o fio azul-escuro que desce do quarto ventrículo. Corte 9 e módulo Medula: o ponto no centro.',
    rel: ['sistema-ventricular', 'quarto-ventriculo', 'medula-espinhal'],
  },
  {
    id: 'plexo-corioideo', g: 'vent', name: 'Plexo corióideo', color: '#E06C8B', sub: 'lcs',
    rows: [['No modelo', M]],
    morf: 'Tecido especial que fica dentro dos ventrículos dos hemisférios cerebrais.',
    func: 'Produz o líquido cerebrospinal.',
    where: 'Em volta › LCS: a faixa rosa-avermelhada dentro de cada ventrículo lateral. É o primeiro passo do caminho do líquido.',
    rel: ['lcs', 'ventriculo-lateral'],
  },
  {
    id: 'lcs', g: 'vent', name: 'Líquido cerebrospinal', aka: 'LCS', color: '#8EC5F5', sub: 'lcs',
    rows: [['No modelo', 'gotas em movimento']],
    morf: 'Líquido claro e salgado que enche o sistema ventricular e o espaço subaracnóideo.',
    func: 'O encéfalo flutua dentro da cabeça nessa camada fina de líquido. Ele é produzido pelo plexo corióideo, desce pelos ventrículos, sai para o espaço subaracnóideo e ali é absorvido pelos vasos sanguíneos, nas vilosidades aracnoides.',
    clueTitle: 'Se o caminho entope',
    clue: 'Quando o fluxo é bloqueado, o líquido se acumula e dilata os ventrículos. É a hidrocefalia, "cabeça d\'água". No bebê, o crânio ainda mole cresce para acomodar o líquido. No adulto o crânio não cede, e a pressão dentro dele sobe.',
    where: 'Em volta › LCS: as gotas azul-claras. O passo a passo segue o líquido do plexo corióideo até o sangue.',
    rel: ['plexo-corioideo', 'sistema-ventricular', 'espaco-subaracnoideo', 'vilosidades-aracnoides'],
  },
  {
    id: 'espaco-subaracnoideo', g: 'vent', name: 'Espaço subaracnóideo', color: '#B5DBF7', sub: 'camadas',
    rows: [['No modelo', E]],
    morf: 'O espaço entre a membrana aracnoide e a pia-máter, cheio de líquido cerebrospinal.',
    func: 'É onde o líquido que sai dos ventrículos circula em volta do encéfalo e da medula, até ser absorvido pelos vasos sanguíneos.',
    where: 'Em volta › Camadas: a faixa azul-clara atravessada por fios, entre a aracnoide e a pia. Em LCS, a casca clara em volta do encéfalo.',
    rel: ['aracnoide', 'pia-mater', 'lcs', 'vilosidades-aracnoides'],
  },
  {
    id: 'vilosidades-aracnoides', g: 'vent', name: 'Vilosidades aracnoides', color: '#5E97D6', sub: 'lcs',
    rows: [['No modelo', E]],
    morf: 'Estruturas especiais da aracnoide, no espaço subaracnóideo.',
    func: 'É por elas que o líquido cerebrospinal é absorvido pelos vasos sanguíneos.',
    more: [{ x: 'O modelo as desenha no alto da cabeça, junto a um vaso na linha média. O capítulo 7 não diz onde elas ficam; na anatomia, projetam-se para dentro de um grande seio venoso da dura-máter.' }],
    where: 'Em volta › LCS: os grãos azuis no alto, junto ao vaso escuro da linha média. É o último passo do caminho do líquido.',
    rel: ['lcs', 'espaco-subaracnoideo', 'aracnoide'],
  },

  /* ===================== meninges e crânio ===================== */
  {
    id: 'meninges', g: 'men', name: 'Meninges', color: '#9DB4DE', sub: 'meninges',
    rows: [['No modelo', E], ['Camadas', 'dura-máter, aracnoide e pia-máter']],
    morf: 'Três membranas que envolvem o encéfalo e a medula espinhal. O nome vem do grego para "cobertura". De fora para dentro: dura-máter, membrana aracnoide e pia-máter.',
    func: 'O sistema nervoso central não encosta direto no osso: as meninges o protegem.',
    where: 'Em volta › Meninges: as cascas em degraus sob o crânio. Em Camadas, o bloco ampliado mostra uma por uma.',
    rel: ['dura-mater', 'aracnoide', 'pia-mater', 'cranio', 'espaco-subaracnoideo'],
  },
  {
    id: 'dura-mater', g: 'men', name: 'Dura-máter', color: '#7F9FDB', sub: 'camadas',
    rows: [['No modelo', E]],
    morf: 'A meninge mais externa. O nome é latim para "mãe dura": tem consistência de couro. Forma um saco firme, que não estica, em volta do encéfalo e da medula.',
    func: 'É a camada resistente que fica logo abaixo do osso.',
    clueTitle: 'Hematoma subdural',
    clue: 'Normalmente não há espaço entre a dura e a aracnoide. Se vasos que atravessam a dura se rompem, o sangue pode ficar preso ali e comprimir o sistema nervoso central.',
    where: 'Em volta › Camadas: a lâmina azul logo abaixo do osso. Em Meninges, a casca azul.',
    rel: ['meninges', 'aracnoide', 'cranio'],
  },
  {
    id: 'aracnoide', g: 'men', name: 'Membrana aracnoide', color: '#E3D08A', sub: 'camadas',
    rows: [['No modelo', E]],
    morf: 'A meninge do meio, logo abaixo da dura-máter. O nome vem do grego para "aranha": tem aparência e consistência de teia.',
    func: 'Entre ela e a pia-máter fica o espaço subaracnóideo, cheio de líquido cerebrospinal.',
    where: 'Em volta › Camadas: a lâmina amarelada com fios que descem até a pia. Em Meninges, a casca amarelada.',
    rel: ['meninges', 'dura-mater', 'pia-mater', 'espaco-subaracnoideo', 'vilosidades-aracnoides'],
  },
  {
    id: 'pia-mater', g: 'men', name: 'Pia-máter', color: '#EFA9BC', sub: 'camadas',
    rows: [['No modelo', E]],
    morf: 'A meninge mais interna. O nome é latim para "mãe piedosa". É uma membrana fina, colada à superfície do encéfalo.',
    func: 'Ao longo dela correm os vasos sanguíneos que depois penetram no tecido nervoso.',
    more: ['O córtex cerebral fica logo abaixo da pia-máter.'],
    where: 'Em volta › Camadas: a película rosa sobre o córtex, com uma artéria correndo por cima.',
    rel: ['meninges', 'aracnoide', 'espaco-subaracnoideo', 'cortex-cerebral'],
  },
  {
    id: 'cranio', g: 'men', name: 'Crânio', aka: 'ossos frontal, parietal, temporal e occipital', color: '#E6DDC6', sub: 'meninges',
    rows: [['No modelo', M]],
    morf: 'A caixa óssea que guarda o encéfalo inteiro.',
    func: 'Os quatro lobos do cérebro têm os nomes dos ossos do crânio que ficam logo acima deles: frontal, parietal, temporal e occipital.',
    more: ['O crânio é o limite que obrigou o córtex humano a dobrar-se.'],
    where: 'Em volta › Meninges: a casca clara de osso, cortada para deixar ver as meninges.',
    rel: ['meninges', 'lobo-frontal', 'lobo-parietal', 'lobo-temporal', 'lobo-occipital'],
  },

  /* ===================== nervos cranianos ===================== */
  {
    id: 'nervos-cranianos', g: 'nc', name: 'Nervos cranianos', aka: '12 pares', color: '#E8C547', sub: 'nervos',
    rows: [['No modelo', E + ' (o óptico é malha)']],
    morf: 'Doze pares de nervos que saem da base do encéfalo, a maioria do tronco encefálico. Cada um tem nome e número. A numeração, de anterior para posterior, é de Galeno, de quase 1.800 anos atrás.',
    func: 'Inervam principalmente a cabeça. Um mesmo nervo costuma ter fibras com funções diferentes.',
    clueTitle: 'Nem todos são periféricos',
    clue: 'Os dois primeiros, olfatório e óptico, são na verdade partes do sistema nervoso central. Os outros se parecem com os nervos espinhais: contêm axônios do sistema nervoso periférico.',
    more: [
      'Os nervos cranianos têm núcleos associados no mesencéfalo, na ponte e no bulbo. Os núcleos coclear e vestibular, por exemplo, recebem do nervo VIII.',
      'Conhecer os nervos e suas funções ajuda no diagnóstico de distúrbios neurológicos.',
    ],
    where: 'Em volta › Nervos: os doze pares de tocos coloridos na base do encéfalo, numerados de I a XII.',
    rel: ['nc-olfatorio', 'nervo-optico', 'nc-oculomotor', 'nc-troclear', 'nc-trigemeo', 'nc-abducente', 'nc-facial', 'nc-vestibulococlear', 'nc-glossofaringeo', 'nc-vago', 'nc-acessorio', 'nc-hipoglosso'],
  },
  {
    id: 'nc-olfatorio', g: 'nc', name: 'I. Olfatório', color: '#E8C547', sub: 'nervos',
    rows: nc('I', 'sensorial especial'),
    morf: 'O primeiro nervo craniano. Na base do encéfalo, é a haste que corre sob o lobo frontal e termina no bulbo olfatório.',
    func: 'Sensação do olfato.',
    more: ['É, na verdade, parte do sistema nervoso central.'],
    where: 'Em volta › Nervos e Atlas › Ventral: a haste clara sob o lobo frontal, ao lado da linha média.',
    rel: ['bulbo-olfatorio', 'nervos-cranianos'],
  },
  {
    id: 'nervo-optico', g: 'nc', name: 'II. Óptico', aka: 'nervo óptico', color: '#F0B94A', sub: 'nervos',
    rows: nc('II', 'sensorial especial').concat([['Volta em', 'cap. 10']]),
    morf: 'Feixe de axônios que sai do fundo de cada olho e vai até o quiasma óptico. É o único agrupamento de axônios do sistema nervoso central que leva o nome de nervo.',
    func: 'Sensação da visão.',
    more: ['Nasce do pedículo óptico, uma parte da vesícula óptica do prosencéfalo. Por isso é parte do encéfalo.', 'Depois do quiasma, os mesmos axônios seguem como tracto óptico.'],
    where: 'Em volta › Nervos e Atlas › Ventral: o cordão amarelo-alaranjado do olho ao quiasma.',
    rel: ['olho', 'quiasma-optico', 'tracto-optico', 'nervos-cranianos', 'voc-nervo'],
  },
  {
    id: 'nc-oculomotor', g: 'nc', name: 'III. Oculomotor', color: '#EE9B4E', sub: 'nervos',
    rows: nc('III', 'motor somático e motor visceral'),
    morf: 'Sai da face ventral do mesencéfalo, perto da linha média.',
    func: 'Movimentos dos olhos e das pálpebras. As fibras motoras viscerais fazem o controle parassimpático do tamanho da pupila.',
    more: ['Alguns dos axônios que movem os olhos nascem no mesencéfalo e se juntam para formar os nervos III e IV.'],
    where: 'Em volta › Nervos: o par laranja que sai do mesencéfalo, logo à frente da ponte.',
    rel: ['mesencefalo', 'coliculo-superior', 'nc-troclear', 'nc-abducente', 'nervos-cranianos'],
  },
  {
    id: 'nc-troclear', g: 'nc', name: 'IV. Troclear', color: '#E77E5C', sub: 'nervos',
    rows: nc('IV', 'motor somático'),
    morf: 'Nervo fino que aparece contornando o mesencéfalo, ao lado dele.',
    func: 'Movimentos oculares.',
    where: 'Em volta › Nervos: o par fino, vermelho-alaranjado, ao lado do mesencéfalo.',
    rel: ['mesencefalo', 'nc-oculomotor', 'nc-abducente', 'nervos-cranianos'],
  },
  {
    id: 'nc-trigemeo', g: 'nc', name: 'V. Trigêmeo', color: '#DD6A7C', sub: 'nervos',
    rows: nc('V', 'somatossensorial e motor somático'),
    morf: 'Nervo grosso que sai do lado da ponte.',
    func: 'Sensação do tato da face. Movimentos dos músculos da mastigação.',
    where: 'Em volta › Nervos: o par mais grosso, rosa-avermelhado, no lado da ponte.',
    rel: ['ponte', 'nervos-cranianos'],
  },
  {
    id: 'nc-abducente', g: 'nc', name: 'VI. Abducente', color: '#C96BA6', sub: 'nervos',
    rows: nc('VI', 'motor somático'),
    morf: 'Sai perto da linha média, no limite entre a ponte e o bulbo.',
    func: 'Movimentos oculares.',
    where: 'Em volta › Nervos: o par magenta junto à linha média, na borda de baixo da ponte.',
    rel: ['ponte', 'bulbo', 'nc-oculomotor', 'nc-troclear', 'nervos-cranianos'],
  },
  {
    id: 'nc-facial', g: 'nc', name: 'VII. Facial', color: '#A979C9', sub: 'nervos',
    rows: nc('VII', 'motor somático, somatossensorial, sensorial especial e motor visceral'),
    morf: 'Sai do lado do tronco encefálico, no limite entre a ponte e o bulbo, junto do nervo VIII.',
    func: 'Movimentos dos músculos da expressão facial. Sensação da gustação nos dois terços anteriores da língua.',
    where: 'Em volta › Nervos: o par roxo no ângulo entre a ponte, o bulbo e o cerebelo.',
    rel: ['ponte', 'bulbo', 'nc-vestibulococlear', 'nucleo-gustatorio', 'nervos-cranianos'],
  },
  {
    id: 'nc-vestibulococlear', g: 'nc', name: 'VIII. Vestibulococlear', color: '#7F8BD8', sub: 'nervos',
    rows: nc('VIII', 'sensorial especial').concat([['Volta em', 'cap. 11']]),
    morf: 'Sai do lado do tronco encefálico, no limite entre a ponte e o bulbo, junto do nervo VII.',
    func: 'Sensação da audição e do equilíbrio.',
    more: ['Os núcleos coclear e vestibular do bulbo recebem a informação dele.'],
    where: 'Em volta › Nervos: o par azul-violeta ao lado do nervo facial.',
    rel: ['nucleos-cocleares', 'nucleos-vestibulares', 'nc-facial', 'nervos-cranianos'],
  },
  {
    id: 'nc-glossofaringeo', g: 'nc', name: 'IX. Glossofaríngeo', color: '#5FA4D9', sub: 'nervos',
    rows: nc('IX', 'motor somático, motor visceral, sensorial especial e sensorial visceral'),
    morf: 'Sai do lado do bulbo, logo abaixo dos nervos VII e VIII.',
    func: 'Movimento dos músculos da garganta (orofaringe). Controle parassimpático das glândulas salivares. Gustação no terço posterior da língua. Detecção de alterações da pressão arterial na aorta.',
    where: 'Em volta › Nervos: o par azul no lado do bulbo, o primeiro da fileira.',
    rel: ['bulbo', 'nc-vago', 'nucleo-gustatorio', 'nervos-cranianos'],
  },
  {
    id: 'nc-vago', g: 'nc', name: 'X. Vago', color: '#52B7C0', sub: 'nervos',
    rows: nc('X', 'motor visceral, sensorial visceral e motor somático').concat([['Volta em', 'cap. 15']]),
    morf: 'Sai do lado do bulbo, por uma fileira de raízes, logo abaixo do glossofaríngeo.',
    func: 'Controle parassimpático do coração, dos pulmões e dos órgãos abdominais. Sensação de dor associada às vísceras. Movimento dos músculos da garganta (orofaringe).',
    clueTitle: 'Por que importa',
    clue: 'A maior parte da inervação parassimpática das vísceras vem do nervo vago.',
    where: 'Em volta › Nervos: o par verde-azulado no lado do bulbo, o do meio da fileira.',
    rel: ['bulbo', 'snv', 'nc-glossofaringeo', 'nc-acessorio', 'nervos-cranianos'],
  },
  {
    id: 'nc-acessorio', g: 'nc', name: 'XI. Acessório', color: '#5DBE96', sub: 'nervos',
    rows: nc('XI', 'motor somático'),
    morf: 'Sai do lado do bulbo, abaixo do vago, na passagem para a medula espinhal.',
    func: 'Movimento dos músculos da garganta e do pescoço.',
    where: 'Em volta › Nervos: o par verde no lado do bulbo, o último da fileira.',
    rel: ['bulbo', 'nc-vago', 'nervos-cranianos'],
  },
  {
    id: 'nc-hipoglosso', g: 'nc', name: 'XII. Hipoglosso', color: '#8CC56A', sub: 'nervos',
    rows: nc('XII', 'motor somático'),
    morf: 'Sai da face ventral do bulbo, mais perto da linha média que os nervos IX a XI.',
    func: 'Movimentos da língua.',
    more: ['Os neurônios motores que comandam a língua ficam no bulbo. Pense nele da próxima vez que mostrar a língua.'],
    where: 'Em volta › Nervos: o par verde-claro na frente do bulbo, ao lado das pirâmides.',
    rel: ['bulbo', 'piramide-bulbar', 'nervos-cranianos'],
  },

  /* ===================== artérias ===================== */
  {
    id: 'circulo-arterial', g: 'art', name: 'Círculo arterial do cérebro', aka: 'polígono de Willis', color: '#E57373', sub: 'arterias',
    rows: [['No modelo', E]],
    morf: 'Anel de artérias ligadas entre si na base do encéfalo. É formado pelas artérias cerebrais posteriores, as comunicantes posteriores, as carótidas internas, as cerebrais anteriores e a comunicante anterior.',
    func: 'Junta os dois pares de artérias que levam sangue ao encéfalo: as vertebrais, por trás, e as carótidas internas, pela frente.',
    where: 'Em volta › Artérias: o anel vermelho na base, em volta do quiasma óptico e dos corpos mamilares. Ao escolher, o anel inteiro acende.',
    rel: ['art-carotida-interna', 'art-cerebral-anterior', 'art-comunicante-anterior', 'art-comunicante-posterior', 'art-cerebral-posterior', 'art-basilar'],
  },
  {
    id: 'art-vertebral', g: 'art', name: 'Artéria vertebral', color: '#A34A3A', sub: 'arterias',
    rows: [['No modelo', E]],
    morf: 'Par de artérias que sobe pela frente do bulbo.',
    func: 'É um dos dois pares que fornecem sangue ao encéfalo. As duas convergem perto da base da ponte e formam a artéria basilar.',
    where: 'Em volta › Artérias: os dois tubos castanho-avermelhados sobre o bulbo.',
    rel: ['art-basilar', 'art-carotida-interna', 'bulbo'],
  },
  {
    id: 'art-basilar', g: 'art', name: 'Artéria basilar', color: '#8E2430', sub: 'arterias',
    rows: [['No modelo', E]],
    morf: 'Artéria única, na linha média, sobre a face ventral da ponte. Forma-se da união das duas vertebrais.',
    func: 'No nível do mesencéfalo ela se divide nas artérias cerebelares superiores e nas cerebrais posteriores, direitas e esquerdas.',
    where: 'Em volta › Artérias: o tubo vermelho-escuro que sobe pelo meio da ponte.',
    rel: ['art-vertebral', 'art-cerebelar-superior', 'art-cerebral-posterior', 'ponte'],
  },
  {
    id: 'art-cerebelar-superior', g: 'art', name: 'Artéria cerebelar superior', color: '#D35D8C', sub: 'arterias',
    rows: [['No modelo', E]],
    morf: 'Ramo da artéria basilar, um de cada lado, que sai no nível do mesencéfalo e contorna o tronco em direção ao cerebelo.',
    func: 'O capítulo 7 só a nomeia como ramo da basilar.',
    where: 'Em volta › Artérias: o par rosa que sai do alto da basilar para os lados, logo abaixo das cerebrais posteriores.',
    rel: ['art-basilar', 'art-cerebral-posterior', 'cerebelo'],
  },
  {
    id: 'art-cerebral-posterior', g: 'art', name: 'Artéria cerebral posterior', color: '#AD1457', sub: 'arterias',
    rows: [['No modelo', E]],
    morf: 'Ramo final da artéria basilar, um de cada lado, no nível do mesencéfalo.',
    func: 'Irriga a parede medial do lobo occipital e a parte inferior do lobo temporal. Manda um ramo, a comunicante posterior, que a liga à carótida interna.',
    where: 'Em volta › Artérias: o par magenta-escuro que sai do topo da basilar e contorna o mesencéfalo.',
    rel: ['art-basilar', 'art-comunicante-posterior', 'lobo-occipital', 'cortex-temporal-inferior', 'circulo-arterial'],
  },
  {
    id: 'art-comunicante-posterior', g: 'art', name: 'Artéria comunicante posterior', color: '#F08A5D', sub: 'arterias',
    rows: [['No modelo', E]],
    morf: 'Ramo curto de cada artéria cerebral posterior.',
    func: 'Conecta a cerebral posterior à carótida interna do mesmo lado. Fecha o círculo arterial atrás.',
    where: 'Em volta › Artérias: o trecho curto, laranja, de cada lado do anel.',
    rel: ['art-cerebral-posterior', 'art-carotida-interna', 'circulo-arterial'],
  },
  {
    id: 'art-carotida-interna', g: 'art', name: 'Artéria carótida interna', color: '#C0392B', sub: 'arterias',
    rows: [['No modelo', E]],
    morf: 'Par de artérias que chega à base do encéfalo ao lado do quiasma óptico.',
    func: 'É o outro par que fornece sangue ao encéfalo. Cada uma se ramifica em artéria cerebral média e artéria cerebral anterior.',
    where: 'Em volta › Artérias: os dois tocos vermelhos ao lado do quiasma óptico.',
    rel: ['art-cerebral-media', 'art-cerebral-anterior', 'art-comunicante-posterior', 'art-vertebral', 'circulo-arterial'],
  },
  {
    id: 'art-cerebral-media', g: 'art', name: 'Artéria cerebral média', color: '#E74C3C', sub: 'arterias',
    rows: [['No modelo', E]],
    morf: 'Ramo da carótida interna que segue para o lado, entra na fissura lateral e se espalha pela face lateral do hemisfério.',
    func: 'Supre a maior parte da superfície lateral do cérebro. Irriga também as estruturas profundas do prosencéfalo basal.',
    where: 'Em volta › Artérias: o ramo vermelho-vivo que vai para o lado e se abre em leque sobre a face lateral.',
    rel: ['art-carotida-interna', 'fissura-lateral', 'telencefalo-basal', 'art-cerebral-anterior'],
  },
  {
    id: 'art-cerebral-anterior', g: 'art', name: 'Artéria cerebral anterior', color: '#E67E22', sub: 'arterias',
    rows: [['No modelo', E]],
    morf: 'Ramo da carótida interna que segue para a frente e para a linha média, entra na fissura longitudinal e contorna o corpo caloso.',
    func: 'Irriga a maior parte da parede medial dos hemisférios cerebrais.',
    where: 'Em volta › Artérias: o ramo laranja que sobe pela face medial do hemisfério, em volta do corpo caloso.',
    rel: ['art-carotida-interna', 'art-comunicante-anterior', 'corpo-caloso', 'art-cerebral-media'],
  },
  {
    id: 'art-comunicante-anterior', g: 'art', name: 'Artéria comunicante anterior', color: '#F4B350', sub: 'arterias',
    rows: [['No modelo', E]],
    morf: 'Trecho curto, na linha média, à frente do quiasma óptico.',
    func: 'Conecta as duas artérias cerebrais anteriores. Fecha o círculo arterial na frente.',
    where: 'Em volta › Artérias: a pontezinha amarelada entre as duas cerebrais anteriores.',
    rel: ['art-cerebral-anterior', 'circulo-arterial'],
  },
];
