// Fichas: medula espinhal, nervos espinhais e tractos. Fonte: cap. 7 e apêndice (ver 01-geral.pt.js).
const M = 'malha anatômica', E = 'desenho esquemático', T = 'região marcada na secção, como na figura do livro';

export default [
  {
    id: 'coluna-vertebral', g: 'med', name: 'Coluna vertebral', aka: 'vértebras C1 a S1', color: '#E6DDC6', sub: 'coluna',
    rows: [['No modelo', M], ['Vértebras', '7 cervicais, 12 torácicas, 5 lombares e as sacrais']],
    morf: 'A coluna de ossos que guarda a medula espinhal. As vértebras do pescoço são as cervicais, C1 a C7. As que se articulam com as costelas são as torácicas, T1 a T12. As cinco de baixo são as lombares. As da área pélvica são as sacrais.',
    func: 'Protege a medula. Os nervos espinhais saem dela pelos espaços entre uma vértebra e outra, os forames intervertebrais.',
    more: ['A coluna e os músculos ligados a ela se desenvolvem dos somitos, que dão 33 vértebras.'],
    where: 'Medula › Coluna: os ossos claros, vistos por trás. A medula amarela corre por dentro deles.',
    rel: ['medula-espinhal', 'nervo-espinhal', 'cauda-equina', 'somitos'],
  },
  {
    id: 'nervo-espinhal', g: 'med', name: 'Nervo espinhal', color: '#E3B94F', sub: 'segmento',
    rows: [['No modelo', E]],
    morf: 'Nervo que sai da medula pelo espaço entre duas vértebras. Ao atravessar o forame intervertebral, divide-se em duas raízes, a dorsal e a ventral, que se prendem à medula.',
    func: 'É por eles que a medula se comunica com o corpo. Fazem parte do sistema nervoso periférico somático: inervam a pele, as articulações e os músculos de controle voluntário.',
    clueTitle: 'Os nomes',
    clue: 'Os nervos espinhais e os segmentos da medula ligados a eles levam o nome das vértebras. Há oito nervos cervicais para sete vértebras cervicais.',
    more: ['Os nervos espinhais sacrais são, com o nervo vago, a fonte das fibras parassimpáticas.'],
    where: 'Medula › Segmento: o cordão dourado em que as duas raízes se juntam. Em Coluna, os ramos que saem entre as vértebras.',
    rel: ['raiz-dorsal', 'raiz-ventral', 'ganglio-da-raiz-dorsal', 'coluna-vertebral', 'snp'],
  },
  {
    id: 'cauda-equina', g: 'med', name: 'Cauda equina', color: '#D9A83F', sub: 'coluna',
    rows: [['No modelo', E]],
    morf: 'O feixe de nervos espinhais que desce por dentro da coluna lombar e sacral, abaixo do fim da medula.',
    func: 'Existe porque a medula não cresce depois do nascimento e a coluna vertebral cresce. A medula do adulto acaba, segundo o livro, no nível da terceira vértebra lombar, e os nervos de baixo têm de descer até a saída deles.',
    more: [{ x: 'Outros textos de anatomia situam o fim da medula do adulto entre as vértebras L1 e L2.' }],
    where: 'Medula › Coluna: o feixe de fios dourados abaixo do fim da medula, dentro das vértebras lombares e do sacro.',
    rel: ['medula-espinhal', 'nervo-espinhal', 'coluna-vertebral'],
  },
  {
    id: 'raiz-dorsal', g: 'med', name: 'Raiz dorsal', color: '#64B5F6', sub: 'segmento',
    rows: [['No modelo', E]],
    morf: 'A raiz de trás de cada nervo espinhal. Chega à medula por uma fileira de filamentos.',
    func: 'Leva à medula os axônios sensoriais. Os corpos celulares desses axônios ficam no gânglio da raiz dorsal.',
    more: ['Foi François Magendie quem mostrou que a raiz dorsal traz informação para a medula.'],
    where: 'Medula › Segmento: o cordão azul que entra por trás, com o gânglio no meio do caminho.',
    rel: ['ganglio-da-raiz-dorsal', 'raiz-ventral', 'corno-dorsal', 'nervo-espinhal', 'aferente-eferente'],
  },
  {
    id: 'ganglio-da-raiz-dorsal', g: 'med', name: 'Gânglio da raiz dorsal', color: '#F6C453', sub: 'segmento',
    rows: [['No modelo', E]],
    morf: 'Dilatação da raiz dorsal, fora da medula. Há um para cada nervo espinhal.',
    func: 'Guarda os corpos celulares dos neurônios sensoriais cujos axônios entram na medula pela raiz dorsal. Como fica fora da medula, pertence ao sistema nervoso periférico.',
    more: ['É o exemplo que o livro dá de "gânglio": um agrupamento de neurônios no sistema nervoso periférico.'],
    where: 'Medula › Segmento: o caroço amarelo na raiz dorsal.',
    rel: ['raiz-dorsal', 'nervo-espinhal', 'snp', 'voc-ganglio', 'crista-neural'],
  },
  {
    id: 'raiz-ventral', g: 'med', name: 'Raiz ventral', color: '#E57373', sub: 'segmento',
    rows: [['No modelo', E]],
    morf: 'A raiz da frente de cada nervo espinhal. Sai da medula por uma fileira de filamentos.',
    func: 'Leva para fora os axônios motores, que saem da substância cinzenta ventral da medula.',
    more: ['Foi Charles Bell quem mostrou que a raiz ventral leva informação para fora da medula.'],
    where: 'Medula › Segmento: o cordão vermelho que sai pela frente.',
    rel: ['raiz-dorsal', 'corno-ventral', 'nervo-espinhal', 'aferente-eferente'],
  },
  {
    id: 'cinzenta-medular', g: 'med', name: 'Substância cinzenta da medula', aka: 'a borboleta', color: '#D8A7A0', sub: 'segmento',
    rows: [['No modelo', E], ['Partes', 'cornos dorsal, lateral e ventral; zona intermediária']],
    morf: 'O centro da medula em corte transversal, em forma de borboleta. É onde ficam os corpos celulares dos neurônios.',
    func: 'Os neurônios dela começam a análise da informação sensorial, coordenam os movimentos e montam os reflexos simples.',
    where: 'Medula › Segmento e Tractos: a borboleta rosada no centro da secção.',
    rel: ['corno-dorsal', 'corno-ventral', 'corno-lateral', 'zona-intermediaria', 'branca-medular', 'voc-substancia-cinzenta'],
  },
  {
    id: 'corno-dorsal', g: 'med', name: 'Corno dorsal', color: '#7FB2E5', sub: 'segmento',
    rows: [['No modelo', E]],
    morf: 'A parte de cima das asas da borboleta, voltada para as costas.',
    func: 'As células dele recebem as aferências sensoriais que chegam pela raiz dorsal.',
    where: 'Medula › Segmento: as duas pontas de trás da borboleta, azuis quando escolhidas.',
    rel: ['cinzenta-medular', 'raiz-dorsal', 'corno-ventral', 'zona-intermediaria'],
  },
  {
    id: 'corno-ventral', g: 'med', name: 'Corno ventral', color: '#E08A8A', sub: 'segmento',
    rows: [['No modelo', E]],
    morf: 'A parte de baixo das asas da borboleta, voltada para a frente do corpo.',
    func: 'As células motoras dele mandam os axônios pela raiz ventral para inervar os músculos. Os neurônios do córtex motor falam direto com elas.',
    where: 'Medula › Segmento: as duas pontas da frente da borboleta, vermelhas quando escolhidas.',
    rel: ['cinzenta-medular', 'raiz-ventral', 'cortex-motor-primario', 'tracto-corticospinal', 'zona-intermediaria'],
  },
  {
    id: 'corno-lateral', g: 'med', name: 'Corno lateral', color: '#B39DDB', sub: 'segmento',
    rows: [['No modelo', E]],
    morf: 'A saliência lateral da substância cinzenta, entre o corno dorsal e o ventral.',
    func: 'O apêndice só o aponta na figura da medula; não descreve a função.',
    where: 'Medula › Segmento: a pequena ponta do lado da borboleta, lilás quando escolhida.',
    rel: ['cinzenta-medular', 'zona-intermediaria'],
  },
  {
    id: 'zona-intermediaria', g: 'med', name: 'Zona intermediária', color: '#BFAFA8', sub: 'segmento',
    rows: [['No modelo', E]],
    morf: 'A substância cinzenta que fica entre o corno dorsal e o corno ventral.',
    func: 'As células dela são interneurônios. Modulam as saídas motoras em resposta às entradas sensoriais e aos comandos que descem do encéfalo.',
    where: 'Medula › Segmento: o miolo da borboleta, entre os cornos.',
    rel: ['cinzenta-medular', 'corno-dorsal', 'corno-ventral', 'tracto-corticospinal'],
  },
  {
    id: 'branca-medular', g: 'med', name: 'Substância branca da medula', aka: 'colunas dorsal, lateral e ventral', color: '#EFE6D2', sub: 'tractos',
    rows: [['No modelo', E]],
    morf: 'A camada espessa em volta da substância cinzenta. São colunas de axônios longos que sobem e descem pela medula. De cada lado há três: a coluna dorsal, ao longo da superfície de trás; a lateral, ao lado da substância cinzenta; e a ventral, ao longo da superfície da frente.',
    func: 'Há pelo menos meia dúzia de tractos em cada lado. A maioria é de mão única: leva informação para o encéfalo ou do encéfalo para a medula.',
    clueTitle: 'Ao contrário do cérebro',
    clue: 'No prosencéfalo, a substância cinzenta envolve a branca. Na medula, a branca fica por fora e a cinzenta no centro.',
    where: 'Medula › Tractos: tudo o que está em volta da borboleta. As regiões coloridas são os tractos.',
    rel: ['cinzenta-medular', 'coluna-dorsal', 'tracto-corticospinal', 'tracto-espinotalamico', 'substancia-branca'],
  },
  {
    id: 'coluna-dorsal', g: 'med', name: 'Coluna dorsal', color: '#4FC3F7', sub: 'tractos',
    rows: [['No modelo', T], ['Sentido', 'ascendente'], ['Volta em', 'cap. 12']],
    morf: 'A coluna de substância branca da parte de trás da medula, entre os dois cornos dorsais.',
    func: 'Só tem axônios sensoriais que sobem ao encéfalo. É uma via expressa: leva depressa a informação do tato do mesmo lado do corpo até os núcleos da coluna dorsal, no bulbo. É importante para a percepção consciente do tato.',
    where: 'Medula › Tractos: a região azul-clara de trás. Em Vias › Tato, é o primeiro trecho da subida.',
    rel: ['nucleos-da-coluna-dorsal', 'lemnisco-medial', 'raiz-dorsal', 'tracto-espinotalamico', 'branca-medular'],
  },
  {
    id: 'tracto-espinotalamico', g: 'med', name: 'Tracto espinotalâmico', color: '#66BB6A', sub: 'tractos',
    rows: [['No modelo', T], ['Sentido', 'ascendente'], ['Volta em', 'cap. 12']],
    morf: 'Tracto da parte da frente e do lado da substância branca da medula.',
    func: 'Transmite informação sobre os estímulos dolorosos e a temperatura. O nome diz o caminho: da medula ao tálamo.',
    where: 'Medula › Tractos: a região verde, na frente e no lado, na metade das vias sensoriais.',
    rel: ['coluna-dorsal', 'talamo', 'branca-medular', 'cinzenta-periaquedutal'],
  },
  {
    id: 'tracto-corticospinal', g: 'med', name: 'Tracto corticospinal', aka: 'tracto piramidal', color: '#9575CD', sub: 'tractos',
    rows: [['No modelo', T], ['Sentido', 'descendente; via lateral'], ['Volta em', 'cap. 14']],
    morf: 'Tracto de axônios que nascem no córtex cerebral e terminam na medula espinhal. Desce pela cápsula interna, pelo mesencéfalo, pela ponte e pelas pirâmides do bulbo. Na medula, corre na coluna lateral.',
    func: 'É uma via importante do córtex para comandar o movimento voluntário. Os axônios inervam os neurônios da zona intermediária e do corno ventral.',
    clueTitle: 'Cruza no bulbo',
    clue: 'Perto da passagem do bulbo para a medula, o tracto de cada lado cruza a linha média: é a decussação piramidal. Por isso o córtex de um lado comanda os músculos do lado oposto.',
    more: ['É o exemplo que o livro dá de "tracto": axônios com origem e destino em comum.'],
    where: 'Medula › Tractos: a região roxa grande na coluna lateral. Em Vias › Movimento, o caminho inteiro, do giro pré-central à medula.',
    rel: ['cortex-motor-primario', 'capsula-interna', 'piramide-bulbar', 'decussacao-piramidal', 'corno-ventral', 'tracto-rubrospinal', 'voc-tracto'],
  },
  {
    id: 'tracto-rubrospinal', g: 'med', name: 'Tracto rubrospinal', color: '#5C6BC0', sub: 'tractos',
    rows: [['No modelo', T], ['Sentido', 'descendente; via lateral'], ['Volta em', 'cap. 14']],
    morf: 'Tracto pequeno da coluna lateral, logo à frente do corticospinal.',
    func: 'Com o corticospinal, forma a via lateral, que transmite os comandos dos movimentos voluntários, sobretudo das extremidades. Pelo nome: do núcleo rubro à medula.',
    where: 'Medula › Tractos: a pequena região azul-índigo encostada no tracto corticospinal.',
    rel: ['nucleo-rubro', 'tracto-corticospinal', 'branca-medular'],
  },
  {
    id: 'tracto-reticulospinal-bulbar', g: 'med', name: 'Tracto reticulospinal bulbar', color: '#F06292', sub: 'tractos',
    rows: [['No modelo', T], ['Sentido', 'descendente; via ventromedial'], ['Volta em', 'cap. 14']],
    morf: 'Tracto da frente da coluna lateral.',
    func: 'É um dos tractos da via ventromedial, que cuida sobretudo da postura e de certos movimentos reflexos. Pelo nome: da formação reticular do bulbo à medula.',
    where: 'Medula › Tractos: a faixa rosa mais lateral, na metade das vias motoras.',
    rel: ['formacao-reticular', 'tracto-reticulospinal-pontino', 'tracto-vestibulospinal', 'tracto-tectospinal'],
  },
  {
    id: 'tracto-reticulospinal-pontino', g: 'med', name: 'Tracto reticulospinal pontino', color: '#EC407A', sub: 'tractos',
    rows: [['No modelo', T], ['Sentido', 'descendente; via ventromedial'], ['Volta em', 'cap. 14']],
    morf: 'Tracto da coluna ventral, perto da linha média.',
    func: 'É um dos tractos da via ventromedial, que cuida sobretudo da postura e de certos movimentos reflexos. Pelo nome: da formação reticular da ponte à medula.',
    where: 'Medula › Tractos: a região rosa-escura na coluna ventral.',
    rel: ['formacao-reticular', 'tracto-reticulospinal-bulbar', 'tracto-vestibulospinal', 'tracto-tectospinal'],
  },
  {
    id: 'tracto-tectospinal', g: 'med', name: 'Tracto tectospinal', color: '#FF8A65', sub: 'tractos',
    rows: [['No modelo', T], ['Sentido', 'descendente; via ventromedial'], ['Volta em', 'cap. 14']],
    morf: 'Tracto pequeno da coluna ventral, junto à linha média.',
    func: 'É um dos tractos da via ventromedial, que cuida sobretudo da postura e de certos movimentos reflexos. Pelo nome: do teto do mesencéfalo à medula.',
    where: 'Medula › Tractos: a pequena região alaranjada junto à fissura da frente.',
    rel: ['teto', 'coliculo-superior', 'tracto-vestibulospinal', 'tracto-reticulospinal-pontino'],
  },
  {
    id: 'tracto-vestibulospinal', g: 'med', name: 'Tracto vestibulospinal', color: '#FFB74D', sub: 'tractos',
    rows: [['No modelo', T], ['Sentido', 'descendente; via ventromedial'], ['Volta em', 'cap. 14']],
    morf: 'Tracto da coluna ventral, na borda da frente da medula.',
    func: 'Nasce nos núcleos vestibulares do bulbo e termina na medula espinhal. É um dos tractos da via ventromedial, que cuida sobretudo da postura e de certos movimentos reflexos.',
    more: ['É o exemplo do livro de como o nome de um tracto diz de onde ele sai e onde termina.'],
    where: 'Medula › Tractos: as regiões amarelo-alaranjadas na borda ventral.',
    rel: ['nucleos-vestibulares', 'tracto-tectospinal', 'tracto-reticulospinal-pontino', 'tracto-reticulospinal-bulbar'],
  },
];
