// Fichas: do tubo neural ao encéfalo. Fonte: cap. 7 (ver 01-geral.pt.js).
const E = 'desenho esquemático, fora de escala, como as figuras do livro', C = 'conceito, sem peça própria';

export default [
  {
    id: 'folhetos', g: 'dev', name: 'Ectoderma, mesoderma e endoderma', aka: 'as três camadas do embrião', color: '#90CAF9', sub: 'origem',
    rows: [['No modelo', E]],
    morf: 'No início, o embrião é um disco plano com três camadas de células: ectoderma, mesoderma e endoderma.',
    func: 'O endoderma dá o revestimento de muitos órgãos internos. O mesoderma dá os ossos e os músculos. O sistema nervoso e a pele vêm inteiros do ectoderma.',
    where: 'Origem, passo 1: as três lâminas empilhadas, azul (ectoderma), rosa (mesoderma) e amarela (endoderma).',
    rel: ['placa-neural', 'somitos', 'tubo-neural'],
  },
  {
    id: 'placa-neural', g: 'dev', name: 'Placa neural', color: '#8BC34A', sub: 'origem',
    rows: [['No modelo', E], ['Quando', 'cerca de 17 dias após a fecundação']],
    morf: 'A região do ectoderma de onde nasce o sistema nervoso. Nessa fase, o encéfalo é só uma camada achatada de células.',
    func: 'É o ponto de partida. Dela vêm o sulco neural, o tubo neural e a crista neural.',
    where: 'Origem, passo 1: a faixa verde no meio do ectoderma.',
    rel: ['folhetos', 'sulco-neural', 'tubo-neural'],
  },
  {
    id: 'sulco-neural', g: 'dev', name: 'Sulco neural e pregas neurais', color: '#7CB342', sub: 'origem',
    rows: [['No modelo', E]],
    morf: 'Um sulco se forma na placa neural e corre de rostral a caudal. As paredes do sulco são as pregas neurais.',
    func: 'As pregas se aproximam e se fundem dorsalmente. Assim o sulco se fecha em tubo.',
    where: 'Origem, passo 2: a placa verde afunda no meio e as bordas roxas sobem.',
    rel: ['placa-neural', 'tubo-neural', 'crista-neural'],
  },
  {
    id: 'tubo-neural', g: 'dev', name: 'Tubo neural', color: '#66BB6A', sub: 'origem',
    rows: [['No modelo', E], ['Quando', 'fecha em torno de 22 dias após a fecundação']],
    morf: 'Tubo cheio de líquido que se forma quando as pregas neurais se fundem. O processo que transforma a placa neural em tubo neural chama-se neurulação.',
    func: 'Todo o sistema nervoso central se desenvolve das paredes do tubo neural. O interior do tubo vira o sistema ventricular do adulto.',
    clueTitle: 'Quando o tubo não fecha',
    clue: 'A fusão das pregas começa no meio e avança para a frente e para trás. A falha em fechar é um defeito congênito comum, cerca de 1 em cada 500 nascidos vivos. O livro relata que muitos casos estão ligados à falta de ácido fólico na dieta materna nas semanas depois da concepção.',
    more: [
      'O eixo definido pelo tubo neural é o neuroeixo. No ser humano ele se curva, sobretudo na junção do mesencéfalo com o tálamo.',
      'A parte rostral do tubo dá o encéfalo; a caudal dá a medula espinhal.',
    ],
    where: 'Origem, passo 3: o tubo verde fechado, com o canal no centro.',
    rel: ['sulco-neural', 'crista-neural', 'prosencefalo', 'mesencefalo', 'rombencefalo', 'sistema-ventricular', 'snc'],
  },
  {
    id: 'crista-neural', g: 'dev', name: 'Crista neural', color: '#AB7FD4', sub: 'origem',
    rows: [['No modelo', E]],
    morf: 'Pedaços do ectoderma neural que se desprendem quando as pregas se juntam e ficam ao lado do tubo neural.',
    func: 'Todos os neurônios com corpo celular no sistema nervoso periférico derivam da crista neural.',
    where: 'Origem, passo 3: os dois grupos roxos acima e ao lado do tubo.',
    rel: ['tubo-neural', 'snp', 'ganglio-da-raiz-dorsal', 'somitos'],
  },
  {
    id: 'somitos', g: 'dev', name: 'Somitos', color: '#F48FB1', sub: 'origem',
    rows: [['No modelo', E]],
    morf: 'Saliências de mesoderma, de cada lado do tubo neural.',
    func: 'Deles se desenvolvem as 33 vértebras da coluna vertebral e os músculos esqueléticos ligados a elas. Os nervos que inervam esses músculos são os nervos motores somáticos.',
    where: 'Origem, passo 3: os blocos rosados de cada lado do tubo.',
    rel: ['folhetos', 'coluna-vertebral', 'tubo-neural', 'crista-neural'],
  },
  {
    id: 'prosencefalo', g: 'dev', name: 'Prosencéfalo', aka: 'encéfalo anterior', color: '#6F9BE0', sub: 'origem',
    rows: [['No modelo', E], ['Dá origem a', 'telencéfalo, diencéfalo e vesículas ópticas']],
    morf: 'A mais rostral das três vesículas primárias do tubo neural. Pró vem do grego para "antes de".',
    func: 'No adulto, é o local das percepções, da consciência, da cognição e da ação voluntária. Tudo isso depende de conexões amplas com os neurônios sensoriais e motores do tronco encefálico e da medula.',
    more: ['Dele brotam, de cada lado, uma vesícula óptica e uma vesícula telencefálica. O que fica no meio, ímpar, é o diencéfalo.'],
    where: 'Origem, passo 4: a dilatação azul, na ponta rostral do tubo. No Atlas, modo de cores Origem: tudo o que é azul.',
    rel: ['telencefalo', 'diencefalo', 'vesicula-optica', 'mesencefalo', 'rombencefalo', 'tubo-neural'],
  },
  {
    id: 'telencefalo', g: 'dev', name: 'Telencéfalo', aka: 'os dois hemisférios cerebrais', color: '#8FB4E8', sub: 'origem',
    rows: [['No modelo', E + '; no Atlas, malha anatômica'], ['Referência', 'ventrículos laterais']],
    morf: 'As duas vesículas telencefálicas, juntas. O nome quer dizer "extremo do encéfalo". No adulto são os dois hemisférios cerebrais.',
    func: 'Quatro coisas acontecem nele. As vesículas crescem para trás e passam a cobrir o diencéfalo por cima e pelos lados. Um par de vesículas brota da face ventral e dá os bulbos olfatórios. As células da parede se dividem e formam o córtex cerebral e o telencéfalo basal. E a substância branca se desenvolve.',
    more: [
      'Derivados no adulto: bulbo olfatório, córtex cerebral, telencéfalo basal, corpo caloso, substância branca cortical e cápsula interna.',
      'As faces ventromediais dos hemisférios se fundem com as faces laterais do diencéfalo.',
    ],
    where: 'Origem, passos 5 a 7: as duas bolsas azul-claras que crescem. No Atlas, modo Origem: azul-claro.',
    rel: ['prosencefalo', 'diencefalo', 'cerebro', 'ventriculo-lateral', 'cortex-cerebral', 'telencefalo-basal'],
  },
  {
    id: 'diencefalo', g: 'dev', name: 'Diencéfalo', aka: '"entre os encéfalos"', color: '#4F7DD1', sub: 'origem',
    rows: [['No modelo', E + '; no Atlas, malha anatômica'], ['Referência', 'terceiro ventrículo']],
    morf: 'A parte central e ímpar do prosencéfalo, que sobra depois que as vesículas ópticas e telencefálicas brotam.',
    func: 'Diferencia-se em duas estruturas: o tálamo e o hipotálamo. O espaço no centro dele é o terceiro ventrículo.',
    more: ['Em corte coronal, o terceiro ventrículo em forma de fenda alongada é um bom sinal de que se está no diencéfalo.'],
    where: 'Origem, passos 5 a 7: a parte azul-escura no meio, entre as bolsas do telencéfalo. No Atlas, modo Origem: azul-escuro.',
    rel: ['prosencefalo', 'telencefalo', 'talamo', 'hipotalamo', 'terceiro-ventriculo', 'tronco-encefalico'],
  },
  {
    id: 'vesicula-optica', g: 'dev', name: 'Vesícula óptica', aka: 'pedículo e cálice ópticos', color: '#5C8FD6', sub: 'origem',
    rows: [['No modelo', E]],
    morf: 'Vesícula par que brota de cada lado do prosencéfalo. Ela cresce e se invagina, formando o pedículo óptico e o cálice óptico.',
    func: 'O pedículo vira o nervo óptico; o cálice vira a retina. Por isso a retina e o nervo óptico são partes do encéfalo.',
    where: 'Origem, passo 5: as duas pequenas bolsas azuis de baixo, com a ponta em taça.',
    rel: ['prosencefalo', 'nervo-optico', 'olho'],
  },
  {
    id: 'rombencefalo', g: 'dev', name: 'Rombencéfalo', aka: 'encéfalo posterior', color: '#7CC07E', sub: 'origem',
    rows: [['No modelo', E], ['Dá origem a', 'cerebelo, ponte e bulbo'], ['Referência', 'quarto ventrículo']],
    morf: 'A mais caudal das três vesículas primárias. Une-se ao tubo neural caudal, que dá a medula espinhal.',
    func: 'A metade rostral dá o cerebelo e a ponte; a caudal dá o bulbo. No adulto, é passagem obrigatória entre o prosencéfalo e a medula, e contribui para o processamento sensorial, o controle do movimento e a regulação do sistema nervoso visceral.',
    more: ['O interior do tubo, nesse trecho, vira o quarto ventrículo.'],
    where: 'Origem, passo 4: a dilatação verde, a terceira. No Atlas, modo Origem: tudo o que é verde.',
    rel: ['cerebelo', 'ponte', 'bulbo', 'labios-rombicos', 'quarto-ventriculo', 'mesencefalo', 'prosencefalo'],
  },
  {
    id: 'labios-rombicos', g: 'dev', name: 'Lábios rômbicos', color: '#3E9A58', sub: 'origem',
    rows: [['No modelo', E]],
    morf: 'O tecido da parede dorsolateral do rombencéfalo rostral.',
    func: 'Crescem em direção dorsal e para o meio até se fundirem um com o outro. A aba que resulta vira o cerebelo.',
    where: 'Origem, passo 9: as duas abas verde-escuras que se fecham sobre o quarto ventrículo.',
    rel: ['cerebelo', 'rombencefalo', 'quarto-ventriculo', 'ponte'],
  },
  {
    id: 'diferenciacao', g: 'dev', name: 'Diferenciação', color: '#A7B5C9', kind: 'termo', sub: 'origem',
    rows: [['No modelo', C]],
    morf: 'O processo pelo qual as estruturas ficam mais complexas e funcionalmente especializadas durante o desenvolvimento.',
    func: 'A primeira etapa da diferenciação do encéfalo é o aparecimento de três dilatações na ponta rostral do tubo neural: as vesículas primárias. O encéfalo inteiro vem delas.',
    where: 'Origem: cada passo a partir do 4 é uma etapa da diferenciação.',
    rel: ['tubo-neural', 'prosencefalo', 'mesencefalo', 'rombencefalo'],
  },
];
